// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { CGPoint, CGSize, NSAffineTransformStruct } from "../structs.js";

export declare class _NSAffineTransform extends _NSObject {
  static alloc(): _NSAffineTransform;
  static new(): _NSAffineTransform;
  // Class methods
  static transform(): _NSAffineTransform;

  // Instance methods
  initWithTransform$(transform: _NSAffineTransform): _NSAffineTransform;
  init(): _NSAffineTransform;
  translateXBy$yBy$(deltaX: number, deltaY: number): void;
  rotateByDegrees$(angle: number): void;
  rotateByRadians$(angle: number): void;
  scaleBy$(scale: number): void;
  scaleXBy$yBy$(scaleX: number, scaleY: number): void;
  invert(): void;
  appendTransform$(transform: _NSAffineTransform): void;
  prependTransform$(transform: _NSAffineTransform): void;
  transformPoint$(aPoint: CGPoint): CGPoint;
  transformSize$(aSize: CGSize): CGSize;

  // Properties
  transformStruct(): NSAffineTransformStruct;
  setTransformStruct$(value: NSAffineTransformStruct): void;
}
