// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAppleEventDescriptor } from "./NSAppleEventDescriptor.js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSAppleEventManager extends _NSObject {
  static alloc(): _NSAppleEventManager;
  static new(): _NSAppleEventManager;
  init(): _NSAppleEventManager;
  // Class methods
  static sharedAppleEventManager(): _NSAppleEventManager;

  // Instance methods
  setEventHandler$andSelector$forEventClass$andEventID$(handler: NobjcObject, handleEventSelector: string, eventClass: NobjcObject, eventID: NobjcObject): void;
  removeEventHandlerForEventClass$andEventID$(eventClass: NobjcObject, eventID: NobjcObject): void;
  dispatchRawAppleEvent$withRawReply$handlerRefCon$(theAppleEvent: NobjcObject, theReply: NobjcObject, handlerRefCon: NobjcObject): NobjcObject;
  suspendCurrentAppleEvent(): number | null;
  appleEventForSuspensionID$(suspensionID: number): _NSAppleEventDescriptor;
  replyAppleEventForSuspensionID$(suspensionID: number): _NSAppleEventDescriptor;
  setCurrentAppleEventAndReplyEventWithSuspensionID$(suspensionID: number): void;
  resumeWithSuspensionID$(suspensionID: number): void;

  // Properties
  currentAppleEvent(): _NSAppleEventDescriptor | null;
  currentReplyAppleEvent(): _NSAppleEventDescriptor | null;
}
