// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAppleEventDescriptor } from "./NSAppleEventDescriptor.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSAppleScript extends _NSObject {
  static alloc(): _NSAppleScript;
  static new(): _NSAppleScript;
  init(): _NSAppleScript;
  // Instance methods
  initWithContentsOfURL$error$(url: _NSURL, errorInfo: NobjcObject): _NSAppleScript | null;
  initWithSource$(source: _NSString): _NSAppleScript | null;
  compileAndReturnError$(errorInfo: NobjcObject): boolean;
  executeAndReturnError$(errorInfo: NobjcObject): _NSAppleEventDescriptor;
  executeAppleEvent$error$(event: _NSAppleEventDescriptor, errorInfo: NobjcObject): _NSAppleEventDescriptor;

  // Properties
  source(): _NSString | null;
  compiled(): boolean;
}
