// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "./NSCoder.js";
import type { _NSData } from "./NSData.js";
import type { _NSEnumerator } from "./NSEnumerator.js";
import type { _NSIndexSet } from "./NSIndexSet.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSOrderedCollectionDifference } from "./NSOrderedCollectionDifference.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";
import type { NSRange } from "../structs.js";

export declare class _NSArray extends _NSObject {
  static alloc(): _NSArray;
  static new(): _NSArray;
  // Class methods
  static array(): _NSArray;
  static arrayWithObject$(anObject: NobjcObject): _NSArray;
  static arrayWithObjects$count$(objects: NobjcObject, cnt: number): _NSArray;
  static arrayWithObjects$(firstObj: NobjcObject): _NSArray;
  static arrayWithArray$(array: _NSArray): _NSArray;
  static arrayWithContentsOfURL$error$(url: _NSURL, error: NobjcObject): _NSArray | null;
  static arrayWithContentsOfFile$(path: _NSString): _NSArray | null;
  static arrayWithContentsOfURL$(url: _NSURL): _NSArray | null;

  // Instance methods
  objectAtIndex$(index: number): NobjcObject;
  init(): _NSArray;
  initWithObjects$count$(objects: NobjcObject, cnt: number): _NSArray;
  initWithCoder$(coder: _NSCoder): _NSArray | null;
  arrayByAddingObject$(anObject: NobjcObject): _NSArray;
  arrayByAddingObjectsFromArray$(otherArray: _NSArray): _NSArray;
  componentsJoinedByString$(separator: _NSString): _NSString;
  containsObject$(anObject: NobjcObject): boolean;
  descriptionWithLocale$(locale: NobjcObject): _NSString;
  descriptionWithLocale$indent$(locale: NobjcObject, level: number): _NSString;
  firstObjectCommonWithArray$(otherArray: _NSArray): NobjcObject;
  getObjects$range$(objects: NobjcObject, range: NSRange): void;
  indexOfObject$(anObject: NobjcObject): number;
  indexOfObject$inRange$(anObject: NobjcObject, range: NSRange): number;
  indexOfObjectIdenticalTo$(anObject: NobjcObject): number;
  indexOfObjectIdenticalTo$inRange$(anObject: NobjcObject, range: NSRange): number;
  isEqualToArray$(otherArray: _NSArray): boolean;
  objectEnumerator(): _NSEnumerator;
  reverseObjectEnumerator(): _NSEnumerator;
  sortedArrayUsingFunction$context$(comparator: (...args: any[]) => any | null, context: NobjcObject): _NSArray;
  sortedArrayUsingFunction$context$hint$(comparator: (...args: any[]) => any | null, context: NobjcObject, hint: _NSData | null): _NSArray;
  sortedArrayUsingSelector$(comparator: string): _NSArray;
  subarrayWithRange$(range: NSRange): _NSArray;
  writeToURL$error$(url: _NSURL, error: NobjcObject): boolean;
  makeObjectsPerformSelector$(aSelector: string): void;
  makeObjectsPerformSelector$withObject$(aSelector: string, argument: NobjcObject): void;
  objectsAtIndexes$(indexes: _NSIndexSet): _NSArray;
  objectAtIndexedSubscript$(idx: number): NobjcObject;
  enumerateObjectsUsingBlock$(block: (...args: any[]) => any): void;
  enumerateObjectsWithOptions$usingBlock$(opts: number, block: (...args: any[]) => any): void;
  enumerateObjectsAtIndexes$options$usingBlock$(s: _NSIndexSet, opts: number, block: (...args: any[]) => any): void;
  indexOfObjectPassingTest$(predicate: (...args: any[]) => any): number;
  indexOfObjectWithOptions$passingTest$(opts: number, predicate: (...args: any[]) => any): number;
  indexOfObjectAtIndexes$options$passingTest$(s: _NSIndexSet, opts: number, predicate: (...args: any[]) => any): number;
  indexesOfObjectsPassingTest$(predicate: (...args: any[]) => any): _NSIndexSet;
  indexesOfObjectsWithOptions$passingTest$(opts: number, predicate: (...args: any[]) => any): _NSIndexSet;
  indexesOfObjectsAtIndexes$options$passingTest$(s: _NSIndexSet, opts: number, predicate: (...args: any[]) => any): _NSIndexSet;
  sortedArrayUsingComparator$(cmptr: number): _NSArray;
  sortedArrayWithOptions$usingComparator$(opts: number, cmptr: number): _NSArray;
  indexOfObject$inSortedRange$options$usingComparator$(obj: NobjcObject, r: NSRange, opts: number, cmp: number): number;
  initWithObjects$(firstObj: NobjcObject): _NSArray;
  initWithArray$(array: _NSArray): _NSArray;
  initWithArray$copyItems$(array: _NSArray, flag: boolean): _NSArray;
  initWithContentsOfURL$error$(url: _NSURL, error: NobjcObject): _NSArray | null;
  differenceFromArray$withOptions$usingEquivalenceTest$(other: _NSArray, options: number, block: (...args: any[]) => any): _NSOrderedCollectionDifference;
  differenceFromArray$withOptions$(other: _NSArray, options: number): _NSOrderedCollectionDifference;
  differenceFromArray$(other: _NSArray): _NSOrderedCollectionDifference;
  arrayByApplyingDifference$(difference: _NSOrderedCollectionDifference): _NSArray | null;
  getObjects$(objects: NobjcObject): void;
  initWithContentsOfFile$(path: _NSString): _NSArray | null;
  initWithContentsOfURL$(url: _NSURL): _NSArray | null;
  writeToFile$atomically$(path: _NSString, useAuxiliaryFile: boolean): boolean;
  writeToURL$atomically$(url: _NSURL, atomically: boolean): boolean;

  // Properties
  count(): number;
  description(): _NSString;
  firstObject(): NobjcObject;
  lastObject(): NobjcObject;
  sortedArrayHint(): _NSData;
}
