// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "./NSCoder.js";
import type { _NSData } from "./NSData.js";
import type { _NSMutableData } from "./NSMutableData.js";
import type { _NSString } from "./NSString.js";

export declare class _NSArchiver extends _NSCoder {
  static alloc(): _NSArchiver;
  static new(): _NSArchiver;
  init(): _NSArchiver;
  // Class methods
  static archivedDataWithRootObject$(rootObject: NobjcObject): _NSData;
  static archiveRootObject$toFile$(rootObject: NobjcObject, path: _NSString): boolean;

  // Instance methods
  initForWritingWithMutableData$(mdata: _NSMutableData): _NSArchiver;
  encodeRootObject$(rootObject: NobjcObject): void;
  encodeConditionalObject$(object_: NobjcObject): void;
  encodeClassName$intoClassName$(trueName: _NSString, inArchiveName: _NSString): void;
  classNameEncodedForTrueClassName$(trueName: _NSString): _NSString | null;
  replaceObject$withObject$(object_: NobjcObject, newObject: NobjcObject): void;

  // Properties
  archiverData(): _NSMutableData;
}
