// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";
import type { NSRange } from "../structs.js";

export declare class _NSAttributedStringMarkdownSourcePosition extends _NSObject {
  static alloc(): _NSAttributedStringMarkdownSourcePosition;
  static new(): _NSAttributedStringMarkdownSourcePosition;
  init(): _NSAttributedStringMarkdownSourcePosition;
  // Instance methods
  initWithStartLine$startColumn$endLine$endColumn$(startLine: number, startColumn: number, endLine: number, endColumn: number): _NSAttributedStringMarkdownSourcePosition;
  rangeInString$(string_: _NSString): NSRange;

  // Properties
  startLine(): number;
  startColumn(): number;
  endLine(): number;
  endColumn(): number;
}
