// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSOperation } from "./NSOperation.js";

export declare class _NSBlockOperation extends _NSOperation {
  static alloc(): _NSBlockOperation;
  static new(): _NSBlockOperation;
  init(): _NSBlockOperation;
  // Class methods
  static blockOperationWithBlock$(block: (...args: any[]) => any): _NSBlockOperation;

  // Instance methods
  addExecutionBlock$(block: (...args: any[]) => any): void;

  // Properties
  executionBlocks(): (...args: any[]) => any;
}
