// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSBundle } from "./NSBundle.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSProgress } from "./NSProgress.js";
import type { _NSSet } from "./NSSet.js";

export declare class _NSBundleResourceRequest extends _NSObject {
  static alloc(): _NSBundleResourceRequest;
  static new(): _NSBundleResourceRequest;
  init(): _NSBundleResourceRequest;
  // Instance methods
  initWithTags$(tags: _NSSet): _NSBundleResourceRequest;
  initWithTags$bundle$(tags: _NSSet, bundle: _NSBundle): _NSBundleResourceRequest;
  beginAccessingResourcesWithCompletionHandler$(completionHandler: (...args: any[]) => any | null): void;
  conditionallyBeginAccessingResourcesWithCompletionHandler$(completionHandler: (...args: any[]) => any): void;
  endAccessingResources(): void;

  // Properties
  loadingPriority(): number;
  setLoadingPriority$(value: number): void;
  tags(): _NSSet;
  bundle(): _NSBundle;
  progress(): _NSProgress;
}
