// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";

export interface _NSCopying {
  // Instance methods
  copyWithZone$?(zone: NobjcObject): NobjcObject;
}
