// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSScriptClassDescription } from "./NSScriptClassDescription.js";
import type { _NSScriptCommand } from "./NSScriptCommand.js";

export declare class _NSCreateCommand extends _NSScriptCommand {
  static alloc(): _NSCreateCommand;
  static new(): _NSCreateCommand;
  init(): _NSCreateCommand;
  // Properties
  createClassDescription(): _NSScriptClassDescription;
  resolvedKeyDictionary(): _NSDictionary;
}
