// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "./NSCoder.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSDate extends _NSObject {
  static alloc(): _NSDate;
  static new(): _NSDate;
  // Class methods
  static date(): _NSDate;
  static dateWithTimeIntervalSinceNow$(secs: number): _NSDate;
  static dateWithTimeIntervalSinceReferenceDate$(ti: number): _NSDate;
  static dateWithTimeIntervalSince1970$(secs: number): _NSDate;
  static dateWithTimeInterval$sinceDate$(secsToBeAdded: number, date: _NSDate): _NSDate;
  static distantFuture(): _NSDate;
  static distantPast(): _NSDate;
  static now(): _NSDate;

  // Instance methods
  init(): _NSDate;
  initWithTimeIntervalSinceReferenceDate$(ti: number): _NSDate;
  initWithCoder$(coder: _NSCoder): _NSDate | null;
  timeIntervalSinceDate$(anotherDate: _NSDate): number;
  addTimeInterval$(seconds: number): NobjcObject;
  dateByAddingTimeInterval$(ti: number): _NSDate;
  earlierDate$(anotherDate: _NSDate): _NSDate;
  laterDate$(anotherDate: _NSDate): _NSDate;
  compare$(other: _NSDate): number;
  isEqualToDate$(otherDate: _NSDate): boolean;
  descriptionWithLocale$(locale: NobjcObject): _NSString;
  initWithTimeIntervalSinceNow$(secs: number): _NSDate;
  initWithTimeIntervalSince1970$(secs: number): _NSDate;
  initWithTimeInterval$sinceDate$(secsToBeAdded: number, date: _NSDate): _NSDate;

  // Properties
  timeIntervalSinceReferenceDate(): number;
  timeIntervalSinceNow(): number;
  timeIntervalSince1970(): number;
  description(): _NSString;
}
