// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDecimalNumber } from "./NSDecimalNumber.js";

export interface _NSDecimalNumberBehaviors {
  // Instance methods
  roundingMode?(): number;
  scale?(): number;
  exceptionDuringOperation$error$leftOperand$rightOperand$?(operation: string, error: number, leftOperand: _NSDecimalNumber, rightOperand: _NSDecimalNumber | null): _NSDecimalNumber | null;
}
