// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSDecimalNumberHandler extends _NSObject {
  static alloc(): _NSDecimalNumberHandler;
  static new(): _NSDecimalNumberHandler;
  init(): _NSDecimalNumberHandler;
  // Class methods
  static decimalNumberHandlerWithRoundingMode$scale$raiseOnExactness$raiseOnOverflow$raiseOnUnderflow$raiseOnDivideByZero$(roundingMode: number, scale: number, exact: boolean, overflow: boolean, underflow: boolean, divideByZero: boolean): _NSDecimalNumberHandler;
  static defaultDecimalNumberHandler(): _NSDecimalNumberHandler;

  // Instance methods
  initWithRoundingMode$scale$raiseOnExactness$raiseOnOverflow$raiseOnUnderflow$raiseOnDivideByZero$(roundingMode: number, scale: number, exact: boolean, overflow: boolean, underflow: boolean, divideByZero: boolean): _NSDecimalNumberHandler;
}
