// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSNumber } from "./NSNumber.js";
import type { _NSString } from "./NSString.js";

export declare class _NSDecimalNumber extends _NSNumber {
  static alloc(): _NSDecimalNumber;
  static new(): _NSDecimalNumber;
  init(): _NSDecimalNumber;
  // Class methods
  static decimalNumberWithMantissa$exponent$isNegative$(mantissa: number, exponent: number, flag: boolean): _NSDecimalNumber;
  static decimalNumberWithDecimal$(dcm: number): _NSDecimalNumber;
  static decimalNumberWithString$(numberValue: _NSString | null): _NSDecimalNumber;
  static decimalNumberWithString$locale$(numberValue: _NSString | null, locale: NobjcObject): _NSDecimalNumber;
  static zero(): _NSDecimalNumber;
  static one(): _NSDecimalNumber;
  static minimumDecimalNumber(): _NSDecimalNumber;
  static maximumDecimalNumber(): _NSDecimalNumber;
  static notANumber(): _NSDecimalNumber;
  static defaultBehavior(): NobjcObject;
  static setDefaultBehavior$(value: NobjcObject): void;

  // Instance methods
  initWithMantissa$exponent$isNegative$(mantissa: number, exponent: number, flag: boolean): _NSDecimalNumber;
  initWithDecimal$(dcm: number): _NSDecimalNumber;
  initWithString$(numberValue: _NSString | null): _NSDecimalNumber;
  initWithString$locale$(numberValue: _NSString | null, locale: NobjcObject): _NSDecimalNumber;
  descriptionWithLocale$(locale: NobjcObject): _NSString;
  decimalNumberByAdding$(decimalNumber: _NSDecimalNumber): _NSDecimalNumber;
  decimalNumberByAdding$withBehavior$(decimalNumber: _NSDecimalNumber, behavior: NobjcObject): _NSDecimalNumber;
  decimalNumberBySubtracting$(decimalNumber: _NSDecimalNumber): _NSDecimalNumber;
  decimalNumberBySubtracting$withBehavior$(decimalNumber: _NSDecimalNumber, behavior: NobjcObject): _NSDecimalNumber;
  decimalNumberByMultiplyingBy$(decimalNumber: _NSDecimalNumber): _NSDecimalNumber;
  decimalNumberByMultiplyingBy$withBehavior$(decimalNumber: _NSDecimalNumber, behavior: NobjcObject): _NSDecimalNumber;
  decimalNumberByDividingBy$(decimalNumber: _NSDecimalNumber): _NSDecimalNumber;
  decimalNumberByDividingBy$withBehavior$(decimalNumber: _NSDecimalNumber, behavior: NobjcObject): _NSDecimalNumber;
  decimalNumberByRaisingToPower$(power: number): _NSDecimalNumber;
  decimalNumberByRaisingToPower$withBehavior$(power: number, behavior: NobjcObject): _NSDecimalNumber;
  decimalNumberByMultiplyingByPowerOf10$(power: number): _NSDecimalNumber;
  decimalNumberByMultiplyingByPowerOf10$withBehavior$(power: number, behavior: NobjcObject): _NSDecimalNumber;
  decimalNumberByRoundingAccordingToBehavior$(behavior: NobjcObject): _NSDecimalNumber;
  compare$(decimalNumber: _NSNumber): number;

  // Properties
  decimalValue(): number;
  objCType(): NobjcObject;
  doubleValue(): number;
}
