// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDate } from "./NSDate.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSDistributedLock extends _NSObject {
  static alloc(): _NSDistributedLock;
  static new(): _NSDistributedLock;
  init(): _NSDistributedLock;
  // Class methods
  static lockWithPath$(path: _NSString): _NSDistributedLock | null;

  // Instance methods
  initWithPath$(path: _NSString): _NSDistributedLock | null;
  tryLock(): boolean;
  unlock(): void;
  breakLock(): void;

  // Properties
  lockDate(): _NSDate;
}
