// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSException extends _NSObject {
  static alloc(): _NSException;
  static new(): _NSException;
  init(): _NSException;
  // Class methods
  static exceptionWithName$reason$userInfo$(name: number, reason: _NSString | null, userInfo: _NSDictionary | null): _NSException;
  static raise$format$(name: number, format: _NSString): void;
  static raise$format$arguments$(name: number, format: _NSString, argList: NobjcObject): void;

  // Instance methods
  initWithName$reason$userInfo$(aName: number, aReason: _NSString | null, aUserInfo: _NSDictionary | null): _NSException;
  raise(): void;

  // Properties
  name(): number;
  reason(): _NSString | null;
  userInfo(): _NSDictionary | null;
  callStackReturnAddresses(): _NSArray;
  callStackSymbols(): _NSArray;
}
