// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSError } from "./NSError.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSExtensionContext extends _NSObject {
  static alloc(): _NSExtensionContext;
  static new(): _NSExtensionContext;
  init(): _NSExtensionContext;
  // Instance methods
  completeRequestReturningItems$completionHandler$(items: _NSArray | null, completionHandler: (...args: any[]) => any | null): void;
  cancelRequestWithError$(error: _NSError): void;
  openURL$completionHandler$(URL: _NSURL, completionHandler: (...args: any[]) => any | null): void;
}
