// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSOperationQueue } from "./NSOperationQueue.js";
import type { _NSSet } from "./NSSet.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSFileCoordinator extends _NSObject {
  static alloc(): _NSFileCoordinator;
  static new(): _NSFileCoordinator;
  init(): _NSFileCoordinator;
  // Class methods
  static addFilePresenter$(filePresenter: NobjcObject): void;
  static removeFilePresenter$(filePresenter: NobjcObject): void;
  static filePresenters(): NobjcObject;

  // Instance methods
  initWithFilePresenter$(filePresenterOrNil: NobjcObject): _NSFileCoordinator;
  coordinateAccessWithIntents$queue$byAccessor$(intents: _NSArray, queue: _NSOperationQueue, accessor: (...args: any[]) => any | null): void;
  coordinateReadingItemAtURL$options$error$byAccessor$(url: _NSURL, options: number, outError: NobjcObject, reader: (...args: any[]) => any): void;
  coordinateWritingItemAtURL$options$error$byAccessor$(url: _NSURL, options: number, outError: NobjcObject, writer: (...args: any[]) => any): void;
  coordinateReadingItemAtURL$options$writingItemAtURL$options$error$byAccessor$(readingURL: _NSURL, readingOptions: number, writingURL: _NSURL, writingOptions: number, outError: NobjcObject, readerWriter: (...args: any[]) => any): void;
  coordinateWritingItemAtURL$options$writingItemAtURL$options$error$byAccessor$(url1: _NSURL, options1: number, url2: _NSURL, options2: number, outError: NobjcObject, writer: (...args: any[]) => any): void;
  prepareForReadingItemsAtURLs$options$writingItemsAtURLs$options$error$byAccessor$(readingURLs: _NSArray, readingOptions: number, writingURLs: _NSArray, writingOptions: number, outError: NobjcObject, batchAccessor: (...args: any[]) => any): void;
  itemAtURL$willMoveToURL$(oldURL: _NSURL, newURL: _NSURL): void;
  itemAtURL$didMoveToURL$(oldURL: _NSURL, newURL: _NSURL): void;
  itemAtURL$didChangeUbiquityAttributes$(url: _NSURL, attributes: _NSSet): void;
  cancel(): void;

  // Properties
  purposeIdentifier(): _NSString;
  setPurposeIdentifier$(value: _NSString): void;
}
