// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSCoder } from "./NSCoder.js";
import type { _NSData } from "./NSData.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSFileHandle extends _NSObject {
  static alloc(): _NSFileHandle;
  static new(): _NSFileHandle;
  init(): _NSFileHandle;
  // Class methods
  static fileHandleForReadingAtPath$(path: _NSString): _NSFileHandle | null;
  static fileHandleForWritingAtPath$(path: _NSString): _NSFileHandle | null;
  static fileHandleForUpdatingAtPath$(path: _NSString): _NSFileHandle | null;
  static fileHandleForReadingFromURL$error$(url: _NSURL, error: NobjcObject): _NSFileHandle | null;
  static fileHandleForWritingToURL$error$(url: _NSURL, error: NobjcObject): _NSFileHandle | null;
  static fileHandleForUpdatingURL$error$(url: _NSURL, error: NobjcObject): _NSFileHandle | null;
  static fileHandleWithStandardInput(): _NSFileHandle;
  static fileHandleWithStandardOutput(): _NSFileHandle;
  static fileHandleWithStandardError(): _NSFileHandle;
  static fileHandleWithNullDevice(): _NSFileHandle;

  // Instance methods
  initWithFileDescriptor$closeOnDealloc$(fd: number, closeopt: boolean): _NSFileHandle;
  initWithCoder$(coder: _NSCoder): _NSFileHandle | null;
  readDataToEndOfFileAndReturnError$(error: NobjcObject): _NSData | null;
  readDataUpToLength$error$(length: number, error: NobjcObject): _NSData | null;
  writeData$error$(data: _NSData, error: NobjcObject): boolean;
  getOffset$error$(offsetInFile: NobjcObject, error: NobjcObject): boolean;
  seekToEndReturningOffset$error$(offsetInFile: NobjcObject, error: NobjcObject): boolean;
  seekToOffset$error$(offset: number, error: NobjcObject): boolean;
  truncateAtOffset$error$(offset: number, error: NobjcObject): boolean;
  synchronizeAndReturnError$(error: NobjcObject): boolean;
  closeAndReturnError$(error: NobjcObject): boolean;
  readInBackgroundAndNotifyForModes$(modes: _NSArray | null): void;
  readInBackgroundAndNotify(): void;
  readToEndOfFileInBackgroundAndNotifyForModes$(modes: _NSArray | null): void;
  readToEndOfFileInBackgroundAndNotify(): void;
  acceptConnectionInBackgroundAndNotifyForModes$(modes: _NSArray | null): void;
  acceptConnectionInBackgroundAndNotify(): void;
  waitForDataInBackgroundAndNotifyForModes$(modes: _NSArray | null): void;
  waitForDataInBackgroundAndNotify(): void;
  initWithFileDescriptor$(fd: number): _NSFileHandle;
  readDataToEndOfFile(): _NSData;
  readDataOfLength$(length: number): _NSData;
  writeData$(data: _NSData): void;
  seekToEndOfFile(): number;
  seekToFileOffset$(offset: number): void;
  truncateFileAtOffset$(offset: number): void;
  synchronizeFile(): void;
  closeFile(): void;

  // Properties
  availableData(): _NSData;
  readabilityHandler(): (...args: any[]) => any | null;
  setReadabilityHandler$(value: (...args: any[]) => any | null): void;
  writeabilityHandler(): (...args: any[]) => any | null;
  setWriteabilityHandler$(value: (...args: any[]) => any | null): void;
  fileDescriptor(): number;
  offsetInFile(): number;
}
