// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSFileAccessIntent extends _NSObject {
  static alloc(): _NSFileAccessIntent;
  static new(): _NSFileAccessIntent;
  init(): _NSFileAccessIntent;
  // Class methods
  static readingIntentWithURL$options$(url: _NSURL, options: number): _NSFileAccessIntent;
  static writingIntentWithURL$options$(url: _NSURL, options: number): _NSFileAccessIntent;

  // Properties
  URL(): _NSURL;
}
