// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSScriptCommand } from "./NSScriptCommand.js";

export declare class _NSGetCommand extends _NSScriptCommand {
  static alloc(): _NSGetCommand;
  static new(): _NSGetCommand;
  init(): _NSGetCommand;
}
