// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSMethodSignature } from "./NSMethodSignature.js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSInvocation extends _NSObject {
  static alloc(): _NSInvocation;
  static new(): _NSInvocation;
  init(): _NSInvocation;
  // Class methods
  static invocationWithMethodSignature$(sig: _NSMethodSignature): _NSInvocation;

  // Instance methods
  retainArguments(): void;
  getReturnValue$(retLoc: NobjcObject): void;
  setReturnValue$(retLoc: NobjcObject): void;
  getArgument$atIndex$(argumentLocation: NobjcObject, idx: number): void;
  setArgument$atIndex$(argumentLocation: NobjcObject, idx: number): void;
  invoke(): void;
  invokeWithTarget$(target: NobjcObject): void;
  invokeUsingIMP$(imp: NobjcObject): void;

  // Properties
  methodSignature(): _NSMethodSignature;
  argumentsRetained(): boolean;
  target(): NobjcObject;
  setTarget$(value: NobjcObject): void;
  selector(): string;
  setSelector$(value: string): void;
}
