// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSInflectionRule extends _NSObject {
  static alloc(): _NSInflectionRule;
  static new(): _NSInflectionRule;
  init(): _NSInflectionRule;
  // Class methods
  static canInflectLanguage$(language: _NSString): boolean;
  static automaticRule(): _NSInflectionRule;
  static canInflectPreferredLocalization(): boolean;
}
