// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSScriptClassDescription } from "./NSScriptClassDescription.js";
import type { _NSScriptObjectSpecifier } from "./NSScriptObjectSpecifier.js";
import type { _NSString } from "./NSString.js";

export declare class _NSIndexSpecifier extends _NSScriptObjectSpecifier {
  static alloc(): _NSIndexSpecifier;
  static new(): _NSIndexSpecifier;
  init(): _NSIndexSpecifier;
  // Instance methods
  initWithContainerClassDescription$containerSpecifier$key$index$(classDesc: _NSScriptClassDescription, container: _NSScriptObjectSpecifier | null, property: _NSString, index: number): _NSIndexSpecifier;

  // Properties
  index(): number;
  setIndex$(value: number): void;
}
