// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { NSRange } from "../structs.js";

export declare class _NSIndexSet extends _NSObject {
  static alloc(): _NSIndexSet;
  static new(): _NSIndexSet;
  init(): _NSIndexSet;
  // Class methods
  static indexSet(): _NSIndexSet;
  static indexSetWithIndex$(value: number): _NSIndexSet;
  static indexSetWithIndexesInRange$(range: NSRange): _NSIndexSet;

  // Instance methods
  initWithIndexesInRange$(range: NSRange): _NSIndexSet;
  initWithIndexSet$(indexSet: _NSIndexSet): _NSIndexSet;
  initWithIndex$(value: number): _NSIndexSet;
  isEqualToIndexSet$(indexSet: _NSIndexSet): boolean;
  indexGreaterThanIndex$(value: number): number;
  indexLessThanIndex$(value: number): number;
  indexGreaterThanOrEqualToIndex$(value: number): number;
  indexLessThanOrEqualToIndex$(value: number): number;
  getIndexes$maxCount$inIndexRange$(indexBuffer: NobjcObject, bufferSize: number, range: NobjcObject): number;
  countOfIndexesInRange$(range: NSRange): number;
  containsIndex$(value: number): boolean;
  containsIndexesInRange$(range: NSRange): boolean;
  containsIndexes$(indexSet: _NSIndexSet): boolean;
  intersectsIndexesInRange$(range: NSRange): boolean;
  enumerateIndexesUsingBlock$(block: (...args: any[]) => any): void;
  enumerateIndexesWithOptions$usingBlock$(opts: number, block: (...args: any[]) => any): void;
  enumerateIndexesInRange$options$usingBlock$(range: NSRange, opts: number, block: (...args: any[]) => any): void;
  indexPassingTest$(predicate: (...args: any[]) => any): number;
  indexWithOptions$passingTest$(opts: number, predicate: (...args: any[]) => any): number;
  indexInRange$options$passingTest$(range: NSRange, opts: number, predicate: (...args: any[]) => any): number;
  indexesPassingTest$(predicate: (...args: any[]) => any): _NSIndexSet;
  indexesWithOptions$passingTest$(opts: number, predicate: (...args: any[]) => any): _NSIndexSet;
  indexesInRange$options$passingTest$(range: NSRange, opts: number, predicate: (...args: any[]) => any): _NSIndexSet;
  enumerateRangesUsingBlock$(block: (...args: any[]) => any): void;
  enumerateRangesWithOptions$usingBlock$(opts: number, block: (...args: any[]) => any): void;
  enumerateRangesInRange$options$usingBlock$(range: NSRange, opts: number, block: (...args: any[]) => any): void;

  // Properties
  count(): number;
  firstIndex(): number;
  lastIndex(): number;
}
