// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { NSRange } from "../structs.js";

export declare class _NSIndexPath extends _NSObject {
  static alloc(): _NSIndexPath;
  static new(): _NSIndexPath;
  init(): _NSIndexPath;
  // Class methods
  static indexPathWithIndex$(index: number): _NSIndexPath;
  static indexPathWithIndexes$length$(indexes: NobjcObject, length: number): _NSIndexPath;

  // Instance methods
  initWithIndexes$length$(indexes: NobjcObject, length: number): _NSIndexPath;
  initWithIndex$(index: number): _NSIndexPath;
  indexPathByAddingIndex$(index: number): _NSIndexPath;
  indexPathByRemovingLastIndex(): _NSIndexPath;
  indexAtPosition$(position: number): number;
  getIndexes$range$(indexes: NobjcObject, positionRange: NSRange): void;
  compare$(otherObject: _NSIndexPath): number;
  getIndexes$(indexes: NobjcObject): void;

  // Properties
  length(): number;
}
