// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSProgress } from "./NSProgress.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSItemProvider extends _NSObject {
  static alloc(): _NSItemProvider;
  static new(): _NSItemProvider;
  // Instance methods
  init(): _NSItemProvider;
  registerDataRepresentationForTypeIdentifier$visibility$loadHandler$(typeIdentifier: _NSString, visibility: number, loadHandler: (...args: any[]) => any | null): void;
  registerFileRepresentationForTypeIdentifier$fileOptions$visibility$loadHandler$(typeIdentifier: _NSString, fileOptions: number, visibility: number, loadHandler: (...args: any[]) => any | null): void;
  registeredTypeIdentifiersWithFileOptions$(fileOptions: number): _NSArray;
  hasItemConformingToTypeIdentifier$(typeIdentifier: _NSString): boolean;
  hasRepresentationConformingToTypeIdentifier$fileOptions$(typeIdentifier: _NSString, fileOptions: number): boolean;
  loadDataRepresentationForTypeIdentifier$completionHandler$(typeIdentifier: _NSString, completionHandler: (...args: any[]) => any | null): _NSProgress;
  loadFileRepresentationForTypeIdentifier$completionHandler$(typeIdentifier: _NSString, completionHandler: (...args: any[]) => any | null): _NSProgress;
  loadInPlaceFileRepresentationForTypeIdentifier$completionHandler$(typeIdentifier: _NSString, completionHandler: (...args: any[]) => any | null): _NSProgress;
  initWithObject$(object_: NobjcObject): _NSItemProvider;
  registerObject$visibility$(object_: NobjcObject, visibility: number): void;
  registerObjectOfClass$visibility$loadHandler$(aClass: NobjcObject, visibility: number, loadHandler: (...args: any[]) => any | null): void;
  canLoadObjectOfClass$(aClass: NobjcObject): boolean;
  loadObjectOfClass$completionHandler$(aClass: NobjcObject, completionHandler: (...args: any[]) => any | null): _NSProgress;
  initWithItem$typeIdentifier$(item: NobjcObject, typeIdentifier: _NSString | null): _NSItemProvider;
  initWithContentsOfURL$(fileURL: _NSURL): _NSItemProvider | null;
  registerItemForTypeIdentifier$loadHandler$(typeIdentifier: _NSString, loadHandler: number): void;
  loadItemForTypeIdentifier$options$completionHandler$(typeIdentifier: _NSString, options: _NSDictionary | null, completionHandler: number | null): void;
  loadPreviewImageWithOptions$completionHandler$(options: _NSDictionary, completionHandler: number): void;

  // Properties
  registeredTypeIdentifiers(): _NSArray;
  suggestedName(): _NSString | null;
  setSuggestedName$(value: _NSString | null): void;
  previewImageHandler(): number | null;
  setPreviewImageHandler$(value: number | null): void;
}
