// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSData } from "./NSData.js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSJSONSerialization extends _NSObject {
  static alloc(): _NSJSONSerialization;
  static new(): _NSJSONSerialization;
  init(): _NSJSONSerialization;
  // Class methods
  static isValidJSONObject$(obj: NobjcObject): boolean;
  static dataWithJSONObject$options$error$(obj: NobjcObject, opt: number, error: NobjcObject): _NSData | null;
  static JSONObjectWithData$options$error$(data: _NSData, opt: number, error: NobjcObject): NobjcObject;
  static writeJSONObject$toStream$options$error$(obj: NobjcObject, stream: NobjcObject, opt: number, error: NobjcObject): number;
  static JSONObjectWithStream$options$error$(stream: NobjcObject, opt: number, error: NobjcObject): NobjcObject;
}
