// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSKeyedUnarchiver } from "./NSKeyedUnarchiver.js";
import type { _NSString } from "./NSString.js";

export interface _NSKeyedUnarchiverDelegate {
  // Instance methods
  unarchiver$cannotDecodeObjectOfClassName$originalClasses$?(unarchiver: _NSKeyedUnarchiver, name: _NSString, classNames: _NSArray): NobjcObject;
  unarchiver$didDecodeObject$?(unarchiver: _NSKeyedUnarchiver, object_: NobjcObject): NobjcObject;
  unarchiver$willReplaceObject$withObject$?(unarchiver: _NSKeyedUnarchiver, object_: NobjcObject, newObject: NobjcObject): void;
  unarchiverWillFinish$?(unarchiver: _NSKeyedUnarchiver): void;
  unarchiverDidFinish$?(unarchiver: _NSKeyedUnarchiver): void;
}
