// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSLocalizedNumberFormatRule extends _NSObject {
  static alloc(): _NSLocalizedNumberFormatRule;
  static new(): _NSLocalizedNumberFormatRule;
  init(): _NSLocalizedNumberFormatRule;
  // Class methods
  static automatic(): _NSLocalizedNumberFormatRule;
}
