// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSPort } from "./NSPort.js";
import type { _NSPortNameServer } from "./NSPortNameServer.js";
import type { _NSString } from "./NSString.js";

export declare class _NSMachBootstrapServer extends _NSPortNameServer {
  static alloc(): _NSMachBootstrapServer;
  static new(): _NSMachBootstrapServer;
  init(): _NSMachBootstrapServer;
  // Class methods
  static sharedInstance(): NobjcObject;

  // Instance methods
  portForName$(name: _NSString): _NSPort | null;
  portForName$host$(name: _NSString, host: _NSString | null): _NSPort | null;
  registerPort$name$(port: _NSPort, name: _NSString): boolean;
  servicePortWithName$(name: _NSString): _NSPort | null;
}
