// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSPortDelegate } from "./NSPortDelegate.js";

export interface _NSMachPortDelegate extends _NSPortDelegate {
  // Instance methods
  handleMachMessage$?(msg: NobjcObject): void;
}
