// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSPort } from "./NSPort.js";
import type { _NSPortNameServer } from "./NSPortNameServer.js";
import type { _NSString } from "./NSString.js";

export declare class _NSMessagePortNameServer extends _NSPortNameServer {
  static alloc(): _NSMessagePortNameServer;
  static new(): _NSMessagePortNameServer;
  init(): _NSMessagePortNameServer;
  // Class methods
  static sharedInstance(): NobjcObject;

  // Instance methods
  portForName$(name: _NSString): _NSPort | null;
  portForName$host$(name: _NSString, host: _NSString | null): _NSPort | null;
}
