// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSMetadataQueryResultGroup extends _NSObject {
  static alloc(): _NSMetadataQueryResultGroup;
  static new(): _NSMetadataQueryResultGroup;
  init(): _NSMetadataQueryResultGroup;
  // Instance methods
  resultAtIndex$(idx: number): NobjcObject;

  // Properties
  attribute(): _NSString;
  value(): NobjcObject;
  subgroups(): _NSArray | null;
  resultCount(): number;
  results(): _NSArray;
}
