// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSMethodSignature extends _NSObject {
  static alloc(): _NSMethodSignature;
  static new(): _NSMethodSignature;
  init(): _NSMethodSignature;
  // Class methods
  static signatureWithObjCTypes$(types: string): _NSMethodSignature | null;

  // Instance methods
  getArgumentTypeAtIndex$(idx: number): string;
  isOneway(): boolean;

  // Properties
  numberOfArguments(): number;
  frameLength(): number;
  methodReturnType(): NobjcObject;
  methodReturnLength(): number;
}
