// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSMetadataQueryAttributeValueTuple extends _NSObject {
  static alloc(): _NSMetadataQueryAttributeValueTuple;
  static new(): _NSMetadataQueryAttributeValueTuple;
  init(): _NSMetadataQueryAttributeValueTuple;
  // Properties
  attribute(): _NSString;
  value(): NobjcObject;
  count(): number;
}
