// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSOperationQueue } from "./NSOperationQueue.js";
import type { _NSPredicate } from "./NSPredicate.js";
import type { _NSString } from "./NSString.js";

export declare class _NSMetadataQuery extends _NSObject {
  static alloc(): _NSMetadataQuery;
  static new(): _NSMetadataQuery;
  init(): _NSMetadataQuery;
  // Instance methods
  startQuery(): boolean;
  stopQuery(): void;
  disableUpdates(): void;
  enableUpdates(): void;
  resultAtIndex$(idx: number): NobjcObject;
  enumerateResultsUsingBlock$(block: (...args: any[]) => any): void;
  enumerateResultsWithOptions$usingBlock$(opts: number, block: (...args: any[]) => any): void;
  indexOfResult$(result: NobjcObject): number;
  valueOfAttribute$forResultAtIndex$(attrName: _NSString, idx: number): NobjcObject;

  // Properties
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  predicate(): _NSPredicate | null;
  setPredicate$(value: _NSPredicate | null): void;
  sortDescriptors(): _NSArray;
  setSortDescriptors$(value: _NSArray): void;
  valueListAttributes(): _NSArray;
  setValueListAttributes$(value: _NSArray): void;
  groupingAttributes(): _NSArray | null;
  setGroupingAttributes$(value: _NSArray | null): void;
  notificationBatchingInterval(): number;
  setNotificationBatchingInterval$(value: number): void;
  searchScopes(): _NSArray;
  setSearchScopes$(value: _NSArray): void;
  searchItems(): _NSArray | null;
  setSearchItems$(value: _NSArray | null): void;
  operationQueue(): _NSOperationQueue | null;
  setOperationQueue$(value: _NSOperationQueue | null): void;
  started(): boolean;
  gathering(): boolean;
  stopped(): boolean;
  resultCount(): number;
  results(): _NSArray;
  valueLists(): NobjcObject;
  groupedResults(): _NSArray;
}
