// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSScriptObjectSpecifier } from "./NSScriptObjectSpecifier.js";

export declare class _NSMiddleSpecifier extends _NSScriptObjectSpecifier {
  static alloc(): _NSMiddleSpecifier;
  static new(): _NSMiddleSpecifier;
  init(): _NSMiddleSpecifier;
}
