// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSMorphology } from "./NSMorphology.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSMorphologyPronoun extends _NSObject {
  static alloc(): _NSMorphologyPronoun;
  static new(): _NSMorphologyPronoun;
  init(): _NSMorphologyPronoun;
  // Instance methods
  initWithPronoun$morphology$dependentMorphology$(pronoun: _NSString, morphology: _NSMorphology, dependentMorphology: _NSMorphology | null): _NSMorphologyPronoun;

  // Properties
  pronoun(): _NSString;
  morphology(): _NSMorphology;
  dependentMorphology(): _NSMorphology | null;
}
