// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSScriptCommand } from "./NSScriptCommand.js";
import type { _NSScriptObjectSpecifier } from "./NSScriptObjectSpecifier.js";

export declare class _NSMoveCommand extends _NSScriptCommand {
  static alloc(): _NSMoveCommand;
  static new(): _NSMoveCommand;
  init(): _NSMoveCommand;
  // Instance methods
  setReceiversSpecifier$(receiversRef: _NSScriptObjectSpecifier | null): void;

  // Properties
  keySpecifier(): _NSScriptObjectSpecifier;
}
