// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCharacterSet } from "./NSCharacterSet.js";
import type { _NSData } from "./NSData.js";
import type { _NSString } from "./NSString.js";
import type { NSRange } from "../structs.js";

export declare class _NSMutableCharacterSet extends _NSCharacterSet {
  static alloc(): _NSMutableCharacterSet;
  static new(): _NSMutableCharacterSet;
  init(): _NSMutableCharacterSet;
  // Class methods
  static controlCharacterSet(): _NSMutableCharacterSet;
  static whitespaceCharacterSet(): _NSMutableCharacterSet;
  static whitespaceAndNewlineCharacterSet(): _NSMutableCharacterSet;
  static decimalDigitCharacterSet(): _NSMutableCharacterSet;
  static letterCharacterSet(): _NSMutableCharacterSet;
  static lowercaseLetterCharacterSet(): _NSMutableCharacterSet;
  static uppercaseLetterCharacterSet(): _NSMutableCharacterSet;
  static nonBaseCharacterSet(): _NSMutableCharacterSet;
  static alphanumericCharacterSet(): _NSMutableCharacterSet;
  static decomposableCharacterSet(): _NSMutableCharacterSet;
  static illegalCharacterSet(): _NSMutableCharacterSet;
  static punctuationCharacterSet(): _NSMutableCharacterSet;
  static capitalizedLetterCharacterSet(): _NSMutableCharacterSet;
  static symbolCharacterSet(): _NSMutableCharacterSet;
  static newlineCharacterSet(): _NSMutableCharacterSet;
  static characterSetWithRange$(aRange: NSRange): _NSMutableCharacterSet;
  static characterSetWithCharactersInString$(aString: _NSString): _NSMutableCharacterSet;
  static characterSetWithBitmapRepresentation$(data: _NSData): _NSMutableCharacterSet;
  static characterSetWithContentsOfFile$(fName: _NSString): _NSMutableCharacterSet | null;

  // Instance methods
  addCharactersInRange$(aRange: NSRange): void;
  removeCharactersInRange$(aRange: NSRange): void;
  addCharactersInString$(aString: _NSString): void;
  removeCharactersInString$(aString: _NSString): void;
  formUnionWithCharacterSet$(otherSet: _NSCharacterSet): void;
  formIntersectionWithCharacterSet$(otherSet: _NSCharacterSet): void;
  invert(): void;
}
