// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSString } from "./NSString.js";
import type { NSRange } from "../structs.js";

export declare class _NSMutableString extends _NSString {
  static alloc(): _NSMutableString;
  static new(): _NSMutableString;
  init(): _NSMutableString;
  // Class methods
  static stringWithCapacity$(capacity: number): _NSMutableString;

  // Instance methods
  replaceCharactersInRange$withString$(range: NSRange, aString: _NSString): void;
  insertString$atIndex$(aString: _NSString, loc: number): void;
  deleteCharactersInRange$(range: NSRange): void;
  appendString$(aString: _NSString): void;
  appendFormat$(format: _NSString): void;
  setString$(aString: _NSString): void;
  replaceOccurrencesOfString$withString$options$range$(target: _NSString, replacement: _NSString, options: number, searchRange: NSRange): number;
  applyTransform$reverse$range$updatedRange$(transform: number, reverse: boolean, range: NSRange, resultingRange: number | null): boolean;
  initWithCapacity$(capacity: number): _NSMutableString;
}
