// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAttributedString } from "./NSAttributedString.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSMutableString } from "./NSMutableString.js";
import type { _NSString } from "./NSString.js";
import type { NSRange } from "../structs.js";

export declare class _NSMutableAttributedString extends _NSAttributedString {
  static alloc(): _NSMutableAttributedString;
  static new(): _NSMutableAttributedString;
  init(): _NSMutableAttributedString;
  // Instance methods
  replaceCharactersInRange$withString$(range: NSRange, str: _NSString): void;
  setAttributes$range$(attrs: _NSDictionary | null, range: NSRange): void;
  addAttribute$value$range$(name: _NSString, value: NobjcObject, range: NSRange): void;
  addAttributes$range$(attrs: _NSDictionary, range: NSRange): void;
  removeAttribute$range$(name: _NSString, range: NSRange): void;
  replaceCharactersInRange$withAttributedString$(range: NSRange, attrString: _NSAttributedString): void;
  insertAttributedString$atIndex$(attrString: _NSAttributedString, loc: number): void;
  appendAttributedString$(attrString: _NSAttributedString): void;
  deleteCharactersInRange$(range: NSRange): void;
  setAttributedString$(attrString: _NSAttributedString): void;
  beginEditing(): void;
  endEditing(): void;
  appendLocalizedFormat$(format: _NSAttributedString): void;

  // Properties
  mutableString(): _NSMutableString;
}
