// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSNetService } from "./NSNetService.js";
import type { _NSNetServiceBrowser } from "./NSNetServiceBrowser.js";
import type { _NSString } from "./NSString.js";

export interface _NSNetServiceBrowserDelegate {
  // Instance methods
  netServiceBrowserWillSearch$?(browser: _NSNetServiceBrowser): void;
  netServiceBrowserDidStopSearch$?(browser: _NSNetServiceBrowser): void;
  netServiceBrowser$didNotSearch$?(browser: _NSNetServiceBrowser, errorDict: _NSDictionary): void;
  netServiceBrowser$didFindDomain$moreComing$?(browser: _NSNetServiceBrowser, domainString: _NSString, moreComing: boolean): void;
  netServiceBrowser$didFindService$moreComing$?(browser: _NSNetServiceBrowser, service: _NSNetService, moreComing: boolean): void;
  netServiceBrowser$didRemoveDomain$moreComing$?(browser: _NSNetServiceBrowser, domainString: _NSString, moreComing: boolean): void;
  netServiceBrowser$didRemoveService$moreComing$?(browser: _NSNetServiceBrowser, service: _NSNetService, moreComing: boolean): void;
}
