// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSNull extends _NSObject {
  static alloc(): _NSNull;
  static new(): _NSNull;
  init(): _NSNull;
  // Class methods
  static null(): _NSNull;
}
