// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAttributedString } from "./NSAttributedString.js";
import type { _NSFormatter } from "./NSFormatter.js";
import type { _NSLocale } from "./NSLocale.js";
import type { _NSPersonNameComponents } from "./NSPersonNameComponents.js";
import type { _NSString } from "./NSString.js";

export declare class _NSPersonNameComponentsFormatter extends _NSFormatter {
  static alloc(): _NSPersonNameComponentsFormatter;
  static new(): _NSPersonNameComponentsFormatter;
  init(): _NSPersonNameComponentsFormatter;
  // Class methods
  static localizedStringFromPersonNameComponents$style$options$(components: _NSPersonNameComponents, nameFormatStyle: number, nameOptions: number): _NSString;

  // Instance methods
  stringFromPersonNameComponents$(components: _NSPersonNameComponents): _NSString;
  annotatedStringFromPersonNameComponents$(components: _NSPersonNameComponents): _NSAttributedString;
  personNameComponentsFromString$(string_: _NSString): _NSPersonNameComponents | null;
  getObjectValue$forString$errorDescription$(obj: NobjcObject, string_: _NSString, error: NobjcObject): boolean;

  // Properties
  style(): number;
  setStyle$(value: number): void;
  phonetic(): boolean;
  setPhonetic$(value: boolean): void;
  locale(): _NSLocale;
  setLocale$(value: _NSLocale): void;
}
