// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSPersonNameComponents extends _NSObject {
  static alloc(): _NSPersonNameComponents;
  static new(): _NSPersonNameComponents;
  init(): _NSPersonNameComponents;
  // Properties
  namePrefix(): _NSString | null;
  setNamePrefix$(value: _NSString | null): void;
  givenName(): _NSString | null;
  setGivenName$(value: _NSString | null): void;
  middleName(): _NSString | null;
  setMiddleName$(value: _NSString | null): void;
  familyName(): _NSString | null;
  setFamilyName$(value: _NSString | null): void;
  nameSuffix(): _NSString | null;
  setNameSuffix$(value: _NSString | null): void;
  nickname(): _NSString | null;
  setNickname$(value: _NSString | null): void;
  phoneticRepresentation(): _NSPersonNameComponents | null;
  setPhoneticRepresentation$(value: _NSPersonNameComponents | null): void;
}
