// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSPointerFunctions extends _NSObject {
  static alloc(): _NSPointerFunctions;
  static new(): _NSPointerFunctions;
  init(): _NSPointerFunctions;
  // Class methods
  static pointerFunctionsWithOptions$(options: number): _NSPointerFunctions;

  // Instance methods
  initWithOptions$(options: number): _NSPointerFunctions;

  // Properties
  hashFunction(): (...args: any[]) => any | null;
  setHashFunction$(value: (...args: any[]) => any | null): void;
  isEqualFunction(): (...args: any[]) => any | null;
  setIsEqualFunction$(value: (...args: any[]) => any | null): void;
  sizeFunction(): (...args: any[]) => any | null;
  setSizeFunction$(value: (...args: any[]) => any | null): void;
  descriptionFunction(): (...args: any[]) => any | null;
  setDescriptionFunction$(value: (...args: any[]) => any | null): void;
  relinquishFunction(): (...args: any[]) => any | null;
  setRelinquishFunction$(value: (...args: any[]) => any | null): void;
  acquireFunction(): (...args: any[]) => any | null;
  setAcquireFunction$(value: (...args: any[]) => any | null): void;
  usesStrongWriteBarrier(): boolean;
  setUsesStrongWriteBarrier$(value: boolean): void;
  usesWeakReadAndWriteBarriers(): boolean;
  setUsesWeakReadAndWriteBarriers$(value: boolean): void;
}
