// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSPort } from "./NSPort.js";
import type { _NSString } from "./NSString.js";

export declare class _NSPortNameServer extends _NSObject {
  static alloc(): _NSPortNameServer;
  static new(): _NSPortNameServer;
  init(): _NSPortNameServer;
  // Class methods
  static systemDefaultPortNameServer(): _NSPortNameServer;

  // Instance methods
  portForName$(name: _NSString): _NSPort | null;
  portForName$host$(name: _NSString, host: _NSString | null): _NSPort | null;
  registerPort$name$(port: _NSPort, name: _NSString): boolean;
  removePortForName$(name: _NSString): boolean;
}
