// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSPresentationIntent extends _NSObject {
  static alloc(): _NSPresentationIntent;
  static new(): _NSPresentationIntent;
  init(): _NSPresentationIntent;
  // Class methods
  static paragraphIntentWithIdentity$nestedInsideIntent$(identity: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static headerIntentWithIdentity$level$nestedInsideIntent$(identity: number, level: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static codeBlockIntentWithIdentity$languageHint$nestedInsideIntent$(identity: number, languageHint: _NSString | null, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static thematicBreakIntentWithIdentity$nestedInsideIntent$(identity: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static orderedListIntentWithIdentity$nestedInsideIntent$(identity: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static unorderedListIntentWithIdentity$nestedInsideIntent$(identity: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static listItemIntentWithIdentity$ordinal$nestedInsideIntent$(identity: number, ordinal: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static blockQuoteIntentWithIdentity$nestedInsideIntent$(identity: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static tableIntentWithIdentity$columnCount$alignments$nestedInsideIntent$(identity: number, columnCount: number, alignments: _NSArray, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static tableHeaderRowIntentWithIdentity$nestedInsideIntent$(identity: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static tableRowIntentWithIdentity$row$nestedInsideIntent$(identity: number, row: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;
  static tableCellIntentWithIdentity$column$nestedInsideIntent$(identity: number, column: number, parent: _NSPresentationIntent | null): _NSPresentationIntent;

  // Instance methods
  isEquivalentToPresentationIntent$(other: _NSPresentationIntent): boolean;

  // Properties
  intentKind(): number;
  parentIntent(): _NSPresentationIntent | null;
  identity(): number;
  ordinal(): number;
  columnAlignments(): _NSArray | null;
  columnCount(): number;
  headerLevel(): number;
  languageHint(): _NSString | null;
  column(): number;
  row(): number;
  indentationLevel(): number;
}
