// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSScriptObjectSpecifier } from "./NSScriptObjectSpecifier.js";

export declare class _NSPropertySpecifier extends _NSScriptObjectSpecifier {
  static alloc(): _NSPropertySpecifier;
  static new(): _NSPropertySpecifier;
  init(): _NSPropertySpecifier;
}
