// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSClassDescription } from "./NSClassDescription.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSScriptCommandDescription } from "./NSScriptCommandDescription.js";
import type { _NSString } from "./NSString.js";

export declare class _NSScriptClassDescription extends _NSClassDescription {
  static alloc(): _NSScriptClassDescription;
  static new(): _NSScriptClassDescription;
  init(): _NSScriptClassDescription;
  // Class methods
  static classDescriptionForClass$(aClass: NobjcObject): _NSScriptClassDescription | null;

  // Instance methods
  initWithSuiteName$className$dictionary$(suiteName: _NSString, className: _NSString, classDeclaration: _NSDictionary | null): _NSScriptClassDescription | null;
  matchesAppleEventCode$(appleEventCode: NobjcObject): boolean;
  supportsCommand$(commandDescription: _NSScriptCommandDescription): boolean;
  selectorForCommand$(commandDescription: _NSScriptCommandDescription): string | null;
  typeForKey$(key: _NSString): _NSString | null;
  classDescriptionForKey$(key: _NSString): _NSScriptClassDescription | null;
  appleEventCodeForKey$(key: _NSString): NobjcObject;
  keyWithAppleEventCode$(appleEventCode: NobjcObject): _NSString | null;
  isLocationRequiredToCreateForKey$(toManyRelationshipKey: _NSString): boolean;
  hasPropertyForKey$(key: _NSString): boolean;
  hasOrderedToManyRelationshipForKey$(key: _NSString): boolean;
  hasReadablePropertyForKey$(key: _NSString): boolean;
  hasWritablePropertyForKey$(key: _NSString): boolean;
  isReadOnlyKey$(key: _NSString): boolean;

  // Properties
  suiteName(): _NSString | null;
  className(): _NSString | null;
  implementationClassName(): _NSString | null;
  superclassDescription(): _NSScriptClassDescription | null;
  appleEventCode(): NobjcObject;
  defaultSubcontainerAttributeKey(): _NSString | null;
}
