// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCharacterSet } from "./NSCharacterSet.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSScanner extends _NSObject {
  static alloc(): _NSScanner;
  static new(): _NSScanner;
  init(): _NSScanner;
  // Class methods
  static scannerWithString$(string_: _NSString): _NSScanner;
  static localizedScannerWithString$(string_: _NSString): NobjcObject;

  // Instance methods
  initWithString$(string_: _NSString): _NSScanner;
  scanInt$(result: NobjcObject): boolean;
  scanInteger$(result: NobjcObject): boolean;
  scanLongLong$(result: NobjcObject): boolean;
  scanUnsignedLongLong$(result: NobjcObject): boolean;
  scanFloat$(result: NobjcObject): boolean;
  scanDouble$(result: NobjcObject): boolean;
  scanHexInt$(result: NobjcObject): boolean;
  scanHexLongLong$(result: NobjcObject): boolean;
  scanHexFloat$(result: NobjcObject): boolean;
  scanHexDouble$(result: NobjcObject): boolean;
  scanString$intoString$(string_: _NSString, result: NobjcObject): boolean;
  scanCharactersFromSet$intoString$(set: _NSCharacterSet, result: NobjcObject): boolean;
  scanUpToString$intoString$(string_: _NSString, result: NobjcObject): boolean;
  scanUpToCharactersFromSet$intoString$(set: _NSCharacterSet, result: NobjcObject): boolean;

  // Properties
  string(): _NSString;
  scanLocation(): number;
  setScanLocation$(value: number): void;
  charactersToBeSkipped(): _NSCharacterSet | null;
  setCharactersToBeSkipped$(value: _NSCharacterSet | null): void;
  caseSensitive(): boolean;
  setCaseSensitive$(value: boolean): void;
  locale(): NobjcObject;
  setLocale$(value: NobjcObject): void;
  atEnd(): boolean;
}
