// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "./NSCoder.js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSScriptWhoseTest extends _NSObject {
  static alloc(): _NSScriptWhoseTest;
  static new(): _NSScriptWhoseTest;
  // Instance methods
  isTrue(): boolean;
  init(): _NSScriptWhoseTest;
  initWithCoder$(inCoder: _NSCoder): _NSScriptWhoseTest | null;
}
