// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoding } from "./NSCoding.js";

export interface _NSSecureCoding extends _NSCoding {
}
