// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSCoder } from "./NSCoder.js";
import type { _NSEnumerator } from "./NSEnumerator.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSSet extends _NSObject {
  static alloc(): _NSSet;
  static new(): _NSSet;
  // Class methods
  static set(): _NSSet;
  static setWithObject$(object_: NobjcObject): _NSSet;
  static setWithObjects$count$(objects: NobjcObject, cnt: number): _NSSet;
  static setWithObjects$(firstObj: NobjcObject): _NSSet;
  static setWithSet$(set: _NSSet): _NSSet;
  static setWithArray$(array: _NSArray): _NSSet;

  // Instance methods
  member$(object_: NobjcObject): NobjcObject;
  objectEnumerator(): _NSEnumerator;
  init(): _NSSet;
  initWithObjects$count$(objects: NobjcObject, cnt: number): _NSSet;
  initWithCoder$(coder: _NSCoder): _NSSet | null;
  anyObject(): NobjcObject;
  containsObject$(anObject: NobjcObject): boolean;
  descriptionWithLocale$(locale: NobjcObject): _NSString;
  intersectsSet$(otherSet: _NSSet): boolean;
  isEqualToSet$(otherSet: _NSSet): boolean;
  isSubsetOfSet$(otherSet: _NSSet): boolean;
  makeObjectsPerformSelector$(aSelector: string): void;
  makeObjectsPerformSelector$withObject$(aSelector: string, argument: NobjcObject): void;
  setByAddingObject$(anObject: NobjcObject): _NSSet;
  setByAddingObjectsFromSet$(other: _NSSet): _NSSet;
  setByAddingObjectsFromArray$(other: _NSArray): _NSSet;
  enumerateObjectsUsingBlock$(block: (...args: any[]) => any): void;
  enumerateObjectsWithOptions$usingBlock$(opts: number, block: (...args: any[]) => any): void;
  objectsPassingTest$(predicate: (...args: any[]) => any): _NSSet;
  objectsWithOptions$passingTest$(opts: number, predicate: (...args: any[]) => any): _NSSet;
  initWithObjects$(firstObj: NobjcObject): _NSSet;
  initWithSet$(set: _NSSet): _NSSet;
  initWithSet$copyItems$(set: _NSSet, flag: boolean): _NSSet;
  initWithArray$(array: _NSArray): _NSSet;

  // Properties
  count(): number;
  allObjects(): _NSArray;
  description(): _NSString;
}
