// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSSpellServer extends _NSObject {
  static alloc(): _NSSpellServer;
  static new(): _NSSpellServer;
  init(): _NSSpellServer;
  // Instance methods
  registerLanguage$byVendor$(language: _NSString | null, vendor: _NSString | null): boolean;
  isWordInUserDictionaries$caseSensitive$(word: _NSString, flag: boolean): boolean;
  run(): void;

  // Properties
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
}
