// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSTask extends _NSObject {
  static alloc(): _NSTask;
  static new(): _NSTask;
  // Class methods
  static launchedTaskWithExecutableURL$arguments$error$terminationHandler$(url: _NSURL, arguments: _NSArray, error: NobjcObject, terminationHandler: (...args: any[]) => any | null): _NSTask | null;
  static launchedTaskWithLaunchPath$arguments$(path: _NSString, arguments: _NSArray): _NSTask;

  // Instance methods
  init(): _NSTask;
  launchAndReturnError$(error: NobjcObject): boolean;
  interrupt(): void;
  terminate(): void;
  suspend(): boolean;
  resume(): boolean;
  waitUntilExit(): void;
  launch(): void;

  // Properties
  executableURL(): NobjcObject;
  setExecutableURL$(value: NobjcObject): void;
  arguments(): _NSArray | null;
  setArguments$(value: _NSArray | null): void;
  environment(): _NSDictionary | null;
  setEnvironment$(value: _NSDictionary | null): void;
  currentDirectoryURL(): NobjcObject;
  setCurrentDirectoryURL$(value: NobjcObject): void;
  launchRequirementData(): NobjcObject;
  setLaunchRequirementData$(value: NobjcObject): void;
  standardInput(): NobjcObject;
  setStandardInput$(value: NobjcObject): void;
  standardOutput(): NobjcObject;
  setStandardOutput$(value: NobjcObject): void;
  standardError(): NobjcObject;
  setStandardError$(value: NobjcObject): void;
  processIdentifier(): number;
  running(): boolean;
  terminationStatus(): number;
  terminationReason(): number;
  terminationHandler(): (...args: any[]) => any;
  setTerminationHandler$(value: (...args: any[]) => any): void;
  qualityOfService(): number;
  setQualityOfService$(value: number): void;
  launchPath(): NobjcObject;
  setLaunchPath$(value: NobjcObject): void;
  currentDirectoryPath(): NobjcObject;
  setCurrentDirectoryPath$(value: NobjcObject): void;
}
