// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSDate } from "./NSDate.js";
import type { _NSMutableDictionary } from "./NSMutableDictionary.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSThread extends _NSObject {
  static alloc(): _NSThread;
  static new(): _NSThread;
  // Class methods
  static detachNewThreadWithBlock$(block: (...args: any[]) => any): void;
  static detachNewThreadSelector$toTarget$withObject$(selector: string, target: NobjcObject, argument: NobjcObject): void;
  static isMultiThreaded(): boolean;
  static sleepUntilDate$(date: _NSDate): void;
  static sleepForTimeInterval$(ti: number): void;
  static exit(): void;
  static threadPriority(): number;
  static setThreadPriority$(p: number): boolean;
  static currentThread(): NobjcObject;
  static callStackReturnAddresses(): _NSArray;
  static callStackSymbols(): _NSArray;
  static mainThread(): _NSThread;

  // Instance methods
  init(): _NSThread;
  initWithTarget$selector$object$(target: NobjcObject, selector: string, argument: NobjcObject): _NSThread;
  initWithBlock$(block: (...args: any[]) => any): _NSThread;
  cancel(): void;
  start(): void;
  main(): void;

  // Properties
  threadDictionary(): _NSMutableDictionary;
  threadPriority(): number;
  setThreadPriority$(value: number): void;
  qualityOfService(): number;
  setQualityOfService$(value: number): void;
  name(): _NSString | null;
  setName$(value: _NSString | null): void;
  stackSize(): number;
  setStackSize$(value: number): void;
  isMainThread(): boolean;
  executing(): boolean;
  finished(): boolean;
  cancelled(): boolean;
}
