// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDate } from "./NSDate.js";
import type { _NSObject } from "./NSObject.js";

export declare class _NSTimer extends _NSObject {
  static alloc(): _NSTimer;
  static new(): _NSTimer;
  init(): _NSTimer;
  // Class methods
  static timerWithTimeInterval$invocation$repeats$(ti: number, invocation: NobjcObject, yesOrNo: boolean): _NSTimer;
  static scheduledTimerWithTimeInterval$invocation$repeats$(ti: number, invocation: NobjcObject, yesOrNo: boolean): _NSTimer;
  static timerWithTimeInterval$target$selector$userInfo$repeats$(ti: number, aTarget: NobjcObject, aSelector: string, userInfo: NobjcObject, yesOrNo: boolean): _NSTimer;
  static scheduledTimerWithTimeInterval$target$selector$userInfo$repeats$(ti: number, aTarget: NobjcObject, aSelector: string, userInfo: NobjcObject, yesOrNo: boolean): _NSTimer;
  static timerWithTimeInterval$repeats$block$(interval: number, repeats: boolean, block: (...args: any[]) => any): _NSTimer;
  static scheduledTimerWithTimeInterval$repeats$block$(interval: number, repeats: boolean, block: (...args: any[]) => any): _NSTimer;

  // Instance methods
  initWithFireDate$interval$repeats$block$(date: _NSDate, interval: number, repeats: boolean, block: (...args: any[]) => any): _NSTimer;
  initWithFireDate$interval$target$selector$userInfo$repeats$(date: _NSDate, ti: number, t: NobjcObject, s: string, ui: NobjcObject, rep: boolean): _NSTimer;
  fire(): void;
  invalidate(): void;

  // Properties
  fireDate(): _NSDate;
  setFireDate$(value: _NSDate): void;
  timeInterval(): number;
  tolerance(): number;
  setTolerance$(value: number): void;
  valid(): boolean;
  userInfo(): NobjcObject;
}
