// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSData } from "./NSData.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSUbiquitousKeyValueStore extends _NSObject {
  static alloc(): _NSUbiquitousKeyValueStore;
  static new(): _NSUbiquitousKeyValueStore;
  init(): _NSUbiquitousKeyValueStore;
  // Class methods
  static defaultStore(): _NSUbiquitousKeyValueStore;

  // Instance methods
  objectForKey$(aKey: _NSString): NobjcObject;
  setObject$forKey$(anObject: NobjcObject, aKey: _NSString): void;
  removeObjectForKey$(aKey: _NSString): void;
  stringForKey$(aKey: _NSString): _NSString | null;
  arrayForKey$(aKey: _NSString): _NSArray | null;
  dictionaryForKey$(aKey: _NSString): _NSDictionary | null;
  dataForKey$(aKey: _NSString): _NSData | null;
  longLongForKey$(aKey: _NSString): number;
  doubleForKey$(aKey: _NSString): number;
  boolForKey$(aKey: _NSString): boolean;
  setString$forKey$(aString: _NSString | null, aKey: _NSString): void;
  setData$forKey$(aData: _NSData | null, aKey: _NSString): void;
  setArray$forKey$(anArray: _NSArray | null, aKey: _NSString): void;
  setDictionary$forKey$(aDictionary: _NSDictionary | null, aKey: _NSString): void;
  setLongLong$forKey$(value: number, aKey: _NSString): void;
  setDouble$forKey$(value: number, aKey: _NSString): void;
  setBool$forKey$(value: boolean, aKey: _NSString): void;
  synchronize(): boolean;

  // Properties
  dictionaryRepresentation(): _NSDictionary;
}
