// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDimension } from "./NSDimension.js";

export declare class _NSUnitVolume extends _NSDimension {
  static alloc(): _NSUnitVolume;
  static new(): _NSUnitVolume;
  init(): _NSUnitVolume;
  // Class methods
  static megaliters(): _NSUnitVolume;
  static kiloliters(): _NSUnitVolume;
  static liters(): _NSUnitVolume;
  static deciliters(): _NSUnitVolume;
  static centiliters(): _NSUnitVolume;
  static milliliters(): _NSUnitVolume;
  static cubicKilometers(): _NSUnitVolume;
  static cubicMeters(): _NSUnitVolume;
  static cubicDecimeters(): _NSUnitVolume;
  static cubicCentimeters(): _NSUnitVolume;
  static cubicMillimeters(): _NSUnitVolume;
  static cubicInches(): _NSUnitVolume;
  static cubicFeet(): _NSUnitVolume;
  static cubicYards(): _NSUnitVolume;
  static cubicMiles(): _NSUnitVolume;
  static acreFeet(): _NSUnitVolume;
  static bushels(): _NSUnitVolume;
  static teaspoons(): _NSUnitVolume;
  static tablespoons(): _NSUnitVolume;
  static fluidOunces(): _NSUnitVolume;
  static cups(): _NSUnitVolume;
  static pints(): _NSUnitVolume;
  static quarts(): _NSUnitVolume;
  static gallons(): _NSUnitVolume;
  static imperialTeaspoons(): _NSUnitVolume;
  static imperialTablespoons(): _NSUnitVolume;
  static imperialFluidOunces(): _NSUnitVolume;
  static imperialPints(): _NSUnitVolume;
  static imperialQuarts(): _NSUnitVolume;
  static imperialGallons(): _NSUnitVolume;
  static metricCups(): _NSUnitVolume;
}
