// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDimension } from "./NSDimension.js";

export declare class _NSUnitTemperature extends _NSDimension {
  static alloc(): _NSUnitTemperature;
  static new(): _NSUnitTemperature;
  init(): _NSUnitTemperature;
  // Class methods
  static kelvin(): _NSUnitTemperature;
  static celsius(): _NSUnitTemperature;
  static fahrenheit(): _NSUnitTemperature;
}
