// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "./NSCoder.js";
import type { _NSScriptClassDescription } from "./NSScriptClassDescription.js";
import type { _NSScriptObjectSpecifier } from "./NSScriptObjectSpecifier.js";
import type { _NSString } from "./NSString.js";

export declare class _NSUniqueIDSpecifier extends _NSScriptObjectSpecifier {
  static alloc(): _NSUniqueIDSpecifier;
  static new(): _NSUniqueIDSpecifier;
  init(): _NSUniqueIDSpecifier;
  // Instance methods
  initWithCoder$(inCoder: _NSCoder): _NSUniqueIDSpecifier | null;
  initWithContainerClassDescription$containerSpecifier$key$uniqueID$(classDesc: _NSScriptClassDescription, container: _NSScriptObjectSpecifier | null, property: _NSString, uniqueID: NobjcObject): _NSUniqueIDSpecifier;

  // Properties
  uniqueID(): NobjcObject;
  setUniqueID$(value: NobjcObject): void;
}
