// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDimension } from "./NSDimension.js";

export declare class _NSUnitAngle extends _NSDimension {
  static alloc(): _NSUnitAngle;
  static new(): _NSUnitAngle;
  init(): _NSUnitAngle;
  // Class methods
  static degrees(): _NSUnitAngle;
  static arcMinutes(): _NSUnitAngle;
  static arcSeconds(): _NSUnitAngle;
  static radians(): _NSUnitAngle;
  static gradians(): _NSUnitAngle;
  static revolutions(): _NSUnitAngle;
}
