// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDimension } from "./NSDimension.js";

export declare class _NSUnitIlluminance extends _NSDimension {
  static alloc(): _NSUnitIlluminance;
  static new(): _NSUnitIlluminance;
  init(): _NSUnitIlluminance;
  // Class methods
  static lux(): _NSUnitIlluminance;
}
