// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSURLSessionTask } from "./NSURLSessionTask.js";

export declare class _NSURLSessionDownloadTask extends _NSURLSessionTask {
  static alloc(): _NSURLSessionDownloadTask;
  // Class methods
  static new(): _NSURLSessionDownloadTask;

  // Instance methods
  cancelByProducingResumeData$(completionHandler: (...args: any[]) => any | null): void;
  init(): _NSURLSessionDownloadTask;
}
