// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSData } from "./NSData.js";
import type { _NSURLSessionTask } from "./NSURLSessionTask.js";
import type { _NSURLSessionWebSocketMessage } from "./NSURLSessionWebSocketMessage.js";

export declare class _NSURLSessionWebSocketTask extends _NSURLSessionTask {
  static alloc(): _NSURLSessionWebSocketTask;
  static new(): _NSURLSessionWebSocketTask;
  init(): _NSURLSessionWebSocketTask;
  // Instance methods
  sendMessage$completionHandler$(message: _NSURLSessionWebSocketMessage, completionHandler: (...args: any[]) => any | null): void;
  receiveMessageWithCompletionHandler$(completionHandler: (...args: any[]) => any | null): void;
  sendPingWithPongReceiveHandler$(pongReceiveHandler: (...args: any[]) => any | null): void;
  cancelWithCloseCode$reason$(closeCode: number, reason: _NSData | null): void;

  // Properties
  maximumMessageSize(): number;
  setMaximumMessageSize$(value: number): void;
  closeCode(): number;
  closeReason(): _NSData | null;
}
