// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSInputStream } from "./NSInputStream.js";
import type { _NSOutputStream } from "./NSOutputStream.js";
import type { _NSURLSession } from "./NSURLSession.js";
import type { _NSURLSessionStreamTask } from "./NSURLSessionStreamTask.js";
import type { _NSURLSessionTaskDelegate } from "./NSURLSessionTaskDelegate.js";

export interface _NSURLSessionStreamDelegate extends _NSURLSessionTaskDelegate {
  // Instance methods
  URLSession$readClosedForStreamTask$?(session: _NSURLSession, streamTask: _NSURLSessionStreamTask): void;
  URLSession$writeClosedForStreamTask$?(session: _NSURLSession, streamTask: _NSURLSessionStreamTask): void;
  URLSession$betterRouteDiscoveredForStreamTask$?(session: _NSURLSession, streamTask: _NSURLSessionStreamTask): void;
  URLSession$streamTask$didBecomeInputStream$outputStream$?(session: _NSURLSession, streamTask: _NSURLSessionStreamTask, inputStream: _NSInputStream, outputStream: _NSOutputStream): void;
}
