// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSURLQueryItem extends _NSObject {
  static alloc(): _NSURLQueryItem;
  static new(): _NSURLQueryItem;
  init(): _NSURLQueryItem;
  // Class methods
  static queryItemWithName$value$(name: _NSString, value: _NSString | null): _NSURLQueryItem;

  // Instance methods
  initWithName$value$(name: _NSString, value: _NSString | null): _NSURLQueryItem;

  // Properties
  name(): _NSString;
  value(): _NSString | null;
}
