// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSData } from "./NSData.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";

export declare class _NSURLSessionWebSocketMessage extends _NSObject {
  static alloc(): _NSURLSessionWebSocketMessage;
  static new(): _NSURLSessionWebSocketMessage;
  init(): _NSURLSessionWebSocketMessage;
  // Instance methods
  initWithData$(data: _NSData): _NSURLSessionWebSocketMessage;
  initWithString$(string_: _NSString): _NSURLSessionWebSocketMessage;

  // Properties
  type(): number;
  data(): _NSData | null;
  string(): _NSString | null;
}
