// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDate } from "./NSDate.js";
import type { _NSNumber } from "./NSNumber.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";
import type { _NSURLRequest } from "./NSURLRequest.js";
import type { _NSURLResponse } from "./NSURLResponse.js";

export declare class _NSURLSessionTaskTransactionMetrics extends _NSObject {
  static alloc(): _NSURLSessionTaskTransactionMetrics;
  // Class methods
  static new(): _NSURLSessionTaskTransactionMetrics;

  // Instance methods
  init(): _NSURLSessionTaskTransactionMetrics;

  // Properties
  request(): _NSURLRequest;
  response(): _NSURLResponse | null;
  fetchStartDate(): _NSDate | null;
  domainLookupStartDate(): _NSDate | null;
  domainLookupEndDate(): _NSDate | null;
  connectStartDate(): _NSDate | null;
  secureConnectionStartDate(): _NSDate | null;
  secureConnectionEndDate(): _NSDate | null;
  connectEndDate(): _NSDate | null;
  requestStartDate(): _NSDate | null;
  requestEndDate(): _NSDate | null;
  responseStartDate(): _NSDate | null;
  responseEndDate(): _NSDate | null;
  networkProtocolName(): _NSString | null;
  proxyConnection(): boolean;
  reusedConnection(): boolean;
  resourceFetchType(): number;
  countOfRequestHeaderBytesSent(): number;
  countOfRequestBodyBytesSent(): number;
  countOfRequestBodyBytesBeforeEncoding(): number;
  countOfResponseHeaderBytesReceived(): number;
  countOfResponseBodyBytesReceived(): number;
  countOfResponseBodyBytesAfterDecoding(): number;
  localAddress(): _NSString | null;
  localPort(): _NSNumber | null;
  remoteAddress(): _NSString | null;
  remotePort(): _NSNumber | null;
  negotiatedTLSProtocolVersion(): _NSNumber | null;
  negotiatedTLSCipherSuite(): _NSNumber | null;
  cellular(): boolean;
  expensive(): boolean;
  constrained(): boolean;
  multipath(): boolean;
  domainResolutionProtocol(): number;
}
