// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSData } from "./NSData.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSInputStream } from "./NSInputStream.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSURLRequest extends _NSObject {
  static alloc(): _NSURLRequest;
  static new(): _NSURLRequest;
  init(): _NSURLRequest;
  // Class methods
  static requestWithURL$(URL: _NSURL): _NSURLRequest;
  static requestWithURL$cachePolicy$timeoutInterval$(URL: _NSURL, cachePolicy: number, timeoutInterval: number): _NSURLRequest;
  static supportsSecureCoding(): boolean;

  // Instance methods
  initWithURL$(URL: _NSURL): _NSURLRequest;
  initWithURL$cachePolicy$timeoutInterval$(URL: _NSURL, cachePolicy: number, timeoutInterval: number): _NSURLRequest;
  valueForHTTPHeaderField$(field: _NSString): _NSString | null;

  // Properties
  URL(): _NSURL | null;
  cachePolicy(): number;
  timeoutInterval(): number;
  mainDocumentURL(): _NSURL | null;
  networkServiceType(): number;
  allowsCellularAccess(): boolean;
  allowsExpensiveNetworkAccess(): boolean;
  allowsConstrainedNetworkAccess(): boolean;
  allowsUltraConstrainedNetworkAccess(): boolean;
  assumesHTTP3Capable(): boolean;
  attribution(): number;
  requiresDNSSECValidation(): boolean;
  allowsPersistentDNS(): boolean;
  cookiePartitionIdentifier(): _NSString | null;
  HTTPMethod(): _NSString | null;
  allHTTPHeaderFields(): _NSDictionary | null;
  HTTPBody(): _NSData | null;
  HTTPBodyStream(): _NSInputStream | null;
  HTTPShouldHandleCookies(): boolean;
  HTTPShouldUsePipelining(): boolean;
}
