// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSURLSessionTask } from "./NSURLSessionTask.js";

export declare class _NSURLSessionDataTask extends _NSURLSessionTask {
  static alloc(): _NSURLSessionDataTask;
  // Class methods
  static new(): _NSURLSessionDataTask;

  // Instance methods
  init(): _NSURLSessionDataTask;
}
