// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSNumber } from "./NSNumber.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";
import type { NSRange } from "../structs.js";

export declare class _NSURLComponents extends _NSObject {
  static alloc(): _NSURLComponents;
  static new(): _NSURLComponents;
  // Class methods
  static componentsWithURL$resolvingAgainstBaseURL$(url: _NSURL, resolve: boolean): _NSURLComponents | null;
  static componentsWithString$(URLString: _NSString): _NSURLComponents | null;
  static componentsWithString$encodingInvalidCharacters$(URLString: _NSString, encodingInvalidCharacters: boolean): _NSURLComponents | null;

  // Instance methods
  init(): _NSURLComponents;
  initWithURL$resolvingAgainstBaseURL$(url: _NSURL, resolve: boolean): _NSURLComponents | null;
  initWithString$(URLString: _NSString): _NSURLComponents | null;
  initWithString$encodingInvalidCharacters$(URLString: _NSString, encodingInvalidCharacters: boolean): _NSURLComponents | null;
  URLRelativeToURL$(baseURL: _NSURL | null): _NSURL | null;

  // Properties
  URL(): _NSURL | null;
  string(): _NSString | null;
  scheme(): _NSString | null;
  setScheme$(value: _NSString | null): void;
  user(): _NSString | null;
  setUser$(value: _NSString | null): void;
  password(): _NSString | null;
  setPassword$(value: _NSString | null): void;
  host(): _NSString | null;
  setHost$(value: _NSString | null): void;
  port(): _NSNumber | null;
  setPort$(value: _NSNumber | null): void;
  path(): _NSString | null;
  setPath$(value: _NSString | null): void;
  query(): _NSString | null;
  setQuery$(value: _NSString | null): void;
  fragment(): _NSString | null;
  setFragment$(value: _NSString | null): void;
  percentEncodedUser(): _NSString | null;
  setPercentEncodedUser$(value: _NSString | null): void;
  percentEncodedPassword(): _NSString | null;
  setPercentEncodedPassword$(value: _NSString | null): void;
  percentEncodedHost(): _NSString | null;
  setPercentEncodedHost$(value: _NSString | null): void;
  percentEncodedPath(): _NSString | null;
  setPercentEncodedPath$(value: _NSString | null): void;
  percentEncodedQuery(): _NSString | null;
  setPercentEncodedQuery$(value: _NSString | null): void;
  percentEncodedFragment(): _NSString | null;
  setPercentEncodedFragment$(value: _NSString | null): void;
  encodedHost(): _NSString | null;
  setEncodedHost$(value: _NSString | null): void;
  rangeOfScheme(): NSRange;
  rangeOfUser(): NSRange;
  rangeOfPassword(): NSRange;
  rangeOfHost(): NSRange;
  rangeOfPort(): NSRange;
  rangeOfPath(): NSRange;
  rangeOfQuery(): NSRange;
  rangeOfFragment(): NSRange;
  queryItems(): _NSArray | null;
  setQueryItems$(value: _NSArray | null): void;
  percentEncodedQueryItems(): _NSArray | null;
  setPercentEncodedQueryItems$(value: _NSArray | null): void;
}
