// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSUserNotification } from "./NSUserNotification.js";
import type { _NSUserNotificationCenter } from "./NSUserNotificationCenter.js";

export interface _NSUserNotificationCenterDelegate {
  // Instance methods
  userNotificationCenter$didDeliverNotification$?(center: _NSUserNotificationCenter, notification: _NSUserNotification): void;
  userNotificationCenter$didActivateNotification$?(center: _NSUserNotificationCenter, notification: _NSUserNotification): void;
  userNotificationCenter$shouldPresentNotification$?(center: _NSUserNotificationCenter, notification: _NSUserNotification): boolean;
}
