// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSDate } from "./NSDate.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSObject } from "./NSObject.js";
import type { _NSSet } from "./NSSet.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";

export declare class _NSUserActivity extends _NSObject {
  static alloc(): _NSUserActivity;
  static new(): _NSUserActivity;
  // Class methods
  static deleteSavedUserActivitiesWithPersistentIdentifiers$completionHandler$(persistentIdentifiers: _NSArray, handler: (...args: any[]) => any): void;
  static deleteAllSavedUserActivitiesWithCompletionHandler$(handler: (...args: any[]) => any): void;

  // Instance methods
  initWithActivityType$(activityType: _NSString): _NSUserActivity;
  init(): _NSUserActivity;
  addUserInfoEntriesFromDictionary$(otherDictionary: _NSDictionary): void;
  becomeCurrent(): void;
  resignCurrent(): void;
  invalidate(): void;
  getContinuationStreamsWithCompletionHandler$(completionHandler: (...args: any[]) => any | null): void;

  // Properties
  activityType(): _NSString;
  title(): _NSString | null;
  setTitle$(value: _NSString | null): void;
  userInfo(): _NSDictionary | null;
  setUserInfo$(value: _NSDictionary | null): void;
  requiredUserInfoKeys(): _NSSet | null;
  setRequiredUserInfoKeys$(value: _NSSet | null): void;
  needsSave(): boolean;
  setNeedsSave$(value: boolean): void;
  webpageURL(): _NSURL | null;
  setWebpageURL$(value: _NSURL | null): void;
  referrerURL(): _NSURL | null;
  setReferrerURL$(value: _NSURL | null): void;
  expirationDate(): _NSDate | null;
  setExpirationDate$(value: _NSDate | null): void;
  keywords(): _NSSet;
  setKeywords$(value: _NSSet): void;
  supportsContinuationStreams(): boolean;
  setSupportsContinuationStreams$(value: boolean): void;
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  targetContentIdentifier(): _NSString | null;
  setTargetContentIdentifier$(value: _NSString | null): void;
  eligibleForHandoff(): boolean;
  setEligibleForHandoff$(value: boolean): void;
  eligibleForSearch(): boolean;
  setEligibleForSearch$(value: boolean): void;
  eligibleForPublicIndexing(): boolean;
  setEligibleForPublicIndexing$(value: boolean): void;
  eligibleForPrediction(): boolean;
  setEligibleForPrediction$(value: boolean): void;
  persistentIdentifier(): NobjcObject;
  setPersistentIdentifier$(value: NobjcObject): void;
}
