// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSUserScriptTask } from "./NSUserScriptTask.js";

export declare class _NSUserAutomatorTask extends _NSUserScriptTask {
  static alloc(): _NSUserAutomatorTask;
  static new(): _NSUserAutomatorTask;
  init(): _NSUserAutomatorTask;
  // Instance methods
  executeWithInput$completionHandler$(input: NobjcObject, handler: number | null): void;

  // Properties
  variables(): _NSDictionary | null;
  setVariables$(value: _NSDictionary | null): void;
}
