// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "./NSArray.js";
import type { _NSData } from "./NSData.js";
import type { _NSDictionary } from "./NSDictionary.js";
import type { _NSString } from "./NSString.js";
import type { _NSURL } from "./NSURL.js";
import type { _NSXMLDTD } from "./NSXMLDTD.js";
import type { _NSXMLElement } from "./NSXMLElement.js";
import type { _NSXMLNode } from "./NSXMLNode.js";

export declare class _NSXMLDocument extends _NSXMLNode {
  static alloc(): _NSXMLDocument;
  static new(): _NSXMLDocument;
  // Class methods
  static replacementClassForClass$(cls: NobjcObject): NobjcObject;

  // Instance methods
  init(): _NSXMLDocument;
  initWithXMLString$options$error$(string_: _NSString, mask: number, error: NobjcObject): _NSXMLDocument | null;
  initWithContentsOfURL$options$error$(url: _NSURL, mask: number, error: NobjcObject): _NSXMLDocument | null;
  initWithData$options$error$(data: _NSData, mask: number, error: NobjcObject): _NSXMLDocument | null;
  initWithRootElement$(element: _NSXMLElement | null): _NSXMLDocument;
  setRootElement$(root: _NSXMLElement): void;
  rootElement(): _NSXMLElement | null;
  insertChild$atIndex$(child: _NSXMLNode, index: number): void;
  insertChildren$atIndex$(children: _NSArray, index: number): void;
  removeChildAtIndex$(index: number): void;
  setChildren$(children: _NSArray | null): void;
  addChild$(child: _NSXMLNode): void;
  replaceChildAtIndex$withNode$(index: number, node: _NSXMLNode): void;
  XMLDataWithOptions$(options: number): _NSData;
  objectByApplyingXSLT$arguments$error$(xslt: _NSData, arguments: _NSDictionary | null, error: NobjcObject): NobjcObject;
  objectByApplyingXSLTString$arguments$error$(xslt: _NSString, arguments: _NSDictionary | null, error: NobjcObject): NobjcObject;
  objectByApplyingXSLTAtURL$arguments$error$(xsltURL: _NSURL, argument: _NSDictionary | null, error: NobjcObject): NobjcObject;
  validateAndReturnError$(error: NobjcObject): boolean;

  // Properties
  characterEncoding(): _NSString | null;
  setCharacterEncoding$(value: _NSString | null): void;
  standalone(): boolean;
  setStandalone$(value: boolean): void;
  documentContentKind(): number;
  setDocumentContentKind$(value: number): void;
  MIMEType(): _NSString | null;
  setMIMEType$(value: _NSString | null): void;
  DTD(): _NSXMLDTD | null;
  setDTD$(value: _NSXMLDTD | null): void;
  XMLData(): _NSData;
}
