// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSString } from "./NSString.js";
import type { _NSXMLNode } from "./NSXMLNode.js";

export declare class _NSXMLDTDNode extends _NSXMLNode {
  static alloc(): _NSXMLDTDNode;
  static new(): _NSXMLDTDNode;
  // Instance methods
  initWithXMLString$(string_: _NSString): _NSXMLDTDNode | null;
  initWithKind$options$(kind: number, options: number): _NSXMLDTDNode;
  init(): _NSXMLDTDNode;

  // Properties
  DTDKind(): number;
  setDTDKind$(value: number): void;
  external(): boolean;
  publicID(): _NSString | null;
  setPublicID$(value: _NSString | null): void;
  systemID(): _NSString | null;
  setSystemID$(value: _NSString | null): void;
  notationName(): _NSString | null;
  setNotationName$(value: _NSString | null): void;
}
