// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSSet } from "./NSSet.js";

export declare class _NSXPCInterface extends _NSObject {
  static alloc(): _NSXPCInterface;
  static new(): _NSXPCInterface;
  init(): _NSXPCInterface;
  // Class methods
  static interfaceWithProtocol$(protocol: NobjcObject): _NSXPCInterface;

  // Instance methods
  setClasses$forSelector$argumentIndex$ofReply$(classes: _NSSet, sel: string, arg: number, ofReply: boolean): void;
  classesForSelector$argumentIndex$ofReply$(sel: string, arg: number, ofReply: boolean): _NSSet;
  setInterface$forSelector$argumentIndex$ofReply$(ifc: _NSXPCInterface, sel: string, arg: number, ofReply: boolean): void;
  interfaceForSelector$argumentIndex$ofReply$(sel: string, arg: number, ofReply: boolean): _NSXPCInterface | null;
  setXPCType$forSelector$argumentIndex$ofReply$(type: NobjcObject, sel: string, arg: number, ofReply: boolean): void;
  XPCTypeForSelector$argumentIndex$ofReply$(sel: string, arg: number, ofReply: boolean): NobjcObject;

  // Properties
  protocol(): NobjcObject;
  setProtocol$(value: NobjcObject): void;
}
