// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "./NSObject.js";
import type { _NSString } from "./NSString.js";
import type { _NSXPCListenerEndpoint } from "./NSXPCListenerEndpoint.js";

export declare class _NSXPCListener extends _NSObject {
  static alloc(): _NSXPCListener;
  static new(): _NSXPCListener;
  init(): _NSXPCListener;
  // Class methods
  static serviceListener(): _NSXPCListener;
  static anonymousListener(): _NSXPCListener;

  // Instance methods
  initWithMachServiceName$(name: _NSString): _NSXPCListener;
  resume(): void;
  suspend(): void;
  activate(): void;
  invalidate(): void;
  setConnectionCodeSigningRequirement$(requirement: _NSString): void;

  // Properties
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  endpoint(): _NSXPCListenerEndpoint;
}
