// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMCSSRule } from "./DOMCSSRule.js";

export declare class _DOMCSSUnknownRule extends _DOMCSSRule {
  static alloc(): _DOMCSSUnknownRule;
  static new(): _DOMCSSUnknownRule;
  init(): _DOMCSSUnknownRule;
}
