// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMCSSRule } from "./DOMCSSRule.js";
import type { _DOMCSSValue } from "./DOMCSSValue.js";
import type { _DOMObject } from "./DOMObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMCSSStyleDeclaration extends _DOMObject {
  static alloc(): _DOMCSSStyleDeclaration;
  static new(): _DOMCSSStyleDeclaration;
  init(): _DOMCSSStyleDeclaration;
  // Instance methods
  getPropertyValue$(propertyName: _NSString): _NSString;
  getPropertyCSSValue$(propertyName: _NSString): _DOMCSSValue;
  removeProperty$(propertyName: _NSString): _NSString;
  getPropertyPriority$(propertyName: _NSString): _NSString;
  setProperty$value$priority$(propertyName: _NSString, value: _NSString, priority: _NSString): void;
  item$(index: number): _NSString;
  getPropertyShorthand$(propertyName: _NSString): _NSString;
  isPropertyImplicit$(propertyName: _NSString): boolean;
  setProperty$$$(propertyName: _NSString, value: _NSString, priority: _NSString): void;

  // Properties
  cssText(): _NSString;
  setCssText$(value: _NSString): void;
  length(): number;
  parentRule(): _DOMCSSRule;
}
