// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMCSSRule } from "./DOMCSSRule.js";
import type { _DOMCSSStyleDeclaration } from "./DOMCSSStyleDeclaration.js";

export declare class _DOMCSSFontFaceRule extends _DOMCSSRule {
  static alloc(): _DOMCSSFontFaceRule;
  static new(): _DOMCSSFontFaceRule;
  init(): _DOMCSSFontFaceRule;
  // Properties
  style(): _DOMCSSStyleDeclaration;
}
