// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMEvent } from "./DOMEvent.js";

export interface _DOMEventListener {
  // Instance methods
  handleEvent$?(event: _DOMEvent): void;
}
