// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMNode } from "./DOMNode.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMEntity extends _DOMNode {
  static alloc(): _DOMEntity;
  static new(): _DOMEntity;
  init(): _DOMEntity;
  // Properties
  publicId(): _NSString;
  systemId(): _NSString;
  notationName(): _NSString;
}
