// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLTableCellElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLTableCellElement;
  static new(): _DOMHTMLTableCellElement;
  init(): _DOMHTMLTableCellElement;
  // Properties
  cellIndex(): number;
  align(): _NSString;
  setAlign$(value: _NSString): void;
  axis(): _NSString;
  setAxis$(value: _NSString): void;
  bgColor(): _NSString;
  setBgColor$(value: _NSString): void;
  ch(): _NSString;
  setCh$(value: _NSString): void;
  chOff(): _NSString;
  setChOff$(value: _NSString): void;
  colSpan(): number;
  setColSpan$(value: number): void;
  rowSpan(): number;
  setRowSpan$(value: number): void;
  headers(): _NSString;
  setHeaders$(value: _NSString): void;
  height(): _NSString;
  setHeight$(value: _NSString): void;
  noWrap(): boolean;
  setNoWrap$(value: boolean): void;
  vAlign(): _NSString;
  setVAlign$(value: _NSString): void;
  width(): _NSString;
  setWidth$(value: _NSString): void;
  abbr(): _NSString;
  setAbbr$(value: _NSString): void;
  scope(): _NSString;
  setScope$(value: _NSString): void;
}
