// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLModElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLModElement;
  static new(): _DOMHTMLModElement;
  init(): _DOMHTMLModElement;
  // Properties
  cite(): _NSString;
  setCite$(value: _NSString): void;
  dateTime(): _NSString;
  setDateTime$(value: _NSString): void;
}
