// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";

export declare class _DOMHTMLAreaElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLAreaElement;
  static new(): _DOMHTMLAreaElement;
  init(): _DOMHTMLAreaElement;
  // Properties
  alt(): _NSString;
  setAlt$(value: _NSString): void;
  coords(): _NSString;
  setCoords$(value: _NSString): void;
  noHref(): boolean;
  setNoHref$(value: boolean): void;
  shape(): _NSString;
  setShape$(value: _NSString): void;
  target(): _NSString;
  setTarget$(value: _NSString): void;
  accessKey(): _NSString;
  setAccessKey$(value: _NSString): void;
  absoluteLinkURL(): _NSURL;
  href(): _NSString;
  setHref$(value: _NSString): void;
  protocol(): _NSString;
  host(): _NSString;
  hostname(): _NSString;
  port(): _NSString;
  pathname(): _NSString;
  search(): _NSString;
  hashName(): _NSString;
}
