// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";

export declare class _DOMHTMLPreElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLPreElement;
  static new(): _DOMHTMLPreElement;
  init(): _DOMHTMLPreElement;
  // Properties
  width(): number;
  setWidth$(value: number): void;
  wrap(): boolean;
  setWrap$(value: boolean): void;
}
