// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLAppletElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLAppletElement;
  static new(): _DOMHTMLAppletElement;
  init(): _DOMHTMLAppletElement;
  // Properties
  align(): _NSString;
  setAlign$(value: _NSString): void;
  alt(): _NSString;
  setAlt$(value: _NSString): void;
  archive(): _NSString;
  setArchive$(value: _NSString): void;
  code(): _NSString;
  setCode$(value: _NSString): void;
  codeBase(): _NSString;
  setCodeBase$(value: _NSString): void;
  height(): _NSString;
  setHeight$(value: _NSString): void;
  hspace(): number;
  setHspace$(value: number): void;
  name(): _NSString;
  setName$(value: _NSString): void;
  object(): _NSString;
  setObject$(value: _NSString): void;
  vspace(): number;
  setVspace$(value: number): void;
  width(): _NSString;
  setWidth$(value: _NSString): void;
}
