// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _DOMHTMLFormElement } from "./DOMHTMLFormElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLButtonElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLButtonElement;
  static new(): _DOMHTMLButtonElement;
  init(): _DOMHTMLButtonElement;
  // Instance methods
  click(): void;

  // Properties
  autofocus(): boolean;
  setAutofocus$(value: boolean): void;
  disabled(): boolean;
  setDisabled$(value: boolean): void;
  form(): _DOMHTMLFormElement;
  type(): _NSString;
  setType$(value: _NSString): void;
  name(): _NSString;
  setName$(value: _NSString): void;
  value(): _NSString;
  setValue$(value: _NSString): void;
  willValidate(): boolean;
  accessKey(): _NSString;
  setAccessKey$(value: _NSString): void;
}
