// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";

export declare class _DOMHTMLDirectoryElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLDirectoryElement;
  static new(): _DOMHTMLDirectoryElement;
  init(): _DOMHTMLDirectoryElement;
  // Properties
  compact(): boolean;
  setCompact$(value: boolean): void;
}
