// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLMetaElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLMetaElement;
  static new(): _DOMHTMLMetaElement;
  init(): _DOMHTMLMetaElement;
  // Properties
  content(): _NSString;
  setContent$(value: _NSString): void;
  httpEquiv(): _NSString;
  setHttpEquiv$(value: _NSString): void;
  name(): _NSString;
  setName$(value: _NSString): void;
  scheme(): _NSString;
  setScheme$(value: _NSString): void;
}
