// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLOListElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLOListElement;
  static new(): _DOMHTMLOListElement;
  init(): _DOMHTMLOListElement;
  // Properties
  compact(): boolean;
  setCompact$(value: boolean): void;
  start(): number;
  setStart$(value: number): void;
  type(): _NSString;
  setType$(value: _NSString): void;
}
