// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLCollection } from "./DOMHTMLCollection.js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLTableRowElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLTableRowElement;
  static new(): _DOMHTMLTableRowElement;
  init(): _DOMHTMLTableRowElement;
  // Instance methods
  insertCell$(index: number): _DOMHTMLElement;
  deleteCell$(index: number): void;

  // Properties
  rowIndex(): number;
  sectionRowIndex(): number;
  cells(): _DOMHTMLCollection;
  align(): _NSString;
  setAlign$(value: _NSString): void;
  bgColor(): _NSString;
  setBgColor$(value: _NSString): void;
  ch(): _NSString;
  setCh$(value: _NSString): void;
  chOff(): _NSString;
  setChOff$(value: _NSString): void;
  vAlign(): _NSString;
  setVAlign$(value: _NSString): void;
}
