// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLScriptElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLScriptElement;
  static new(): _DOMHTMLScriptElement;
  init(): _DOMHTMLScriptElement;
  // Properties
  text(): _NSString;
  setText$(value: _NSString): void;
  htmlFor(): _NSString;
  setHtmlFor$(value: _NSString): void;
  event(): _NSString;
  setEvent$(value: _NSString): void;
  charset(): _NSString;
  setCharset$(value: _NSString): void;
  defer(): boolean;
  setDefer$(value: boolean): void;
  src(): _NSString;
  setSrc$(value: _NSString): void;
  type(): _NSString;
  setType$(value: _NSString): void;
}
