// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _DOMHTMLFormElement } from "./DOMHTMLFormElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLTextAreaElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLTextAreaElement;
  static new(): _DOMHTMLTextAreaElement;
  init(): _DOMHTMLTextAreaElement;
  // Instance methods
  select(): void;
  setSelectionRange$end$(start: number, end: number): void;

  // Properties
  autofocus(): boolean;
  setAutofocus$(value: boolean): void;
  disabled(): boolean;
  setDisabled$(value: boolean): void;
  form(): _DOMHTMLFormElement;
  name(): _NSString;
  setName$(value: _NSString): void;
  readOnly(): boolean;
  setReadOnly$(value: boolean): void;
  rows(): number;
  setRows$(value: number): void;
  cols(): number;
  setCols$(value: number): void;
  type(): _NSString;
  defaultValue(): _NSString;
  setDefaultValue$(value: _NSString): void;
  value(): _NSString;
  setValue$(value: _NSString): void;
  willValidate(): boolean;
  selectionStart(): number;
  setSelectionStart$(value: number): void;
  selectionEnd(): number;
  setSelectionEnd$(value: number): void;
  accessKey(): _NSString;
  setAccessKey$(value: _NSString): void;
}
