// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLLIElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLLIElement;
  static new(): _DOMHTMLLIElement;
  init(): _DOMHTMLLIElement;
  // Properties
  type(): _NSString;
  setType$(value: _NSString): void;
  value(): number;
  setValue$(value: number): void;
}
