// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLCollection } from "./DOMHTMLCollection.js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _DOMHTMLTableCaptionElement } from "./DOMHTMLTableCaptionElement.js";
import type { _DOMHTMLTableSectionElement } from "./DOMHTMLTableSectionElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLTableElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLTableElement;
  static new(): _DOMHTMLTableElement;
  init(): _DOMHTMLTableElement;
  // Instance methods
  createTHead(): _DOMHTMLElement;
  deleteTHead(): void;
  createTFoot(): _DOMHTMLElement;
  deleteTFoot(): void;
  createCaption(): _DOMHTMLElement;
  deleteCaption(): void;
  insertRow$(index: number): _DOMHTMLElement;
  deleteRow$(index: number): void;

  // Properties
  caption(): _DOMHTMLTableCaptionElement;
  setCaption$(value: _DOMHTMLTableCaptionElement): void;
  tHead(): _DOMHTMLTableSectionElement;
  setTHead$(value: _DOMHTMLTableSectionElement): void;
  tFoot(): _DOMHTMLTableSectionElement;
  setTFoot$(value: _DOMHTMLTableSectionElement): void;
  rows(): _DOMHTMLCollection;
  tBodies(): _DOMHTMLCollection;
  align(): _NSString;
  setAlign$(value: _NSString): void;
  bgColor(): _NSString;
  setBgColor$(value: _NSString): void;
  border(): _NSString;
  setBorder$(value: _NSString): void;
  cellPadding(): _NSString;
  setCellPadding$(value: _NSString): void;
  cellSpacing(): _NSString;
  setCellSpacing$(value: _NSString): void;
  frameBorders(): _NSString;
  setFrameBorders$(value: _NSString): void;
  rules(): _NSString;
  setRules$(value: _NSString): void;
  summary(): _NSString;
  setSummary$(value: _NSString): void;
  width(): _NSString;
  setWidth$(value: _NSString): void;
}
