// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMHTMLElement } from "./DOMHTMLElement.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMHTMLDivElement extends _DOMHTMLElement {
  static alloc(): _DOMHTMLDivElement;
  static new(): _DOMHTMLDivElement;
  init(): _DOMHTMLDivElement;
  // Properties
  align(): _NSString;
  setAlign$(value: _NSString): void;
}
