// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMAbstractView } from "./DOMAbstractView.js";
import type { _DOMUIEvent } from "./DOMUIEvent.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMKeyboardEvent extends _DOMUIEvent {
  static alloc(): _DOMKeyboardEvent;
  static new(): _DOMKeyboardEvent;
  init(): _DOMKeyboardEvent;
  // Instance methods
  getModifierState$(keyIdentifierArg: _NSString): boolean;
  initKeyboardEvent$canBubble$cancelable$view$keyIdentifier$location$ctrlKey$altKey$shiftKey$metaKey$altGraphKey$(type: _NSString, canBubble: boolean, cancelable: boolean, view: _DOMAbstractView, keyIdentifier: _NSString, location: number, ctrlKey: boolean, altKey: boolean, shiftKey: boolean, metaKey: boolean, altGraphKey: boolean): void;
  initKeyboardEvent$canBubble$cancelable$view$keyIdentifier$location$ctrlKey$altKey$shiftKey$metaKey$(type: _NSString, canBubble: boolean, cancelable: boolean, view: _DOMAbstractView, keyIdentifier: _NSString, location: number, ctrlKey: boolean, altKey: boolean, shiftKey: boolean, metaKey: boolean): void;
  initKeyboardEvent$canBubble$cancelable$view$keyIdentifier$keyLocation$ctrlKey$altKey$shiftKey$metaKey$altGraphKey$(type: _NSString, canBubble: boolean, cancelable: boolean, view: _DOMAbstractView, keyIdentifier: _NSString, keyLocation: number, ctrlKey: boolean, altKey: boolean, shiftKey: boolean, metaKey: boolean, altGraphKey: boolean): void;
  initKeyboardEvent$canBubble$cancelable$view$keyIdentifier$keyLocation$ctrlKey$altKey$shiftKey$metaKey$(type: _NSString, canBubble: boolean, cancelable: boolean, view: _DOMAbstractView, keyIdentifier: _NSString, keyLocation: number, ctrlKey: boolean, altKey: boolean, shiftKey: boolean, metaKey: boolean): void;

  // Properties
  keyIdentifier(): _NSString;
  location(): number;
  keyLocation(): number;
  ctrlKey(): boolean;
  shiftKey(): boolean;
  altKey(): boolean;
  metaKey(): boolean;
  altGraphKey(): boolean;
  keyCode(): number;
  charCode(): number;
}
