// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMNode } from "./DOMNode.js";
import type { _DOMObject } from "./DOMObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMNamedNodeMap extends _DOMObject {
  static alloc(): _DOMNamedNodeMap;
  static new(): _DOMNamedNodeMap;
  init(): _DOMNamedNodeMap;
  // Instance methods
  getNamedItem$(name: _NSString): _DOMNode;
  setNamedItem$(node: _DOMNode): _DOMNode;
  removeNamedItem$(name: _NSString): _DOMNode;
  item$(index: number): _DOMNode;
  getNamedItemNS$localName$(namespaceURI: _NSString, localName: _NSString): _DOMNode;
  setNamedItemNS$(node: _DOMNode): _DOMNode;
  removeNamedItemNS$localName$(namespaceURI: _NSString, localName: _NSString): _DOMNode;
  getNamedItemNS$$(namespaceURI: _NSString, localName: _NSString): _DOMNode;
  removeNamedItemNS$$(namespaceURI: _NSString, localName: _NSString): _DOMNode;

  // Properties
  length(): number;
}
