// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMEvent } from "./DOMEvent.js";

export declare class _DOMOverflowEvent extends _DOMEvent {
  static alloc(): _DOMOverflowEvent;
  static new(): _DOMOverflowEvent;
  init(): _DOMOverflowEvent;
  // Instance methods
  initOverflowEvent$horizontalOverflow$verticalOverflow$(orient: number, horizontalOverflow: boolean, verticalOverflow: boolean): void;

  // Properties
  orient(): number;
  horizontalOverflow(): boolean;
  verticalOverflow(): boolean;
}
