// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _DOMAbstractView } from "./DOMAbstractView.js";
import type { _DOMEvent } from "./DOMEvent.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _DOMUIEvent extends _DOMEvent {
  static alloc(): _DOMUIEvent;
  static new(): _DOMUIEvent;
  init(): _DOMUIEvent;
  // Instance methods
  initUIEvent$canBubble$cancelable$view$detail$(type: _NSString, canBubble: boolean, cancelable: boolean, view: _DOMAbstractView, detail: number): void;
  initUIEvent$$$$$(type: _NSString, canBubble: boolean, cancelable: boolean, view: _DOMAbstractView, detail: number): void;

  // Properties
  view(): _DOMAbstractView;
  detail(): number;
  keyCode(): number;
  charCode(): number;
  layerX(): number;
  layerY(): number;
  pageX(): number;
  pageY(): number;
  which(): number;
}
