// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSString } from "../Foundation/NSString.js";

export interface _DOMXPathNSResolver {
  // Instance methods
  lookupNamespaceURI$?(prefix: _NSString): _NSString;
}
