// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _WebDataSource } from "./WebDataSource.js";
import type { _NSData } from "../Foundation/NSData.js";
import type { _NSError } from "../Foundation/NSError.js";
import type { _NSString } from "../Foundation/NSString.js";

export interface _WebDocumentRepresentation {
  // Instance methods
  setDataSource$?(dataSource: _WebDataSource): void;
  receivedData$withDataSource$?(data: _NSData, dataSource: _WebDataSource): void;
  receivedError$withDataSource$?(error: _NSError, dataSource: _WebDataSource): void;
  finishedLoadingWithDataSource$?(dataSource: _WebDataSource): void;
  canProvideDocumentSource?(): boolean;
  documentSource?(): _NSString;
  title?(): _NSString;
}
