// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSPrintInfo } from "../AppKit/NSPrintInfo.js";
import type { _NSPrintOperation } from "../AppKit/NSPrintOperation.js";
import type { _NSView } from "../AppKit/NSView.js";
import type { _WebFrame } from "./WebFrame.js";

export declare class _WebFrameView extends _NSView {
  static alloc(): _WebFrameView;
  static new(): _WebFrameView;
  init(): _WebFrameView;
  // Instance methods
  printOperationWithPrintInfo$(printInfo: _NSPrintInfo): _NSPrintOperation;
  printDocumentView(): void;

  // Properties
  webFrame(): _WebFrame;
  documentView(): _NSView;
  allowsScrolling(): boolean;
  setAllowsScrolling$(value: boolean): void;
  canPrintHeadersAndFooters(): boolean;
  documentViewShouldHandlePrint(): boolean;
}
