// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _WebFrame } from "./WebFrame.js";
import type { _WebView } from "./WebView.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSError } from "../Foundation/NSError.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURLRequest } from "../Foundation/NSURLRequest.js";

export interface _WebPolicyDelegate {
  // Instance methods
  webView$decidePolicyForNavigationAction$request$frame$decisionListener$?(webView: _WebView, actionInformation: _NSDictionary, request: _NSURLRequest, frame: _WebFrame, listener: NobjcObject): void;
  webView$decidePolicyForNewWindowAction$request$newFrameName$decisionListener$?(webView: _WebView, actionInformation: _NSDictionary, request: _NSURLRequest, frameName: _NSString, listener: NobjcObject): void;
  webView$decidePolicyForMIMEType$request$frame$decisionListener$?(webView: _WebView, type: _NSString, request: _NSURLRequest, frame: _WebFrame, listener: NobjcObject): void;
  webView$unableToImplementPolicyWithError$frame$?(webView: _WebView, error: _NSError, frame: _WebFrame): void;
}
