// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";

export declare class _WKBackForwardListItem extends _NSObject {
  static alloc(): _WKBackForwardListItem;
  static new(): _WKBackForwardListItem;
  init(): _WKBackForwardListItem;
  // Properties
  URL(): _NSURL;
  title(): _NSString | null;
  initialURL(): _NSURL;
}
