// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _WKDownload } from "./WKDownload.js";
import type { _NSData } from "../Foundation/NSData.js";
import type { _NSError } from "../Foundation/NSError.js";
import type { _NSHTTPURLResponse } from "../Foundation/NSHTTPURLResponse.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";
import type { _NSURLAuthenticationChallenge } from "../Foundation/NSURLAuthenticationChallenge.js";
import type { _NSURLRequest } from "../Foundation/NSURLRequest.js";
import type { _NSURLResponse } from "../Foundation/NSURLResponse.js";

export interface _WKDownloadDelegate {
  // Instance methods
  download$decideDestinationUsingResponse$suggestedFilename$completionHandler$?(download: _WKDownload, response: _NSURLResponse, suggestedFilename: _NSString, completionHandler: (...args: any[]) => any | null): void;
  download$willPerformHTTPRedirection$newRequest$decisionHandler$?(download: _WKDownload, response: _NSHTTPURLResponse, request: _NSURLRequest, decisionHandler: (...args: any[]) => any): void;
  download$didReceiveAuthenticationChallenge$completionHandler$?(download: _WKDownload, challenge: _NSURLAuthenticationChallenge, completionHandler: (...args: any[]) => any | null): void;
  downloadDidFinish$?(download: _WKDownload): void;
  download$didFailWithError$resumeData$?(download: _WKDownload, error: _NSError, resumeData: _NSData | null): void;
  download$decidePlaceholderPolicy$?(download: _WKDownload, completionHandler: (...args: any[]) => any | null): void;
  download$didReceivePlaceholderURL$completionHandler$?(download: _WKDownload, url: _NSURL, completionHandler: (...args: any[]) => any): void;
  download$didReceiveFinalURL$?(download: _WKDownload, url: _NSURL): void;
}
