// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSObject } from "../Foundation/NSObject.js";

export declare class _WKHTTPCookieStore extends _NSObject {
  static alloc(): _WKHTTPCookieStore;
  static new(): _WKHTTPCookieStore;
  init(): _WKHTTPCookieStore;
  // Instance methods
  getAllCookies$(completionHandler: (...args: any[]) => any): void;
  setCookie$completionHandler$(cookie: NobjcObject, completionHandler: (...args: any[]) => any | null): void;
  setCookies$completionHandler$(cookies: _NSArray, completionHandler: (...args: any[]) => any | null): void;
  deleteCookie$completionHandler$(cookie: NobjcObject, completionHandler: (...args: any[]) => any | null): void;
  addObserver$(observer: NobjcObject): void;
  removeObserver$(observer: NobjcObject): void;
  setCookiePolicy$completionHandler$(policy: number, completionHandler: (...args: any[]) => any | null): void;
  getCookiePolicy$(completionHandler: (...args: any[]) => any): void;
}
