// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _WKFrameInfo } from "./WKFrameInfo.js";
import type { _WKNavigationAction } from "./WKNavigationAction.js";
import type { _WKOpenPanelParameters } from "./WKOpenPanelParameters.js";
import type { _WKSecurityOrigin } from "./WKSecurityOrigin.js";
import type { _WKWebView } from "./WKWebView.js";
import type { _WKWebViewConfiguration } from "./WKWebViewConfiguration.js";
import type { _WKWindowFeatures } from "./WKWindowFeatures.js";
import type { _NSString } from "../Foundation/NSString.js";

export interface _WKUIDelegate {
  // Instance methods
  webView$createWebViewWithConfiguration$forNavigationAction$windowFeatures$?(webView: _WKWebView, configuration: _WKWebViewConfiguration, navigationAction: _WKNavigationAction, windowFeatures: _WKWindowFeatures): _WKWebView | null;
  webViewDidClose$?(webView: _WKWebView): void;
  webView$runJavaScriptAlertPanelWithMessage$initiatedByFrame$completionHandler$?(webView: _WKWebView, message: _NSString, frame: _WKFrameInfo, completionHandler: (...args: any[]) => any): void;
  webView$runJavaScriptConfirmPanelWithMessage$initiatedByFrame$completionHandler$?(webView: _WKWebView, message: _NSString, frame: _WKFrameInfo, completionHandler: (...args: any[]) => any): void;
  webView$runJavaScriptTextInputPanelWithPrompt$defaultText$initiatedByFrame$completionHandler$?(webView: _WKWebView, prompt: _NSString, defaultText: _NSString | null, frame: _WKFrameInfo, completionHandler: (...args: any[]) => any | null): void;
  webView$requestMediaCapturePermissionForOrigin$initiatedByFrame$type$decisionHandler$?(webView: _WKWebView, origin: _WKSecurityOrigin, frame: _WKFrameInfo, type: number, decisionHandler: (...args: any[]) => any): void;
  webView$requestDeviceOrientationAndMotionPermissionForOrigin$initiatedByFrame$decisionHandler$?(webView: _WKWebView, origin: _WKSecurityOrigin, frame: _WKFrameInfo, decisionHandler: (...args: any[]) => any): void;
  webView$runOpenPanelWithParameters$initiatedByFrame$completionHandler$?(webView: _WKWebView, parameters: _WKOpenPanelParameters, frame: _WKFrameInfo, completionHandler: (...args: any[]) => any | null): void;
}
