// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _WKContentWorld } from "./WKContentWorld.js";

export declare class _WKUserScript extends _NSObject {
  static alloc(): _WKUserScript;
  static new(): _WKUserScript;
  init(): _WKUserScript;
  // Instance methods
  initWithSource$injectionTime$forMainFrameOnly$(source: _NSString, injectionTime: number, forMainFrameOnly: boolean): _WKUserScript;
  initWithSource$injectionTime$forMainFrameOnly$inContentWorld$(source: _NSString, injectionTime: number, forMainFrameOnly: boolean, contentWorld: _WKContentWorld): _WKUserScript;

  // Properties
  source(): _NSString;
  injectionTime(): number;
  forMainFrameOnly(): boolean;
}
