// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _WKSnapshotConfiguration } from "./WKSnapshotConfiguration.js";
import type { _WKWebExtensionContext } from "./WKWebExtensionContext.js";
import type { _WKWebExtensionTabConfiguration } from "./WKWebExtensionTabConfiguration.js";
import type { _WKWebView } from "./WKWebView.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";
import type { CGSize } from "../structs.js";

export interface _WKWebExtensionTab {
  // Instance methods
  windowForWebExtensionContext$?(context: _WKWebExtensionContext): NobjcObject;
  indexInWindowForWebExtensionContext$?(context: _WKWebExtensionContext): number;
  parentTabForWebExtensionContext$?(context: _WKWebExtensionContext): NobjcObject;
  setParentTab$forWebExtensionContext$completionHandler$?(parentTab: NobjcObject, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  webViewForWebExtensionContext$?(context: _WKWebExtensionContext): _WKWebView | null;
  titleForWebExtensionContext$?(context: _WKWebExtensionContext): _NSString | null;
  isPinnedForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
  setPinned$forWebExtensionContext$completionHandler$?(pinned: boolean, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  isReaderModeAvailableForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
  isReaderModeActiveForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
  setReaderModeActive$forWebExtensionContext$completionHandler$?(active: boolean, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  isPlayingAudioForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
  isMutedForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
  setMuted$forWebExtensionContext$completionHandler$?(muted: boolean, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  sizeForWebExtensionContext$?(context: _WKWebExtensionContext): CGSize;
  zoomFactorForWebExtensionContext$?(context: _WKWebExtensionContext): number;
  setZoomFactor$forWebExtensionContext$completionHandler$?(zoomFactor: number, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  urlForWebExtensionContext$?(context: _WKWebExtensionContext): _NSURL | null;
  pendingURLForWebExtensionContext$?(context: _WKWebExtensionContext): _NSURL | null;
  isLoadingCompleteForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
  detectWebpageLocaleForWebExtensionContext$completionHandler$?(context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  takeSnapshotUsingConfiguration$forWebExtensionContext$completionHandler$?(configuration: _WKSnapshotConfiguration, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  loadURL$forWebExtensionContext$completionHandler$?(url: _NSURL, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  reloadFromOrigin$forWebExtensionContext$completionHandler$?(fromOrigin: boolean, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  goBackForWebExtensionContext$completionHandler$?(context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  goForwardForWebExtensionContext$completionHandler$?(context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  activateForWebExtensionContext$completionHandler$?(context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  isSelectedForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
  setSelected$forWebExtensionContext$completionHandler$?(selected: boolean, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  duplicateUsingConfiguration$forWebExtensionContext$completionHandler$?(configuration: _WKWebExtensionTabConfiguration, context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  closeForWebExtensionContext$completionHandler$?(context: _WKWebExtensionContext, completionHandler: (...args: any[]) => any | null): void;
  shouldGrantPermissionsOnUserGestureForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
  shouldBypassPermissionsForWebExtensionContext$?(context: _WKWebExtensionContext): boolean;
}
