// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSURL } from "../Foundation/NSURL.js";

export declare class _WKWebExtensionTabConfiguration extends _NSObject {
  static alloc(): _WKWebExtensionTabConfiguration;
  static new(): _WKWebExtensionTabConfiguration;
  init(): _WKWebExtensionTabConfiguration;
  // Properties
  window(): NobjcObject;
  index(): number;
  parentTab(): NobjcObject;
  url(): _NSURL | null;
  shouldBeActive(): boolean;
  shouldAddToSelection(): boolean;
  shouldBePinned(): boolean;
  shouldBeMuted(): boolean;
  shouldReaderModeBeActive(): boolean;
}
