// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";

export declare class _WKWebExtensionMatchPattern extends _NSObject {
  static alloc(): _WKWebExtensionMatchPattern;
  static new(): _WKWebExtensionMatchPattern;
  init(): _WKWebExtensionMatchPattern;
  // Class methods
  static registerCustomURLScheme$(urlScheme: _NSString): void;
  static allURLsMatchPattern(): _WKWebExtensionMatchPattern;
  static allHostsAndSchemesMatchPattern(): _WKWebExtensionMatchPattern;
  static matchPatternWithString$(string_: _NSString): _WKWebExtensionMatchPattern | null;
  static matchPatternWithScheme$host$path$(scheme: _NSString, host: _NSString, path: _NSString): _WKWebExtensionMatchPattern | null;

  // Instance methods
  initWithString$error$(string_: _NSString, error: NobjcObject): _WKWebExtensionMatchPattern | null;
  initWithScheme$host$path$error$(scheme: _NSString, host: _NSString, path: _NSString, error: NobjcObject): _WKWebExtensionMatchPattern | null;
  matchesURL$(url: _NSURL | null): boolean;
  matchesURL$options$(url: _NSURL | null, options: number): boolean;
  matchesPattern$(pattern: _WKWebExtensionMatchPattern | null): boolean;
  matchesPattern$options$(pattern: _WKWebExtensionMatchPattern | null, options: number): boolean;

  // Properties
  string(): _NSString;
  scheme(): _NSString | null;
  host(): _NSString | null;
  path(): _NSString | null;
  matchesAllURLs(): boolean;
  matchesAllHosts(): boolean;
}
