// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSAccessibilityButton } from "./NSAccessibilityButton.js";

export interface _NSAccessibilitySwitch extends _NSAccessibilityButton {
  // Instance methods
  accessibilityValue?(): _NSString | null;
  accessibilityPerformIncrement?(): boolean;
  accessibilityPerformDecrement?(): boolean;
}
