// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSAccessibilityCustomAction extends _NSObject {
  static alloc(): _NSAccessibilityCustomAction;
  static new(): _NSAccessibilityCustomAction;
  init(): _NSAccessibilityCustomAction;
  // Instance methods
  initWithName$handler$(name: _NSString, handler: (...args: any[]) => any | null): _NSAccessibilityCustomAction;
  initWithName$target$selector$(name: _NSString, target: NobjcObject, selector: string): _NSAccessibilityCustomAction;

  // Properties
  name(): _NSString;
  setName$(value: _NSString): void;
  handler(): (...args: any[]) => any | null;
  setHandler$(value: (...args: any[]) => any | null): void;
  target(): NobjcObject;
  setTarget$(value: NobjcObject): void;
  selector(): string | null;
  setSelector$(value: string | null): void;
}
