// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSAccessibilityStaticText } from "./NSAccessibilityStaticText.js";
import type { CGRect, NSRange } from "../structs.js";

export interface _NSAccessibilityNavigableStaticText extends _NSAccessibilityStaticText {
  // Instance methods
  accessibilityStringForRange$?(range: NSRange): _NSString | null;
  accessibilityLineForIndex$?(index: number): number;
  accessibilityRangeForLine$?(lineNumber: number): NSRange;
  accessibilityFrameForRange$?(range: NSRange): CGRect;
}
