// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSAccessibilityCustomRotor extends _NSObject {
  static alloc(): _NSAccessibilityCustomRotor;
  static new(): _NSAccessibilityCustomRotor;
  init(): _NSAccessibilityCustomRotor;
  // Instance methods
  initWithLabel$itemSearchDelegate$(label: _NSString, itemSearchDelegate: NobjcObject): _NSAccessibilityCustomRotor;
  initWithRotorType$itemSearchDelegate$(rotorType: number, itemSearchDelegate: NobjcObject): _NSAccessibilityCustomRotor;

  // Properties
  type(): number;
  setType$(value: number): void;
  label(): _NSString;
  setLabel$(value: _NSString): void;
  itemSearchDelegate(): NobjcObject;
  setItemSearchDelegate$(value: NobjcObject): void;
  itemLoadingDelegate(): NobjcObject;
  setItemLoadingDelegate$(value: NobjcObject): void;
}
