// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSString } from "../Foundation/NSString.js";

export interface _NSAccessibilitySlider {
  // Instance methods
  accessibilityLabel?(): _NSString | null;
  accessibilityValue?(): NobjcObject;
  accessibilityPerformIncrement?(): boolean;
  accessibilityPerformDecrement?(): boolean;
}
