// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { NSRange } from "../structs.js";

export interface _NSAccessibilityElementLoading {
  // Instance methods
  accessibilityElementWithToken$?(token: number): NobjcObject;
  accessibilityRangeInTargetElementWithToken$?(token: number): NSRange;
}
