// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAccessibilityGroup } from "./NSAccessibilityGroup.js";
import type { CGRect } from "../structs.js";

export interface _NSAccessibilityLayoutItem extends _NSAccessibilityGroup {
  // Instance methods
  setAccessibilityFrame$?(frame: CGRect): void;
}
