// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSData } from "../Foundation/NSData.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSAdaptiveImageGlyph extends _NSObject {
  static alloc(): _NSAdaptiveImageGlyph;
  static new(): _NSAdaptiveImageGlyph;
  init(): _NSAdaptiveImageGlyph;
  // Class methods
  static contentType(): NobjcObject;

  // Instance methods
  initWithImageContent$(imageContent: _NSData): _NSAdaptiveImageGlyph;
  initWithCoder$(coder: _NSCoder): _NSAdaptiveImageGlyph;

  // Properties
  imageContent(): _NSData;
  contentIdentifier(): _NSString;
  contentDescription(): _NSString;
}
