// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSEvent } from "./NSEvent.js";
import type { _NSPanGestureRecognizer } from "./NSPanGestureRecognizer.js";
import type { _NSView } from "./NSView.js";
import type { CGPoint } from "../structs.js";

export declare class _NSAlignmentFeedbackFilter extends _NSObject {
  static alloc(): _NSAlignmentFeedbackFilter;
  static new(): _NSAlignmentFeedbackFilter;
  init(): _NSAlignmentFeedbackFilter;
  // Class methods
  static inputEventMask(): number;

  // Instance methods
  updateWithEvent$(event: _NSEvent): void;
  updateWithPanRecognizer$(panRecognizer: _NSPanGestureRecognizer): void;
  alignmentFeedbackTokenForMovementInView$previousPoint$alignedPoint$defaultPoint$(view: _NSView | null, previousPoint: CGPoint, alignedPoint: CGPoint, defaultPoint: CGPoint): NobjcObject;
  alignmentFeedbackTokenForHorizontalMovementInView$previousX$alignedX$defaultX$(view: _NSView | null, previousX: number, alignedX: number, defaultX: number): NobjcObject;
  alignmentFeedbackTokenForVerticalMovementInView$previousY$alignedY$defaultY$(view: _NSView | null, previousY: number, alignedY: number, defaultY: number): NobjcObject;
  performFeedback$performanceTime$(alignmentFeedbackTokens: NobjcObject, performanceTime: number): void;
}
