// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSObject } from "../Foundation/NSObject.js";

export declare class _NSAnimation extends _NSObject {
  static alloc(): _NSAnimation;
  static new(): _NSAnimation;
  init(): _NSAnimation;
  // Instance methods
  initWithDuration$animationCurve$(duration: number, animationCurve: number): _NSAnimation;
  initWithCoder$(coder: _NSCoder): _NSAnimation | null;
  startAnimation(): void;
  stopAnimation(): void;
  addProgressMark$(progressMark: number): void;
  removeProgressMark$(progressMark: number): void;
  startWhenAnimation$reachesProgress$(animation: _NSAnimation, startProgress: number): void;
  stopWhenAnimation$reachesProgress$(animation: _NSAnimation, stopProgress: number): void;
  clearStartAnimation(): void;
  clearStopAnimation(): void;

  // Properties
  animating(): boolean;
  currentProgress(): number;
  setCurrentProgress$(value: number): void;
  duration(): number;
  setDuration$(value: number): void;
  animationBlockingMode(): number;
  setAnimationBlockingMode$(value: number): void;
  frameRate(): number;
  setFrameRate$(value: number): void;
  animationCurve(): number;
  setAnimationCurve$(value: number): void;
  currentValue(): number;
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  progressMarks(): _NSArray;
  setProgressMarks$(value: _NSArray): void;
  runLoopModesForAnimating(): _NSArray | null;
}
