// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSView } from "./NSView.js";

export declare class _NSBackgroundExtensionView extends _NSView {
  static alloc(): _NSBackgroundExtensionView;
  static new(): _NSBackgroundExtensionView;
  init(): _NSBackgroundExtensionView;
  // Properties
  contentView(): _NSView | null;
  setContentView$(value: _NSView | null): void;
  automaticallyPlacesContentView(): boolean;
  setAutomaticallyPlacesContentView$(value: boolean): void;
}
