// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSBindingSelectionMarker extends _NSObject {
  static alloc(): _NSBindingSelectionMarker;
  static new(): _NSBindingSelectionMarker;
  init(): _NSBindingSelectionMarker;
  // Class methods
  static setDefaultPlaceholder$forMarker$onClass$withBinding$(placeholder: NobjcObject, marker: _NSBindingSelectionMarker | null, objectClass: NobjcObject, binding: _NSString): void;
  static defaultPlaceholderForMarker$onClass$withBinding$(marker: _NSBindingSelectionMarker | null, objectClass: NobjcObject, binding: _NSString): NobjcObject;
  static multipleValuesSelectionMarker(): NobjcObject;
  static noSelectionMarker(): NobjcObject;
  static notApplicableSelectionMarker(): NobjcObject;
}
