// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSFont } from "./NSFont.js";
import type { _NSView } from "./NSView.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGRect, CGSize } from "../structs.js";

export declare class _NSBox extends _NSView {
  static alloc(): _NSBox;
  static new(): _NSBox;
  init(): _NSBox;
  // Instance methods
  sizeToFit(): void;
  setFrameFromContentFrame$(contentFrame: CGRect): void;
  setTitleWithMnemonic$(stringWithAmpersand: _NSString): void;

  // Properties
  boxType(): number;
  setBoxType$(value: number): void;
  titlePosition(): number;
  setTitlePosition$(value: number): void;
  title(): _NSString;
  setTitle$(value: _NSString): void;
  titleFont(): _NSFont;
  setTitleFont$(value: _NSFont): void;
  borderRect(): CGRect;
  titleRect(): CGRect;
  titleCell(): NobjcObject;
  contentViewMargins(): CGSize;
  setContentViewMargins$(value: CGSize): void;
  contentView(): _NSView | null;
  setContentView$(value: _NSView | null): void;
  transparent(): boolean;
  setTransparent$(value: boolean): void;
  borderWidth(): number;
  setBorderWidth$(value: number): void;
  cornerRadius(): number;
  setCornerRadius$(value: number): void;
  borderColor(): NobjcObject;
  setBorderColor$(value: NobjcObject): void;
  fillColor(): NobjcObject;
  setFillColor$(value: NobjcObject): void;
  borderType(): number;
  setBorderType$(value: number): void;
}
