// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSActionCell } from "./NSActionCell.js";
import type { _NSColor } from "./NSColor.js";
import type { _NSEvent } from "./NSEvent.js";
import type { _NSImage } from "./NSImage.js";
import type { _NSSound } from "./NSSound.js";
import type { _NSView } from "./NSView.js";
import type { _NSAttributedString } from "../Foundation/NSAttributedString.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGRect } from "../structs.js";

export declare class _NSButtonCell extends _NSActionCell {
  static alloc(): _NSButtonCell;
  static new(): _NSButtonCell;
  init(): _NSButtonCell;
  // Instance methods
  initTextCell$(string_: _NSString): _NSButtonCell;
  initImageCell$(image: _NSImage | null): _NSButtonCell;
  initWithCoder$(coder: _NSCoder): _NSButtonCell;
  setButtonType$(type: number): void;
  setPeriodicDelay$interval$(delay: number, interval: number): void;
  getPeriodicDelay$interval$(delay: NobjcObject, interval: NobjcObject): void;
  performClick$(sender: NobjcObject): void;
  mouseEntered$(event: _NSEvent): void;
  mouseExited$(event: _NSEvent): void;
  drawBezelWithFrame$inView$(frame: CGRect, controlView: _NSView): void;
  drawImage$withFrame$inView$(image: _NSImage, frame: CGRect, controlView: _NSView): void;
  drawTitle$withFrame$inView$(title: _NSAttributedString, frame: CGRect, controlView: _NSView): CGRect;
  setTitleWithMnemonic$(stringWithAmpersand: _NSString): void;
  setAlternateTitleWithMnemonic$(stringWithAmpersand: _NSString): void;
  setAlternateMnemonicLocation$(location: number): void;
  alternateMnemonicLocation(): number;
  alternateMnemonic(): _NSString;
  setKeyEquivalentFont$size$(fontName: _NSString, fontSize: number): void;

  // Properties
  bezelStyle(): number;
  setBezelStyle$(value: number): void;
  highlightsBy(): number;
  setHighlightsBy$(value: number): void;
  showsStateBy(): number;
  setShowsStateBy$(value: number): void;
  title(): _NSString;
  setTitle$(value: _NSString): void;
  attributedTitle(): _NSAttributedString;
  setAttributedTitle$(value: _NSAttributedString): void;
  alternateTitle(): _NSString;
  setAlternateTitle$(value: _NSString): void;
  attributedAlternateTitle(): _NSAttributedString;
  setAttributedAlternateTitle$(value: _NSAttributedString): void;
  alternateImage(): _NSImage | null;
  setAlternateImage$(value: _NSImage | null): void;
  imagePosition(): number;
  setImagePosition$(value: number): void;
  imageScaling(): number;
  setImageScaling$(value: number): void;
  keyEquivalent(): _NSString;
  setKeyEquivalent$(value: _NSString): void;
  keyEquivalentModifierMask(): number;
  setKeyEquivalentModifierMask$(value: number): void;
  transparent(): boolean;
  setTransparent$(value: boolean): void;
  opaque(): boolean;
  imageDimsWhenDisabled(): boolean;
  setImageDimsWhenDisabled$(value: boolean): void;
  showsBorderOnlyWhileMouseInside(): boolean;
  setShowsBorderOnlyWhileMouseInside$(value: boolean): void;
  sound(): _NSSound | null;
  setSound$(value: _NSSound | null): void;
  backgroundColor(): _NSColor | null;
  setBackgroundColor$(value: _NSColor | null): void;
  gradientType(): number;
  setGradientType$(value: number): void;
  keyEquivalentFont(): NobjcObject;
  setKeyEquivalentFont$(value: NobjcObject): void;
}
