// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSImageRep } from "./NSImageRep.js";
import type { _NSWindow } from "./NSWindow.js";
import type { CGRect, CGSize } from "../structs.js";

export declare class _NSCachedImageRep extends _NSImageRep {
  static alloc(): _NSCachedImageRep;
  static new(): _NSCachedImageRep;
  init(): _NSCachedImageRep;
  // Instance methods
  initWithWindow$rect$(win: _NSWindow, rect: CGRect): NobjcObject;
  initWithSize$depth$separate$alpha$(size: CGSize, depth: number, flag: boolean, alpha: boolean): NobjcObject;
  window(): _NSWindow;
  rect(): CGRect;
}
