// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSColor } from "./NSColor.js";
import type { _NSCursor } from "./NSCursor.js";
import type { _NSEvent } from "./NSEvent.js";
import type { _NSView } from "./NSView.js";
import type { _NSNotification } from "../Foundation/NSNotification.js";
import type { CGPoint, CGRect, NSEdgeInsets } from "../structs.js";

export declare class _NSClipView extends _NSView {
  static alloc(): _NSClipView;
  static new(): _NSClipView;
  init(): _NSClipView;
  // Instance methods
  viewFrameChanged$(notification: _NSNotification): void;
  viewBoundsChanged$(notification: _NSNotification): void;
  autoscroll$(event: _NSEvent): boolean;
  scrollToPoint$(newOrigin: CGPoint): void;
  constrainBoundsRect$(proposedBounds: CGRect): CGRect;
  constrainScrollPoint$(newOrigin: CGPoint): CGPoint;

  // Properties
  backgroundColor(): _NSColor;
  setBackgroundColor$(value: _NSColor): void;
  drawsBackground(): boolean;
  setDrawsBackground$(value: boolean): void;
  documentView(): _NSView | null;
  setDocumentView$(value: _NSView | null): void;
  documentRect(): CGRect;
  documentCursor(): _NSCursor | null;
  setDocumentCursor$(value: _NSCursor | null): void;
  documentVisibleRect(): CGRect;
  contentInsets(): NSEdgeInsets;
  setContentInsets$(value: NSEdgeInsets): void;
  automaticallyAdjustsContentInsets(): boolean;
  setAutomaticallyAdjustsContentInsets$(value: boolean): void;
  copiesOnScroll(): boolean;
  setCopiesOnScroll$(value: boolean): void;
}
