// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSColor } from "./NSColor.js";
import type { _NSView } from "./NSView.js";
import type { _NSColorPickingDefault } from "./NSColorPickingDefault.js";

export interface _NSColorPickingCustom extends _NSColorPickingDefault {
  // Instance methods
  supportsMode$?(mode: number): boolean;
  currentMode?(): number;
  provideNewView$?(initialRequest: boolean): _NSView;
  setColor$?(newColor: _NSColor): void;
}
