// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSIndexPath } from "../Foundation/NSIndexPath.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSSet } from "../Foundation/NSSet.js";
import type { _NSCollectionView } from "./NSCollectionView.js";
import type { _NSCollectionViewLayoutAttributes } from "./NSCollectionViewLayoutAttributes.js";
import type { _NSCollectionViewLayoutInvalidationContext } from "./NSCollectionViewLayoutInvalidationContext.js";
import type { _NSNib } from "./NSNib.js";
import type { CGPoint, CGRect, CGSize } from "../structs.js";

export declare class _NSCollectionViewLayout extends _NSObject {
  static alloc(): _NSCollectionViewLayout;
  static new(): _NSCollectionViewLayout;
  init(): _NSCollectionViewLayout;
  // Class methods
  static layoutAttributesClass(): NobjcObject;
  static invalidationContextClass(): NobjcObject;

  // Instance methods
  invalidateLayout(): void;
  invalidateLayoutWithContext$(context: _NSCollectionViewLayoutInvalidationContext): void;
  registerClass$forDecorationViewOfKind$(viewClass: NobjcObject, elementKind: number): void;
  registerNib$forDecorationViewOfKind$(nib: _NSNib | null, elementKind: number): void;
  prepareLayout(): void;
  layoutAttributesForElementsInRect$(rect: CGRect): _NSArray;
  layoutAttributesForItemAtIndexPath$(indexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  layoutAttributesForSupplementaryViewOfKind$atIndexPath$(elementKind: number, indexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  layoutAttributesForDecorationViewOfKind$atIndexPath$(elementKind: number, indexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  layoutAttributesForDropTargetAtPoint$(pointInCollectionView: CGPoint): _NSCollectionViewLayoutAttributes | null;
  layoutAttributesForInterItemGapBeforeIndexPath$(indexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  shouldInvalidateLayoutForBoundsChange$(newBounds: CGRect): boolean;
  invalidationContextForBoundsChange$(newBounds: CGRect): _NSCollectionViewLayoutInvalidationContext;
  shouldInvalidateLayoutForPreferredLayoutAttributes$withOriginalAttributes$(preferredAttributes: _NSCollectionViewLayoutAttributes, originalAttributes: _NSCollectionViewLayoutAttributes): boolean;
  invalidationContextForPreferredLayoutAttributes$withOriginalAttributes$(preferredAttributes: _NSCollectionViewLayoutAttributes, originalAttributes: _NSCollectionViewLayoutAttributes): _NSCollectionViewLayoutInvalidationContext;
  targetContentOffsetForProposedContentOffset$withScrollingVelocity$(proposedContentOffset: CGPoint, velocity: CGPoint): CGPoint;
  targetContentOffsetForProposedContentOffset$(proposedContentOffset: CGPoint): CGPoint;
  prepareForCollectionViewUpdates$(updateItems: _NSArray): void;
  finalizeCollectionViewUpdates(): void;
  prepareForAnimatedBoundsChange$(oldBounds: CGRect): void;
  finalizeAnimatedBoundsChange(): void;
  prepareForTransitionToLayout$(newLayout: _NSCollectionViewLayout): void;
  prepareForTransitionFromLayout$(oldLayout: _NSCollectionViewLayout): void;
  finalizeLayoutTransition(): void;
  initialLayoutAttributesForAppearingItemAtIndexPath$(itemIndexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  finalLayoutAttributesForDisappearingItemAtIndexPath$(itemIndexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  initialLayoutAttributesForAppearingSupplementaryElementOfKind$atIndexPath$(elementKind: number, elementIndexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  finalLayoutAttributesForDisappearingSupplementaryElementOfKind$atIndexPath$(elementKind: number, elementIndexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  initialLayoutAttributesForAppearingDecorationElementOfKind$atIndexPath$(elementKind: number, decorationIndexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  finalLayoutAttributesForDisappearingDecorationElementOfKind$atIndexPath$(elementKind: number, decorationIndexPath: _NSIndexPath): _NSCollectionViewLayoutAttributes | null;
  indexPathsToDeleteForSupplementaryViewOfKind$(elementKind: number): _NSSet;
  indexPathsToDeleteForDecorationViewOfKind$(elementKind: number): _NSSet;
  indexPathsToInsertForSupplementaryViewOfKind$(elementKind: number): _NSSet;
  indexPathsToInsertForDecorationViewOfKind$(elementKind: number): _NSSet;

  // Properties
  collectionView(): _NSCollectionView | null;
  collectionViewContentSize(): CGSize;
}
