// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCollectionView } from "./NSCollectionView.js";
import type { _NSCollectionViewLayout } from "./NSCollectionViewLayout.js";
import type { _NSIndexPath } from "../Foundation/NSIndexPath.js";
import type { _NSCollectionViewDelegate } from "./NSCollectionViewDelegate.js";
import type { CGSize, NSEdgeInsets } from "../structs.js";

export interface _NSCollectionViewDelegateFlowLayout extends _NSCollectionViewDelegate {
  // Instance methods
  collectionView$layout$sizeForItemAtIndexPath$?(collectionView: _NSCollectionView, collectionViewLayout: _NSCollectionViewLayout, indexPath: _NSIndexPath): CGSize;
  collectionView$layout$insetForSectionAtIndex$?(collectionView: _NSCollectionView, collectionViewLayout: _NSCollectionViewLayout, section: number): NSEdgeInsets;
  collectionView$layout$minimumLineSpacingForSectionAtIndex$?(collectionView: _NSCollectionView, collectionViewLayout: _NSCollectionViewLayout, section: number): number;
  collectionView$layout$minimumInteritemSpacingForSectionAtIndex$?(collectionView: _NSCollectionView, collectionViewLayout: _NSCollectionViewLayout, section: number): number;
  collectionView$layout$referenceSizeForHeaderInSection$?(collectionView: _NSCollectionView, collectionViewLayout: _NSCollectionViewLayout, section: number): CGSize;
  collectionView$layout$referenceSizeForFooterInSection$?(collectionView: _NSCollectionView, collectionViewLayout: _NSCollectionViewLayout, section: number): CGSize;
}
