// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSObject } from "../Foundation/NSObject.js";

export declare class _NSController extends _NSObject {
  static alloc(): _NSController;
  static new(): _NSController;
  // Instance methods
  init(): _NSController;
  initWithCoder$(coder: _NSCoder): _NSController | null;
  objectDidBeginEditing$(editor: NobjcObject): void;
  objectDidEndEditing$(editor: NobjcObject): void;
  discardEditing(): void;
  commitEditing(): boolean;
  commitEditingWithDelegate$didCommitSelector$contextInfo$(delegate: NobjcObject, didCommitSelector: string | null, contextInfo: NobjcObject): void;

  // Properties
  editing(): boolean;
}
