// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSSet } from "../Foundation/NSSet.js";
import type { CGPoint, CGSize } from "../structs.js";

export declare class _NSCollectionViewLayoutInvalidationContext extends _NSObject {
  static alloc(): _NSCollectionViewLayoutInvalidationContext;
  static new(): _NSCollectionViewLayoutInvalidationContext;
  init(): _NSCollectionViewLayoutInvalidationContext;
  // Instance methods
  invalidateItemsAtIndexPaths$(indexPaths: _NSSet): void;
  invalidateSupplementaryElementsOfKind$atIndexPaths$(elementKind: number, indexPaths: _NSSet): void;
  invalidateDecorationElementsOfKind$atIndexPaths$(elementKind: number, indexPaths: _NSSet): void;

  // Properties
  invalidateEverything(): boolean;
  invalidateDataSourceCounts(): boolean;
  invalidatedItemIndexPaths(): _NSSet | null;
  invalidatedSupplementaryIndexPaths(): NobjcObject;
  invalidatedDecorationIndexPaths(): NobjcObject;
  contentOffsetAdjustment(): CGPoint;
  setContentOffsetAdjustment$(value: CGPoint): void;
  contentSizeAdjustment(): CGSize;
  setContentSizeAdjustment$(value: CGSize): void;
}
