// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCollectionLayoutSize } from "./NSCollectionLayoutSize.js";
import type { _NSCollectionLayoutSupplementaryItem } from "./NSCollectionLayoutSupplementaryItem.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGPoint } from "../structs.js";

export declare class _NSCollectionLayoutBoundarySupplementaryItem extends _NSCollectionLayoutSupplementaryItem {
  static alloc(): _NSCollectionLayoutBoundarySupplementaryItem;
  static new(): _NSCollectionLayoutBoundarySupplementaryItem;
  init(): _NSCollectionLayoutBoundarySupplementaryItem;
  // Class methods
  static boundarySupplementaryItemWithLayoutSize$elementKind$alignment$(layoutSize: _NSCollectionLayoutSize, elementKind: _NSString, alignment: number): _NSCollectionLayoutBoundarySupplementaryItem;
  static boundarySupplementaryItemWithLayoutSize$elementKind$alignment$absoluteOffset$(layoutSize: _NSCollectionLayoutSize, elementKind: _NSString, alignment: number, absoluteOffset: CGPoint): _NSCollectionLayoutBoundarySupplementaryItem;

  // Properties
  extendsBoundary(): boolean;
  setExtendsBoundary$(value: boolean): void;
  pinToVisibleBounds(): boolean;
  setPinToVisibleBounds$(value: boolean): void;
  alignment(): number;
  offset(): CGPoint;
}
