// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSColor } from "./NSColor.js";
import type { _NSImage } from "./NSImage.js";
import type { _NSTouchBarItem } from "./NSTouchBarItem.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSColorPickerTouchBarItem extends _NSTouchBarItem {
  static alloc(): _NSColorPickerTouchBarItem;
  static new(): _NSColorPickerTouchBarItem;
  init(): _NSColorPickerTouchBarItem;
  // Class methods
  static colorPickerWithIdentifier$(identifier: number): _NSColorPickerTouchBarItem;
  static textColorPickerWithIdentifier$(identifier: number): _NSColorPickerTouchBarItem;
  static strokeColorPickerWithIdentifier$(identifier: number): _NSColorPickerTouchBarItem;
  static colorPickerWithIdentifier$buttonImage$(identifier: number, image: _NSImage): _NSColorPickerTouchBarItem;

  // Properties
  color(): _NSColor;
  setColor$(value: _NSColor): void;
  showsAlpha(): boolean;
  setShowsAlpha$(value: boolean): void;
  allowedColorSpaces(): NobjcObject;
  setAllowedColorSpaces$(value: NobjcObject): void;
  colorList(): NobjcObject;
  setColorList$(value: NobjcObject): void;
  customizationLabel(): _NSString;
  setCustomizationLabel$(value: _NSString): void;
  target(): NobjcObject;
  setTarget$(value: NobjcObject): void;
  action(): string | null;
  setAction$(value: string | null): void;
  enabled(): boolean;
  setEnabled$(value: boolean): void;
}
