// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCollectionLayoutItem } from "./NSCollectionLayoutItem.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSCollectionLayoutDecorationItem extends _NSCollectionLayoutItem {
  static alloc(): _NSCollectionLayoutDecorationItem;
  static new(): _NSCollectionLayoutDecorationItem;
  init(): _NSCollectionLayoutDecorationItem;
  // Class methods
  static backgroundDecorationItemWithElementKind$(elementKind: _NSString): _NSCollectionLayoutDecorationItem;

  // Properties
  zIndex(): number;
  setZIndex$(value: number): void;
  elementKind(): _NSString;
}
