// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { CGPoint } from "../structs.js";

export declare class _NSCollectionLayoutAnchor extends _NSObject {
  static alloc(): _NSCollectionLayoutAnchor;
  static new(): _NSCollectionLayoutAnchor;
  init(): _NSCollectionLayoutAnchor;
  // Class methods
  static layoutAnchorWithEdges$(edges: number): _NSCollectionLayoutAnchor;
  static layoutAnchorWithEdges$absoluteOffset$(edges: number, absoluteOffset: CGPoint): _NSCollectionLayoutAnchor;
  static layoutAnchorWithEdges$fractionalOffset$(edges: number, fractionalOffset: CGPoint): _NSCollectionLayoutAnchor;

  // Properties
  edges(): number;
  offset(): CGPoint;
  isAbsoluteOffset(): boolean;
  isFractionalOffset(): boolean;
}
