// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSColor } from "./NSColor.js";
import type { _NSEvent } from "./NSEvent.js";
import type { _NSImage } from "./NSImage.js";
import type { CGPoint } from "../structs.js";

export declare class _NSCursor extends _NSObject {
  static alloc(): _NSCursor;
  static new(): _NSCursor;
  init(): _NSCursor;
  // Class methods
  static hide(): void;
  static unhide(): void;
  static setHiddenUntilMouseMoves$(flag: boolean): void;
  static pop(): void;
  static columnResizeCursorInDirections$(directions: number): _NSCursor;
  static rowResizeCursorInDirections$(directions: number): _NSCursor;
  static frameResizeCursorFromPosition$inDirections$(position: number, directions: number): _NSCursor;
  static currentCursor(): _NSCursor;
  static arrowCursor(): _NSCursor;
  static crosshairCursor(): _NSCursor;
  static disappearingItemCursor(): _NSCursor;
  static operationNotAllowedCursor(): NobjcObject;
  static dragLinkCursor(): NobjcObject;
  static dragCopyCursor(): NobjcObject;
  static contextualMenuCursor(): NobjcObject;
  static pointingHandCursor(): _NSCursor;
  static closedHandCursor(): _NSCursor;
  static openHandCursor(): _NSCursor;
  static IBeamCursor(): _NSCursor;
  static IBeamCursorForVerticalLayout(): NobjcObject;
  static zoomInCursor(): NobjcObject;
  static zoomOutCursor(): NobjcObject;
  static columnResizeCursor(): NobjcObject;
  static rowResizeCursor(): NobjcObject;
  static currentSystemCursor(): NobjcObject;
  static resizeLeftCursor(): NobjcObject;
  static resizeRightCursor(): NobjcObject;
  static resizeLeftRightCursor(): NobjcObject;
  static resizeUpCursor(): NobjcObject;
  static resizeDownCursor(): NobjcObject;
  static resizeUpDownCursor(): NobjcObject;

  // Instance methods
  initWithImage$hotSpot$(newImage: _NSImage, point: CGPoint): _NSCursor;
  initWithCoder$(coder: _NSCoder): _NSCursor;
  pop(): void;
  push(): void;
  set(): void;
  initWithImage$foregroundColorHint$backgroundColorHint$hotSpot$(newImage: _NSImage, fg: _NSColor | null, bg: _NSColor | null, hotSpot: CGPoint): _NSCursor;
  setOnMouseExited$(flag: boolean): void;
  setOnMouseEntered$(flag: boolean): void;
  mouseEntered$(event: _NSEvent): void;
  mouseExited$(event: _NSEvent): void;

  // Properties
  image(): _NSImage;
  hotSpot(): CGPoint;
  setOnMouseExited(): boolean;
  setOnMouseEntered(): boolean;
}
