// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSDictionaryControllerKeyValuePair extends _NSObject {
  static alloc(): _NSDictionaryControllerKeyValuePair;
  static new(): _NSDictionaryControllerKeyValuePair;
  init(): _NSDictionaryControllerKeyValuePair;
  // Properties
  key(): _NSString | null;
  setKey$(value: _NSString | null): void;
  value(): NobjcObject;
  setValue$(value: NobjcObject): void;
  localizedKey(): _NSString | null;
  setLocalizedKey$(value: _NSString | null): void;
  explicitlyIncluded(): boolean;
}
