// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSError } from "../Foundation/NSError.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";
import type { _NSDocument } from "./NSDocument.js";
import type { _NSMenuItem } from "./NSMenuItem.js";
import type { _NSOpenPanel } from "./NSOpenPanel.js";
import type { _NSWindow } from "./NSWindow.js";

export declare class _NSDocumentController extends _NSObject {
  static alloc(): _NSDocumentController;
  static new(): _NSDocumentController;
  // Class methods
  static sharedDocumentController(): _NSDocumentController;

  // Instance methods
  init(): _NSDocumentController;
  initWithCoder$(coder: _NSCoder): _NSDocumentController | null;
  documentForURL$(url: _NSURL): _NSDocument | null;
  documentForWindow$(window: _NSWindow): _NSDocument | null;
  addDocument$(document: _NSDocument): void;
  removeDocument$(document: _NSDocument): void;
  newDocument$(sender: NobjcObject): void;
  openUntitledDocumentAndDisplay$error$(displayDocument: boolean, outError: NobjcObject): _NSDocument | null;
  makeUntitledDocumentOfType$error$(typeName: _NSString, outError: NobjcObject): _NSDocument | null;
  openDocument$(sender: NobjcObject): void;
  URLsFromRunningOpenPanel(): _NSArray | null;
  runModalOpenPanel$forTypes$(openPanel: _NSOpenPanel, types: _NSArray | null): number;
  beginOpenPanelWithCompletionHandler$(completionHandler: (...args: any[]) => any | null): void;
  beginOpenPanel$forTypes$completionHandler$(openPanel: _NSOpenPanel, inTypes: _NSArray | null, completionHandler: (...args: any[]) => any): void;
  openDocumentWithContentsOfURL$display$completionHandler$(url: _NSURL, displayDocument: boolean, completionHandler: (...args: any[]) => any | null): void;
  makeDocumentWithContentsOfURL$ofType$error$(url: _NSURL, typeName: _NSString, outError: NobjcObject): _NSDocument | null;
  reopenDocumentForURL$withContentsOfURL$display$completionHandler$(urlOrNil: _NSURL | null, contentsURL: _NSURL, displayDocument: boolean, completionHandler: (...args: any[]) => any | null): void;
  makeDocumentForURL$withContentsOfURL$ofType$error$(urlOrNil: _NSURL | null, contentsURL: _NSURL, typeName: _NSString, outError: NobjcObject): _NSDocument | null;
  saveAllDocuments$(sender: NobjcObject): void;
  reviewUnsavedDocumentsWithAlertTitle$cancellable$delegate$didReviewAllSelector$contextInfo$(title: _NSString | null, cancellable: boolean, delegate: NobjcObject, didReviewAllSelector: string | null, contextInfo: NobjcObject): void;
  closeAllDocumentsWithDelegate$didCloseAllSelector$contextInfo$(delegate: NobjcObject, didCloseAllSelector: string | null, contextInfo: NobjcObject): void;
  duplicateDocumentWithContentsOfURL$copying$displayName$error$(url: _NSURL, duplicateByCopying: boolean, displayNameOrNil: _NSString | null, outError: NobjcObject): _NSDocument | null;
  standardShareMenuItem(): _NSMenuItem;
  presentError$modalForWindow$delegate$didPresentSelector$contextInfo$(error: _NSError, window: _NSWindow, delegate: NobjcObject, didPresentSelector: string | null, contextInfo: NobjcObject): void;
  presentError$(error: _NSError): boolean;
  willPresentError$(error: _NSError): _NSError;
  clearRecentDocuments$(sender: NobjcObject): void;
  noteNewRecentDocument$(document: _NSDocument): void;
  noteNewRecentDocumentURL$(url: _NSURL): void;
  typeForContentsOfURL$error$(url: _NSURL, outError: NobjcObject): _NSString | null;
  documentClassForType$(typeName: _NSString): NobjcObject;
  displayNameForType$(typeName: _NSString): _NSString | null;
  validateUserInterfaceItem$(item: NobjcObject): boolean;
  openDocumentWithContentsOfURL$display$error$(url: _NSURL, displayDocument: boolean, outError: NobjcObject): NobjcObject;
  reopenDocumentForURL$withContentsOfURL$error$(url: _NSURL | null, contentsURL: _NSURL, outError: NobjcObject): boolean;
  fileExtensionsFromType$(typeName: _NSString): _NSArray | null;
  typeFromFileExtension$(fileNameExtensionOrHFSFileType: _NSString): _NSString | null;
  documentForFileName$(fileName: _NSString): NobjcObject;
  fileNamesFromRunningOpenPanel(): _NSArray | null;
  makeDocumentWithContentsOfFile$ofType$(fileName: _NSString, type: _NSString): NobjcObject;
  makeDocumentWithContentsOfURL$ofType$(url: _NSURL, type: _NSString): NobjcObject;
  makeUntitledDocumentOfType$(type: _NSString): NobjcObject;
  openDocumentWithContentsOfFile$display$(fileName: _NSString, display: boolean): NobjcObject;
  openDocumentWithContentsOfURL$display$(url: _NSURL, display: boolean): NobjcObject;
  openUntitledDocumentOfType$display$(type: _NSString, display: boolean): NobjcObject;
  setShouldCreateUI$(flag: boolean): void;
  shouldCreateUI(): boolean;

  // Properties
  documents(): _NSArray;
  currentDocument(): _NSDocument | null;
  currentDirectory(): _NSString | null;
  autosavingDelay(): number;
  setAutosavingDelay$(value: number): void;
  hasEditedDocuments(): boolean;
  allowsAutomaticShareMenu(): boolean;
  maximumRecentDocumentCount(): number;
  recentDocumentURLs(): _NSArray;
  defaultType(): _NSString | null;
  documentClassNames(): _NSArray;
}
