// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDockTile } from "./NSDockTile.js";
import type { _NSMenu } from "./NSMenu.js";

export interface _NSDockTilePlugIn {
  // Instance methods
  setDockTile$?(dockTile: _NSDockTile | null): void;
  dockMenu?(): _NSMenu | null;
}
