// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDrawer } from "./NSDrawer.js";
import type { _NSNotification } from "../Foundation/NSNotification.js";
import type { CGSize } from "../structs.js";

export interface _NSDrawerDelegate {
  // Instance methods
  drawerShouldOpen$?(sender: _NSDrawer): boolean;
  drawerShouldClose$?(sender: _NSDrawer): boolean;
  drawerWillResizeContents$toSize$?(sender: _NSDrawer, contentSize: CGSize): CGSize;
  drawerWillOpen$?(notification: _NSNotification): void;
  drawerDidOpen$?(notification: _NSNotification): void;
  drawerWillClose$?(notification: _NSNotification): void;
  drawerDidClose$?(notification: _NSNotification): void;
}
