// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";

export interface _NSEditorRegistration {
  // Instance methods
  objectDidBeginEditing$?(editor: NobjcObject): void;
  objectDidEndEditing$?(editor: NobjcObject): void;
}
