// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSOperationQueue } from "../Foundation/NSOperationQueue.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";
import type { _NSFilePromiseProvider } from "./NSFilePromiseProvider.js";

export interface _NSFilePromiseProviderDelegate {
  // Instance methods
  filePromiseProvider$fileNameForType$?(filePromiseProvider: _NSFilePromiseProvider, fileType: _NSString): _NSString;
  filePromiseProvider$writePromiseToURL$completionHandler$?(filePromiseProvider: _NSFilePromiseProvider, url: _NSURL, completionHandler: (...args: any[]) => any | null): void;
  operationQueueForFilePromiseProvider$?(filePromiseProvider: _NSFilePromiseProvider): _NSOperationQueue;
}
