// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSOperationQueue } from "../Foundation/NSOperationQueue.js";
import type { _NSURL } from "../Foundation/NSURL.js";

export declare class _NSFilePromiseReceiver extends _NSObject {
  static alloc(): _NSFilePromiseReceiver;
  static new(): _NSFilePromiseReceiver;
  init(): _NSFilePromiseReceiver;
  // Class methods
  static readableDraggedTypes(): _NSArray;

  // Instance methods
  receivePromisedFilesAtDestination$options$operationQueue$reader$(destinationDir: _NSURL, options: _NSDictionary, operationQueue: _NSOperationQueue, reader: (...args: any[]) => any | null): void;

  // Properties
  fileTypes(): _NSArray;
  fileNames(): _NSArray;
}
