// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSProgress } from "../Foundation/NSProgress.js";

export declare class _NSFontAssetRequest extends _NSObject {
  static alloc(): _NSFontAssetRequest;
  static new(): _NSFontAssetRequest;
  init(): _NSFontAssetRequest;
  // Instance methods
  initWithFontDescriptors$options$(fontDescriptors: _NSArray, options: number): _NSFontAssetRequest;
  downloadFontAssetsWithCompletionHandler$(completionHandler: (...args: any[]) => any | null): void;

  // Properties
  downloadedFontDescriptors(): _NSArray;
  progress(): _NSProgress;
}
