// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAffineTransform } from "../Foundation/NSAffineTransform.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSSet } from "../Foundation/NSSet.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSFontDescriptor extends _NSObject {
  static alloc(): _NSFontDescriptor;
  static new(): _NSFontDescriptor;
  init(): _NSFontDescriptor;
  // Class methods
  static fontDescriptorWithFontAttributes$(attributes: _NSDictionary | null): _NSFontDescriptor;
  static fontDescriptorWithName$size$(fontName: _NSString, size: number): _NSFontDescriptor;
  static fontDescriptorWithName$matrix$(fontName: _NSString, matrix: _NSAffineTransform): _NSFontDescriptor;
  static preferredFontDescriptorForTextStyle$options$(style: number, options: _NSDictionary): _NSFontDescriptor;

  // Instance methods
  objectForKey$(attribute: number): NobjcObject;
  initWithFontAttributes$(attributes: _NSDictionary | null): _NSFontDescriptor;
  matchingFontDescriptorsWithMandatoryKeys$(mandatoryKeys: _NSSet | null): _NSArray;
  matchingFontDescriptorWithMandatoryKeys$(mandatoryKeys: _NSSet | null): _NSFontDescriptor | null;
  fontDescriptorByAddingAttributes$(attributes: _NSDictionary): _NSFontDescriptor;
  fontDescriptorWithSymbolicTraits$(symbolicTraits: number): _NSFontDescriptor;
  fontDescriptorWithSize$(newPointSize: number): _NSFontDescriptor;
  fontDescriptorWithMatrix$(matrix: _NSAffineTransform): _NSFontDescriptor;
  fontDescriptorWithFace$(newFace: _NSString): _NSFontDescriptor;
  fontDescriptorWithFamily$(newFamily: _NSString): _NSFontDescriptor;
  fontDescriptorWithDesign$(design: number): _NSFontDescriptor | null;

  // Properties
  postscriptName(): _NSString | null;
  pointSize(): number;
  matrix(): _NSAffineTransform | null;
  symbolicTraits(): number;
  requiresFontAssetRequest(): boolean;
  fontAttributes(): _NSDictionary;
}
