// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSFont } from "./NSFont.js";
import type { _NSFormCell } from "./NSFormCell.js";
import type { _NSMatrix } from "./NSMatrix.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGSize } from "../structs.js";

export declare class _NSForm extends _NSMatrix {
  static alloc(): _NSForm;
  static new(): _NSForm;
  init(): _NSForm;
  // Instance methods
  indexOfSelectedItem(): number;
  setEntryWidth$(width: number): void;
  setInterlineSpacing$(spacing: number): void;
  setBordered$(flag: boolean): void;
  setBezeled$(flag: boolean): void;
  setTitleAlignment$(mode: number): void;
  setTextAlignment$(mode: number): void;
  setTitleFont$(fontObj: _NSFont): void;
  setTextFont$(fontObj: _NSFont): void;
  cellAtIndex$(index: number): NobjcObject;
  drawCellAtIndex$(index: number): void;
  addEntry$(title: _NSString): _NSFormCell;
  insertEntry$atIndex$(title: _NSString, index: number): _NSFormCell;
  removeEntryAtIndex$(index: number): void;
  indexOfCellWithTag$(tag: number): number;
  selectTextAtIndex$(index: number): void;
  setFrameSize$(newSize: CGSize): void;
  setTitleBaseWritingDirection$(writingDirection: number): void;
  setTextBaseWritingDirection$(writingDirection: number): void;
  setPreferredTextFieldWidth$(preferredWidth: number): void;
  preferredTextFieldWidth(): number;
}
