// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSEvent } from "./NSEvent.js";
import type { _NSView } from "./NSView.js";
import type { CGPoint } from "../structs.js";

export declare class _NSGestureRecognizer extends _NSObject {
  static alloc(): _NSGestureRecognizer;
  static new(): _NSGestureRecognizer;
  init(): _NSGestureRecognizer;
  // Instance methods
  initWithTarget$action$(target: NobjcObject, action: string | null): _NSGestureRecognizer;
  initWithCoder$(coder: _NSCoder): _NSGestureRecognizer | null;
  locationInView$(view: _NSView | null): CGPoint;
  reset(): void;
  canPreventGestureRecognizer$(preventedGestureRecognizer: _NSGestureRecognizer): boolean;
  canBePreventedByGestureRecognizer$(preventingGestureRecognizer: _NSGestureRecognizer): boolean;
  shouldRequireFailureOfGestureRecognizer$(otherGestureRecognizer: _NSGestureRecognizer): boolean;
  shouldBeRequiredToFailByGestureRecognizer$(otherGestureRecognizer: _NSGestureRecognizer): boolean;
  mouseDown$(event: _NSEvent): void;
  rightMouseDown$(event: _NSEvent): void;
  otherMouseDown$(event: _NSEvent): void;
  mouseUp$(event: _NSEvent): void;
  rightMouseUp$(event: _NSEvent): void;
  otherMouseUp$(event: _NSEvent): void;
  mouseDragged$(event: _NSEvent): void;
  rightMouseDragged$(event: _NSEvent): void;
  otherMouseDragged$(event: _NSEvent): void;
  mouseCancelled$(event: _NSEvent): void;
  keyDown$(event: _NSEvent): void;
  keyUp$(event: _NSEvent): void;
  flagsChanged$(event: _NSEvent): void;
  tabletPoint$(event: _NSEvent): void;
  magnifyWithEvent$(event: _NSEvent): void;
  rotateWithEvent$(event: _NSEvent): void;
  pressureChangeWithEvent$(event: _NSEvent): void;
  touchesBeganWithEvent$(event: _NSEvent): void;
  touchesMovedWithEvent$(event: _NSEvent): void;
  touchesEndedWithEvent$(event: _NSEvent): void;
  touchesCancelledWithEvent$(event: _NSEvent): void;

  // Properties
  target(): NobjcObject;
  setTarget$(value: NobjcObject): void;
  action(): string | null;
  setAction$(value: string | null): void;
  state(): number;
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  enabled(): boolean;
  setEnabled$(value: boolean): void;
  view(): _NSView | null;
  pressureConfiguration(): NobjcObject;
  setPressureConfiguration$(value: NobjcObject): void;
  delaysPrimaryMouseButtonEvents(): boolean;
  setDelaysPrimaryMouseButtonEvents$(value: boolean): void;
  delaysSecondaryMouseButtonEvents(): boolean;
  setDelaysSecondaryMouseButtonEvents$(value: boolean): void;
  delaysOtherMouseButtonEvents(): boolean;
  setDelaysOtherMouseButtonEvents$(value: boolean): void;
  delaysKeyEvents(): boolean;
  setDelaysKeyEvents$(value: boolean): void;
  delaysMagnificationEvents(): boolean;
  setDelaysMagnificationEvents$(value: boolean): void;
  delaysRotationEvents(): boolean;
  setDelaysRotationEvents$(value: boolean): void;
  name(): NobjcObject;
  setName$(value: NobjcObject): void;
  modifierFlags(): number;
  allowedTouchTypes(): number;
  setAllowedTouchTypes$(value: number): void;
}
