// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSColor } from "./NSColor.js";
import type { _NSView } from "./NSView.js";

export declare class _NSGlassEffectView extends _NSView {
  static alloc(): _NSGlassEffectView;
  static new(): _NSGlassEffectView;
  init(): _NSGlassEffectView;
  // Properties
  contentView(): _NSView | null;
  setContentView$(value: _NSView | null): void;
  cornerRadius(): number;
  setCornerRadius$(value: number): void;
  tintColor(): _NSColor | null;
  setTintColor$(value: _NSColor | null): void;
  style(): number;
  setStyle$(value: number): void;
}
