// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSGridCell } from "./NSGridCell.js";
import type { _NSGridView } from "./NSGridView.js";
import type { NSRange } from "../structs.js";

export declare class _NSGridColumn extends _NSObject {
  static alloc(): _NSGridColumn;
  static new(): _NSGridColumn;
  init(): _NSGridColumn;
  // Instance methods
  cellAtIndex$(index: number): _NSGridCell;
  mergeCellsInRange$(range: NSRange): void;

  // Properties
  gridView(): _NSGridView | null;
  numberOfCells(): number;
  xPlacement(): number;
  setXPlacement$(value: number): void;
  width(): number;
  setWidth$(value: number): void;
  leadingPadding(): number;
  setLeadingPadding$(value: number): void;
  trailingPadding(): number;
  setTrailingPadding$(value: number): void;
  hidden(): boolean;
  setHidden$(value: boolean): void;
}
