// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";

export declare class _NSHapticFeedbackManager extends _NSObject {
  static alloc(): _NSHapticFeedbackManager;
  static new(): _NSHapticFeedbackManager;
  init(): _NSHapticFeedbackManager;
  // Class methods
  static defaultPerformer(): NobjcObject;
}
