// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";

export interface _NSHapticFeedbackPerformer {
  // Instance methods
  performFeedbackPattern$performanceTime$?(pattern: number, performanceTime: number): void;
}
