// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCell } from "./NSCell.js";

export declare class _NSImageCell extends _NSCell {
  static alloc(): _NSImageCell;
  static new(): _NSImageCell;
  init(): _NSImageCell;
  // Properties
  imageAlignment(): number;
  setImageAlignment$(value: number): void;
  imageScaling(): number;
  setImageScaling$(value: number): void;
  imageFrameStyle(): number;
  setImageFrameStyle$(value: number): void;
}
