// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSData } from "../Foundation/NSData.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";
import type { _NSGraphicsContext } from "./NSGraphicsContext.js";
import type { _NSPasteboard } from "./NSPasteboard.js";
import type { CGPoint, CGRect, CGSize } from "../structs.js";

export declare class _NSImageRep extends _NSObject {
  static alloc(): _NSImageRep;
  static new(): _NSImageRep;
  // Class methods
  static registerImageRepClass$(imageRepClass: NobjcObject): void;
  static unregisterImageRepClass$(imageRepClass: NobjcObject): void;
  static imageRepClassForFileType$(type: _NSString): NobjcObject;
  static imageRepClassForPasteboardType$(type: number): NobjcObject;
  static imageRepClassForType$(type: _NSString): NobjcObject;
  static imageRepClassForData$(data: _NSData): NobjcObject;
  static canInitWithData$(data: _NSData): boolean;
  static imageUnfilteredFileTypes(): _NSArray;
  static imageUnfilteredPasteboardTypes(): _NSArray;
  static imageFileTypes(): _NSArray;
  static imagePasteboardTypes(): _NSArray;
  static canInitWithPasteboard$(pasteboard: _NSPasteboard): boolean;
  static imageRepsWithContentsOfFile$(filename: _NSString): _NSArray | null;
  static imageRepWithContentsOfFile$(filename: _NSString): _NSImageRep | null;
  static imageRepsWithContentsOfURL$(url: _NSURL): _NSArray | null;
  static imageRepWithContentsOfURL$(url: _NSURL): _NSImageRep | null;
  static imageRepsWithPasteboard$(pasteboard: _NSPasteboard): _NSArray | null;
  static imageRepWithPasteboard$(pasteboard: _NSPasteboard): _NSImageRep | null;
  static registeredImageRepClasses(): _NSArray;
  static imageUnfilteredTypes(): NobjcObject;
  static imageTypes(): NobjcObject;

  // Instance methods
  init(): _NSImageRep;
  initWithCoder$(coder: _NSCoder): _NSImageRep | null;
  draw(): boolean;
  drawAtPoint$(point: CGPoint): boolean;
  drawInRect$(rect: CGRect): boolean;
  drawInRect$fromRect$operation$fraction$respectFlipped$hints$(dstSpacePortionRect: CGRect, srcSpacePortionRect: CGRect, op: number, requestedAlpha: number, respectContextIsFlipped: boolean, hints: _NSDictionary | null): boolean;
  CGImageForProposedRect$context$hints$(proposedDestRect: NobjcObject, context: _NSGraphicsContext | null, hints: _NSDictionary | null): number | null;

  // Properties
  size(): CGSize;
  setSize$(value: CGSize): void;
  alpha(): boolean;
  setAlpha$(value: boolean): void;
  opaque(): boolean;
  setOpaque$(value: boolean): void;
  colorSpaceName(): number;
  setColorSpaceName$(value: number): void;
  bitsPerSample(): number;
  setBitsPerSample$(value: number): void;
  pixelsWide(): number;
  setPixelsWide$(value: number): void;
  pixelsHigh(): number;
  setPixelsHigh$(value: number): void;
  layoutDirection(): number;
  setLayoutDirection$(value: number): void;
}
