// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSControl } from "./NSControl.js";
import type { _NSImage } from "./NSImage.js";

export declare class _NSImageView extends _NSControl {
  static alloc(): _NSImageView;
  static new(): _NSImageView;
  init(): _NSImageView;
  // Class methods
  static imageViewWithImage$(image: _NSImage): _NSImageView;
  static defaultPreferredImageDynamicRange(): number;
  static setDefaultPreferredImageDynamicRange$(value: number): void;

  // Instance methods
  addSymbolEffect$(symbolEffect: NobjcObject): void;
  addSymbolEffect$options$(symbolEffect: NobjcObject, options: NobjcObject): void;
  addSymbolEffect$options$animated$(symbolEffect: NobjcObject, options: NobjcObject, animated: boolean): void;
  removeSymbolEffectOfType$(symbolEffect: NobjcObject): void;
  removeSymbolEffectOfType$options$(symbolEffect: NobjcObject, options: NobjcObject): void;
  removeSymbolEffectOfType$options$animated$(symbolEffect: NobjcObject, options: NobjcObject, animated: boolean): void;
  removeAllSymbolEffects(): void;
  removeAllSymbolEffectsWithOptions$(options: NobjcObject): void;
  removeAllSymbolEffectsWithOptions$animated$(options: NobjcObject, animated: boolean): void;
  setSymbolImage$withContentTransition$(symbolImage: _NSImage, transition: NobjcObject): void;
  setSymbolImage$withContentTransition$options$(symbolImage: _NSImage, transition: NobjcObject, options: NobjcObject): void;

  // Properties
  image(): _NSImage | null;
  setImage$(value: _NSImage | null): void;
  editable(): boolean;
  setEditable$(value: boolean): void;
  imageAlignment(): number;
  setImageAlignment$(value: number): void;
  imageScaling(): number;
  setImageScaling$(value: number): void;
  imageFrameStyle(): number;
  setImageFrameStyle$(value: number): void;
  symbolConfiguration(): NobjcObject;
  setSymbolConfiguration$(value: NobjcObject): void;
  contentTintColor(): NobjcObject;
  setContentTintColor$(value: NobjcObject): void;
  animates(): boolean;
  setAnimates$(value: boolean): void;
  allowsCutCopyPaste(): boolean;
  setAllowsCutCopyPaste$(value: boolean): void;
  preferredImageDynamicRange(): number;
  setPreferredImageDynamicRange$(value: number): void;
  imageDynamicRange(): number;
}
