// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { CGPoint } from "../structs.js";

export interface _NSInputServerMouseTracker {
  // Instance methods
  mouseDownOnCharacterIndex$atCoordinate$withModifier$client$?(index: number, point: CGPoint, flags: number, sender: NobjcObject): boolean;
  mouseDraggedOnCharacterIndex$atCoordinate$withModifier$client$?(index: number, point: CGPoint, flags: number, sender: NobjcObject): boolean;
  mouseUpOnCharacterIndex$atCoordinate$withModifier$client$?(index: number, point: CGPoint, flags: number, sender: NobjcObject): void;
}
