// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSItemBadge extends _NSObject {
  static alloc(): _NSItemBadge;
  static new(): _NSItemBadge;
  init(): _NSItemBadge;
  // Class methods
  static badgeWithCount$(count: number): _NSItemBadge;
  static badgeWithText$(text: _NSString): _NSItemBadge;
  static indicatorBadge(): _NSItemBadge;
}
