// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSLayoutAnchor } from "./NSLayoutAnchor.js";
import type { _NSLayoutConstraint } from "./NSLayoutConstraint.js";
import type { _NSLayoutDimension } from "./NSLayoutDimension.js";

export declare class _NSLayoutYAxisAnchor extends _NSLayoutAnchor {
  static alloc(): _NSLayoutYAxisAnchor;
  static new(): _NSLayoutYAxisAnchor;
  init(): _NSLayoutYAxisAnchor;
  // Instance methods
  anchorWithOffsetToAnchor$(otherAnchor: _NSLayoutYAxisAnchor): _NSLayoutDimension;
  constraintEqualToSystemSpacingBelowAnchor$multiplier$(anchor: _NSLayoutYAxisAnchor, multiplier: number): _NSLayoutConstraint;
  constraintGreaterThanOrEqualToSystemSpacingBelowAnchor$multiplier$(anchor: _NSLayoutYAxisAnchor, multiplier: number): _NSLayoutConstraint;
  constraintLessThanOrEqualToSystemSpacingBelowAnchor$multiplier$(anchor: _NSLayoutYAxisAnchor, multiplier: number): _NSLayoutConstraint;
}
