// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSLayoutAnchor } from "./NSLayoutAnchor.js";
import type { _NSLayoutConstraint } from "./NSLayoutConstraint.js";
import type { _NSLayoutDimension } from "./NSLayoutDimension.js";

export declare class _NSLayoutXAxisAnchor extends _NSLayoutAnchor {
  static alloc(): _NSLayoutXAxisAnchor;
  static new(): _NSLayoutXAxisAnchor;
  init(): _NSLayoutXAxisAnchor;
  // Instance methods
  anchorWithOffsetToAnchor$(otherAnchor: _NSLayoutXAxisAnchor): _NSLayoutDimension;
  constraintEqualToSystemSpacingAfterAnchor$multiplier$(anchor: _NSLayoutXAxisAnchor, multiplier: number): _NSLayoutConstraint;
  constraintGreaterThanOrEqualToSystemSpacingAfterAnchor$multiplier$(anchor: _NSLayoutXAxisAnchor, multiplier: number): _NSLayoutConstraint;
  constraintLessThanOrEqualToSystemSpacingAfterAnchor$multiplier$(anchor: _NSLayoutXAxisAnchor, multiplier: number): _NSLayoutConstraint;
}
