// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSLayoutConstraint } from "./NSLayoutConstraint.js";

export declare class _NSLayoutAnchor extends _NSObject {
  static alloc(): _NSLayoutAnchor;
  static new(): _NSLayoutAnchor;
  init(): _NSLayoutAnchor;
  // Instance methods
  constraintEqualToAnchor$(anchor: _NSLayoutAnchor): _NSLayoutConstraint;
  constraintGreaterThanOrEqualToAnchor$(anchor: _NSLayoutAnchor): _NSLayoutConstraint;
  constraintLessThanOrEqualToAnchor$(anchor: _NSLayoutAnchor): _NSLayoutConstraint;
  constraintEqualToAnchor$constant$(anchor: _NSLayoutAnchor, c: number): _NSLayoutConstraint;
  constraintGreaterThanOrEqualToAnchor$constant$(anchor: _NSLayoutAnchor, c: number): _NSLayoutConstraint;
  constraintLessThanOrEqualToAnchor$constant$(anchor: _NSLayoutAnchor, c: number): _NSLayoutConstraint;

  // Properties
  name(): NobjcObject;
  item(): NobjcObject;
  hasAmbiguousLayout(): boolean;
  constraintsAffectingLayout(): NobjcObject;
}
