// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSActionCell } from "./NSActionCell.js";
import type { CGRect } from "../structs.js";

export declare class _NSLevelIndicatorCell extends _NSActionCell {
  static alloc(): _NSLevelIndicatorCell;
  static new(): _NSLevelIndicatorCell;
  init(): _NSLevelIndicatorCell;
  // Instance methods
  initWithLevelIndicatorStyle$(levelIndicatorStyle: number): _NSLevelIndicatorCell;
  rectOfTickMarkAtIndex$(index: number): CGRect;
  tickMarkValueAtIndex$(index: number): number;

  // Properties
  levelIndicatorStyle(): number;
  setLevelIndicatorStyle$(value: number): void;
  minValue(): number;
  setMinValue$(value: number): void;
  maxValue(): number;
  setMaxValue$(value: number): void;
  warningValue(): number;
  setWarningValue$(value: number): void;
  criticalValue(): number;
  setCriticalValue$(value: number): void;
  tickMarkPosition(): number;
  setTickMarkPosition$(value: number): void;
  numberOfTickMarks(): number;
  setNumberOfTickMarks$(value: number): void;
  numberOfMajorTickMarks(): number;
  setNumberOfMajorTickMarks$(value: number): void;
}
