// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSGestureRecognizer } from "./NSGestureRecognizer.js";

export declare class _NSMagnificationGestureRecognizer extends _NSGestureRecognizer {
  static alloc(): _NSMagnificationGestureRecognizer;
  static new(): _NSMagnificationGestureRecognizer;
  init(): _NSMagnificationGestureRecognizer;
  // Properties
  magnification(): number;
  setMagnification$(value: number): void;
}
