// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSButtonCell } from "./NSButtonCell.js";
import type { _NSMenuItem } from "./NSMenuItem.js";
import type { _NSView } from "./NSView.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGRect } from "../structs.js";

export declare class _NSMenuItemCell extends _NSButtonCell {
  static alloc(): _NSMenuItemCell;
  static new(): _NSMenuItemCell;
  init(): _NSMenuItemCell;
  // Instance methods
  initTextCell$(string_: _NSString): _NSMenuItemCell;
  initWithCoder$(coder: _NSCoder): _NSMenuItemCell;
  calcSize(): void;
  stateImageRectForBounds$(cellFrame: CGRect): CGRect;
  titleRectForBounds$(cellFrame: CGRect): CGRect;
  keyEquivalentRectForBounds$(cellFrame: CGRect): CGRect;
  drawSeparatorItemWithFrame$inView$(cellFrame: CGRect, controlView: _NSView): void;
  drawStateImageWithFrame$inView$(cellFrame: CGRect, controlView: _NSView): void;
  drawImageWithFrame$inView$(cellFrame: CGRect, controlView: _NSView): void;
  drawTitleWithFrame$inView$(cellFrame: CGRect, controlView: _NSView): void;
  drawKeyEquivalentWithFrame$inView$(cellFrame: CGRect, controlView: _NSView): void;
  drawBorderAndBackgroundWithFrame$inView$(cellFrame: CGRect, controlView: _NSView): void;

  // Properties
  menuItem(): _NSMenuItem | null;
  setMenuItem$(value: _NSMenuItem | null): void;
  needsSizing(): boolean;
  setNeedsSizing$(value: boolean): void;
  needsDisplay(): boolean;
  setNeedsDisplay$(value: boolean): void;
  stateImageWidth(): number;
  imageWidth(): number;
  titleWidth(): number;
  keyEquivalentWidth(): number;
  tag(): number;
  setTag$(value: number): void;
}
