// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDraggingSession } from "./NSDraggingSession.js";
import type { _NSOutlineView } from "./NSOutlineView.js";
import type { _NSPasteboard } from "./NSPasteboard.js";
import type { _NSTableColumn } from "./NSTableColumn.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSURL } from "../Foundation/NSURL.js";
import type { CGPoint } from "../structs.js";

export interface _NSOutlineViewDataSource {
  // Instance methods
  outlineView$numberOfChildrenOfItem$?(outlineView: _NSOutlineView, item: NobjcObject): number;
  outlineView$child$ofItem$?(outlineView: _NSOutlineView, index: number, item: NobjcObject): NobjcObject;
  outlineView$isItemExpandable$?(outlineView: _NSOutlineView, item: NobjcObject): boolean;
  outlineView$objectValueForTableColumn$byItem$?(outlineView: _NSOutlineView, tableColumn: _NSTableColumn | null, item: NobjcObject): NobjcObject;
  outlineView$setObjectValue$forTableColumn$byItem$?(outlineView: _NSOutlineView, object_: NobjcObject, tableColumn: _NSTableColumn | null, item: NobjcObject): void;
  outlineView$itemForPersistentObject$?(outlineView: _NSOutlineView, object_: NobjcObject): NobjcObject;
  outlineView$persistentObjectForItem$?(outlineView: _NSOutlineView, item: NobjcObject): NobjcObject;
  outlineView$sortDescriptorsDidChange$?(outlineView: _NSOutlineView, oldDescriptors: _NSArray): void;
  outlineView$pasteboardWriterForItem$?(outlineView: _NSOutlineView, item: NobjcObject): NobjcObject;
  outlineView$draggingSession$willBeginAtPoint$forItems$?(outlineView: _NSOutlineView, session: _NSDraggingSession, screenPoint: CGPoint, draggedItems: _NSArray): void;
  outlineView$draggingSession$endedAtPoint$operation$?(outlineView: _NSOutlineView, session: _NSDraggingSession, screenPoint: CGPoint, operation: number): void;
  outlineView$writeItems$toPasteboard$?(outlineView: _NSOutlineView, items: _NSArray, pasteboard: _NSPasteboard): boolean;
  outlineView$updateDraggingItemsForDrag$?(outlineView: _NSOutlineView, draggingInfo: NobjcObject): void;
  outlineView$validateDrop$proposedItem$proposedChildIndex$?(outlineView: _NSOutlineView, info: NobjcObject, item: NobjcObject, index: number): number;
  outlineView$acceptDrop$item$childIndex$?(outlineView: _NSOutlineView, info: NobjcObject, item: NobjcObject, index: number): boolean;
  outlineView$namesOfPromisedFilesDroppedAtDestination$forDraggedItems$?(outlineView: _NSOutlineView, dropDestination: _NSURL, items: _NSArray): _NSArray;
}
