// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSImage } from "./NSImage.js";
import type { _NSTextFieldCell } from "./NSTextFieldCell.js";
import type { _NSURL } from "../Foundation/NSURL.js";

export declare class _NSPathComponentCell extends _NSTextFieldCell {
  static alloc(): _NSPathComponentCell;
  static new(): _NSPathComponentCell;
  init(): _NSPathComponentCell;
  // Properties
  image(): _NSImage | null;
  setImage$(value: _NSImage | null): void;
  URL(): _NSURL | null;
  setURL$(value: _NSURL | null): void;
}
