// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSPasteboard } from "./NSPasteboard.js";

export interface _NSPasteboardTypeOwner {
  // Instance methods
  pasteboard$provideDataForType$?(sender: _NSPasteboard, type: number): void;
  pasteboardChangedOwner$?(sender: _NSPasteboard): void;
}
