// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSGestureRecognizer } from "./NSGestureRecognizer.js";
import type { _NSView } from "./NSView.js";
import type { CGPoint } from "../structs.js";

export declare class _NSPanGestureRecognizer extends _NSGestureRecognizer {
  static alloc(): _NSPanGestureRecognizer;
  static new(): _NSPanGestureRecognizer;
  init(): _NSPanGestureRecognizer;
  // Instance methods
  translationInView$(view: _NSView | null): CGPoint;
  setTranslation$inView$(translation: CGPoint, view: _NSView | null): void;
  velocityInView$(view: _NSView | null): CGPoint;

  // Properties
  buttonMask(): number;
  setButtonMask$(value: number): void;
  numberOfTouchesRequired(): number;
  setNumberOfTouchesRequired$(value: number): void;
}
