// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSData } from "../Foundation/NSData.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSFileWrapper } from "../Foundation/NSFileWrapper.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSSet } from "../Foundation/NSSet.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSPasteboardItem } from "./NSPasteboardItem.js";

export declare class _NSPasteboard extends _NSObject {
  static alloc(): _NSPasteboard;
  static new(): _NSPasteboard;
  init(): _NSPasteboard;
  // Class methods
  static pasteboardWithName$(name: number): _NSPasteboard;
  static pasteboardWithUniqueName(): _NSPasteboard;
  static typesFilterableTo$(type: _NSString): _NSArray;
  static pasteboardByFilteringFile$(filename: _NSString): _NSPasteboard;
  static pasteboardByFilteringData$ofType$(data: _NSData, type: _NSString): _NSPasteboard;
  static pasteboardByFilteringTypesInPasteboard$(pboard: _NSPasteboard): _NSPasteboard;
  static generalPasteboard(): _NSPasteboard;

  // Instance methods
  releaseGlobally(): void;
  prepareForNewContentsWithOptions$(options: number): number;
  clearContents(): number;
  writeObjects$(objects: NobjcObject): boolean;
  readObjectsForClasses$options$(classArray: _NSArray, options: _NSDictionary | null): _NSArray | null;
  indexOfPasteboardItem$(pasteboardItem: _NSPasteboardItem): number;
  canReadItemWithDataConformingToTypes$(types: _NSArray): boolean;
  canReadObjectForClasses$options$(classArray: _NSArray, options: _NSDictionary | null): boolean;
  declareTypes$owner$(newTypes: _NSArray, newOwner: NobjcObject): number;
  addTypes$owner$(newTypes: _NSArray, newOwner: NobjcObject): number;
  availableTypeFromArray$(types: _NSArray): _NSString | null;
  setData$forType$(data: _NSData | null, dataType: _NSString): boolean;
  setPropertyList$forType$(plist: NobjcObject, dataType: _NSString): boolean;
  setString$forType$(string_: _NSString, dataType: _NSString): boolean;
  dataForType$(dataType: _NSString): _NSData | null;
  propertyListForType$(dataType: _NSString): NobjcObject;
  stringForType$(dataType: _NSString): _NSString | null;
  detectPatternsForPatterns$completionHandler$(patterns: _NSSet, completionHandler: (...args: any[]) => any | null): void;
  detectValuesForPatterns$completionHandler$(patterns: _NSSet, completionHandler: (...args: any[]) => any | null): void;
  detectMetadataForTypes$completionHandler$(types: _NSSet, completionHandler: (...args: any[]) => any | null): void;
  writeFileContents$(filename: _NSString): boolean;
  readFileContentsType$toFile$(type: _NSString | null, filename: _NSString): _NSString | null;
  writeFileWrapper$(wrapper: _NSFileWrapper): boolean;
  readFileWrapper(): _NSFileWrapper | null;

  // Properties
  name(): number;
  changeCount(): number;
  accessBehavior(): number;
  pasteboardItems(): NobjcObject;
  types(): _NSArray | null;
}
