// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSMenu } from "./NSMenu.js";
import type { _NSOpenPanel } from "./NSOpenPanel.js";
import type { _NSPasteboard } from "./NSPasteboard.js";
import type { _NSPathComponentCell } from "./NSPathComponentCell.js";
import type { _NSPathControl } from "./NSPathControl.js";
import type { _NSPathControlItem } from "./NSPathControlItem.js";

export interface _NSPathControlDelegate {
  // Instance methods
  pathControl$shouldDragItem$withPasteboard$?(pathControl: _NSPathControl, pathItem: _NSPathControlItem, pasteboard: _NSPasteboard): boolean;
  pathControl$shouldDragPathComponentCell$withPasteboard$?(pathControl: _NSPathControl, pathComponentCell: _NSPathComponentCell, pasteboard: _NSPasteboard): boolean;
  pathControl$validateDrop$?(pathControl: _NSPathControl, info: NobjcObject): number;
  pathControl$acceptDrop$?(pathControl: _NSPathControl, info: NobjcObject): boolean;
  pathControl$willDisplayOpenPanel$?(pathControl: _NSPathControl, openPanel: _NSOpenPanel): void;
  pathControl$willPopUpMenu$?(pathControl: _NSPathControl, menu: _NSMenu): void;
}
