// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAttributedString } from "../Foundation/NSAttributedString.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSURL } from "../Foundation/NSURL.js";
import type { _NSImage } from "./NSImage.js";

export declare class _NSPathControlItem extends _NSObject {
  static alloc(): _NSPathControlItem;
  static new(): _NSPathControlItem;
  init(): _NSPathControlItem;
  // Properties
  title(): _NSString;
  setTitle$(value: _NSString): void;
  attributedTitle(): _NSAttributedString;
  setAttributedTitle$(value: _NSAttributedString): void;
  image(): _NSImage | null;
  setImage$(value: _NSImage | null): void;
  URL(): _NSURL | null;
}
