// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSPasteboard } from "./NSPasteboard.js";

export interface _NSPasteboardWriting {
  // Instance methods
  writableTypesForPasteboard$?(pasteboard: _NSPasteboard): _NSArray;
  writingOptionsForType$pasteboard$?(type: number, pasteboard: _NSPasteboard): number;
  pasteboardPropertyListForType$?(type: number): NobjcObject;
}
