// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSData } from "../Foundation/NSData.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSSet } from "../Foundation/NSSet.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSPasteboardItem extends _NSObject {
  static alloc(): _NSPasteboardItem;
  static new(): _NSPasteboardItem;
  init(): _NSPasteboardItem;
  // Instance methods
  availableTypeFromArray$(types: _NSArray): _NSString | null;
  setDataProvider$forTypes$(dataProvider: NobjcObject, types: _NSArray): boolean;
  setData$forType$(data: _NSData, type: _NSString): boolean;
  setString$forType$(string_: _NSString, type: _NSString): boolean;
  setPropertyList$forType$(propertyList: NobjcObject, type: _NSString): boolean;
  dataForType$(type: _NSString): _NSData | null;
  stringForType$(type: _NSString): _NSString | null;
  propertyListForType$(type: _NSString): NobjcObject;
  detectPatternsForPatterns$completionHandler$(patterns: _NSSet, completionHandler: (...args: any[]) => any | null): void;
  detectValuesForPatterns$completionHandler$(patterns: _NSSet, completionHandler: (...args: any[]) => any | null): void;
  detectMetadataForTypes$completionHandler$(types: _NSSet, completionHandler: (...args: any[]) => any | null): void;

  // Properties
  types(): _NSArray;
}
