// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSMenu } from "./NSMenu.js";
import type { _NSMenuItem } from "./NSMenuItem.js";
import type { _NSMenuItemCell } from "./NSMenuItemCell.js";
import type { _NSView } from "./NSView.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGRect } from "../structs.js";

export declare class _NSPopUpButtonCell extends _NSMenuItemCell {
  static alloc(): _NSPopUpButtonCell;
  static new(): _NSPopUpButtonCell;
  init(): _NSPopUpButtonCell;
  // Instance methods
  initTextCell$pullsDown$(stringValue: _NSString, pullDown: boolean): _NSPopUpButtonCell;
  initWithCoder$(coder: _NSCoder): _NSPopUpButtonCell;
  addItemWithTitle$(title: _NSString): void;
  addItemsWithTitles$(itemTitles: _NSArray): void;
  insertItemWithTitle$atIndex$(title: _NSString, index: number): void;
  removeItemWithTitle$(title: _NSString): void;
  removeItemAtIndex$(index: number): void;
  removeAllItems(): void;
  indexOfItem$(item: _NSMenuItem): number;
  indexOfItemWithTitle$(title: _NSString): number;
  indexOfItemWithTag$(tag: number): number;
  indexOfItemWithRepresentedObject$(obj: NobjcObject): number;
  indexOfItemWithTarget$andAction$(target: NobjcObject, actionSelector: string | null): number;
  itemAtIndex$(index: number): _NSMenuItem | null;
  itemWithTitle$(title: _NSString): _NSMenuItem | null;
  selectItem$(item: _NSMenuItem | null): void;
  selectItemAtIndex$(index: number): void;
  selectItemWithTitle$(title: _NSString): void;
  selectItemWithTag$(tag: number): boolean;
  synchronizeTitleAndSelectedItem(): void;
  itemTitleAtIndex$(index: number): _NSString;
  attachPopUpWithFrame$inView$(cellFrame: CGRect, controlView: _NSView): void;
  dismissPopUp(): void;
  performClickWithFrame$inView$(frame: CGRect, controlView: _NSView): void;

  // Properties
  menu(): _NSMenu | null;
  setMenu$(value: _NSMenu | null): void;
  pullsDown(): boolean;
  setPullsDown$(value: boolean): void;
  autoenablesItems(): boolean;
  setAutoenablesItems$(value: boolean): void;
  preferredEdge(): number;
  setPreferredEdge$(value: number): void;
  usesItemFromMenu(): boolean;
  setUsesItemFromMenu$(value: boolean): void;
  altersStateOfSelectedItem(): boolean;
  setAltersStateOfSelectedItem$(value: boolean): void;
  itemArray(): _NSArray;
  numberOfItems(): number;
  lastItem(): _NSMenuItem | null;
  selectedItem(): _NSMenuItem | null;
  indexOfSelectedItem(): number;
  itemTitles(): _NSArray;
  titleOfSelectedItem(): _NSString | null;
  arrowPosition(): number;
  setArrowPosition$(value: number): void;
}
