// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSPopover } from "./NSPopover.js";
import type { _NSWindow } from "./NSWindow.js";
import type { _NSNotification } from "../Foundation/NSNotification.js";

export interface _NSPopoverDelegate {
  // Instance methods
  popoverShouldClose$?(popover: _NSPopover): boolean;
  popoverShouldDetach$?(popover: _NSPopover): boolean;
  popoverDidDetach$?(popover: _NSPopover): void;
  detachableWindowForPopover$?(popover: _NSPopover): _NSWindow | null;
  popoverWillShow$?(notification: _NSNotification): void;
  popoverDidShow$?(notification: _NSNotification): void;
  popoverWillClose$?(notification: _NSNotification): void;
  popoverDidClose$?(notification: _NSNotification): void;
}
