// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGRect, CGSize } from "../structs.js";

export declare class _NSPrinter extends _NSObject {
  static alloc(): _NSPrinter;
  static new(): _NSPrinter;
  init(): _NSPrinter;
  // Class methods
  static printerWithName$(name: _NSString): _NSPrinter | null;
  static printerWithType$(type: number): _NSPrinter | null;
  static printerWithName$domain$includeUnavailable$(name: _NSString, domain: _NSString | null, flag: boolean): _NSPrinter | null;
  static printerNames(): _NSArray;
  static printerTypes(): _NSArray;

  // Instance methods
  pageSizeForPaper$(paperName: number): CGSize;
  statusForTable$(tableName: _NSString): number;
  isKey$inTable$(key: _NSString | null, table: _NSString): boolean;
  booleanForKey$inTable$(key: _NSString | null, table: _NSString): boolean;
  floatForKey$inTable$(key: _NSString | null, table: _NSString): number;
  intForKey$inTable$(key: _NSString | null, table: _NSString): number;
  rectForKey$inTable$(key: _NSString | null, table: _NSString): CGRect;
  sizeForKey$inTable$(key: _NSString | null, table: _NSString): CGSize;
  stringForKey$inTable$(key: _NSString | null, table: _NSString): _NSString | null;
  stringListForKey$inTable$(key: _NSString | null, table: _NSString): _NSArray | null;
  imageRectForPaper$(paperName: _NSString | null): CGRect;
  acceptsBinary(): boolean;
  isColor(): boolean;
  isFontAvailable$(faceName: _NSString | null): boolean;
  isOutputStackInReverseOrder(): boolean;
  domain(): _NSString;
  host(): _NSString;
  note(): _NSString;

  // Properties
  name(): _NSString;
  type(): number;
  languageLevel(): number;
  deviceDescription(): _NSDictionary;
}
