// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSItemProvider } from "../Foundation/NSItemProvider.js";
import type { _NSString } from "../Foundation/NSString.js";

export interface _NSPreviewRepresentableActivityItem {
  // Properties
  item?(): NobjcObject;
  title?(): _NSString | null;
  imageProvider?(): _NSItemProvider | null;
  iconProvider?(): _NSItemProvider | null;
}
