// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSMutableDictionary } from "../Foundation/NSMutableDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSPDFInfo } from "./NSPDFInfo.js";
import type { _NSPrinter } from "./NSPrinter.js";
import type { CGRect, CGSize } from "../structs.js";

export declare class _NSPrintInfo extends _NSObject {
  static alloc(): _NSPrintInfo;
  static new(): _NSPrintInfo;
  // Class methods
  static setDefaultPrinter$(printer: _NSPrinter | null): void;
  static sizeForPaperName$(name: number | null): CGSize;
  static sharedPrintInfo(): _NSPrintInfo;
  static setSharedPrintInfo$(value: _NSPrintInfo): void;
  static defaultPrinter(): _NSPrinter | null;

  // Instance methods
  initWithDictionary$(attributes: _NSDictionary): _NSPrintInfo;
  initWithCoder$(coder: _NSCoder): _NSPrintInfo;
  init(): _NSPrintInfo;
  dictionary(): _NSMutableDictionary;
  setUpPrintOperationDefaultValues(): void;
  PMPrintSession(): NobjcObject;
  PMPageFormat(): NobjcObject;
  PMPrintSettings(): NobjcObject;
  updateFromPMPageFormat(): void;
  updateFromPMPrintSettings(): void;
  takeSettingsFromPDFInfo$(inPDFInfo: _NSPDFInfo): void;

  // Properties
  paperName(): number | null;
  setPaperName$(value: number | null): void;
  paperSize(): CGSize;
  setPaperSize$(value: CGSize): void;
  orientation(): number;
  setOrientation$(value: number): void;
  scalingFactor(): number;
  setScalingFactor$(value: number): void;
  leftMargin(): number;
  setLeftMargin$(value: number): void;
  rightMargin(): number;
  setRightMargin$(value: number): void;
  topMargin(): number;
  setTopMargin$(value: number): void;
  bottomMargin(): number;
  setBottomMargin$(value: number): void;
  horizontallyCentered(): boolean;
  setHorizontallyCentered$(value: boolean): void;
  verticallyCentered(): boolean;
  setVerticallyCentered$(value: boolean): void;
  horizontalPagination(): number;
  setHorizontalPagination$(value: number): void;
  verticalPagination(): number;
  setVerticalPagination$(value: number): void;
  jobDisposition(): number;
  setJobDisposition$(value: number): void;
  printer(): _NSPrinter;
  setPrinter$(value: _NSPrinter): void;
  imageablePageBounds(): CGRect;
  localizedPaperName(): _NSString | null;
  printSettings(): NobjcObject;
  selectionOnly(): boolean;
  setSelectionOnly$(value: boolean): void;
}
