// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSScrubberLayout } from "./NSScrubberLayout.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";

export declare class _NSScrubberProportionalLayout extends _NSScrubberLayout {
  static alloc(): _NSScrubberProportionalLayout;
  static new(): _NSScrubberProportionalLayout;
  init(): _NSScrubberProportionalLayout;
  // Instance methods
  initWithNumberOfVisibleItems$(numberOfVisibleItems: number): _NSScrubberProportionalLayout;
  initWithCoder$(coder: _NSCoder): _NSScrubberProportionalLayout;

  // Properties
  numberOfVisibleItems(): number;
  setNumberOfVisibleItems$(value: number): void;
}
