// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { CGRect, NSEdgeInsets } from "../structs.js";

export declare class _NSScreen extends _NSObject {
  static alloc(): _NSScreen;
  static new(): _NSScreen;
  init(): _NSScreen;
  // Class methods
  static screens(): _NSArray;
  static mainScreen(): _NSScreen | null;
  static deepestScreen(): _NSScreen | null;
  static screensHaveSeparateSpaces(): boolean;

  // Instance methods
  canRepresentDisplayGamut$(displayGamut: number): boolean;
  convertRectToBacking$(rect: CGRect): CGRect;
  convertRectFromBacking$(rect: CGRect): CGRect;
  backingAlignedRect$options$(rect: CGRect, options: number): CGRect;
  displayLinkWithTarget$selector$(target: NobjcObject, selector: string): NobjcObject;
  userSpaceScaleFactor(): number;

  // Properties
  depth(): number;
  frame(): CGRect;
  visibleFrame(): CGRect;
  deviceDescription(): _NSDictionary;
  colorSpace(): NobjcObject;
  supportedWindowDepths(): NobjcObject;
  backingScaleFactor(): number;
  localizedName(): NobjcObject;
  safeAreaInsets(): NSEdgeInsets;
  auxiliaryTopLeftArea(): CGRect;
  auxiliaryTopRightArea(): CGRect;
  CGDirectDisplayID(): number;
  maximumExtendedDynamicRangeColorComponentValue(): number;
  maximumPotentialExtendedDynamicRangeColorComponentValue(): number;
  maximumReferenceExtendedDynamicRangeColorComponentValue(): number;
  maximumFramesPerSecond(): number;
  minimumRefreshInterval(): number;
  maximumRefreshInterval(): number;
  displayUpdateGranularity(): number;
  lastDisplayUpdateTimestamp(): number;
}
