// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSControl } from "./NSControl.js";
import type { _NSEvent } from "./NSEvent.js";
import type { CGPoint, CGRect } from "../structs.js";

export declare class _NSScroller extends _NSControl {
  static alloc(): _NSScroller;
  static new(): _NSScroller;
  init(): _NSScroller;
  // Class methods
  static scrollerWidthForControlSize$scrollerStyle$(controlSize: number, scrollerStyle: number): number;
  static scrollerWidthForControlSize$(controlSize: number): number;
  static scrollerWidth(): number;
  static compatibleWithOverlayScrollers(): boolean;
  static preferredScrollerStyle(): number;

  // Instance methods
  rectForPart$(partCode: number): CGRect;
  checkSpaceForParts(): void;
  drawKnob(): void;
  drawKnobSlotInRect$highlight$(slotRect: CGRect, flag: boolean): void;
  testPart$(point: CGPoint): number;
  trackKnob$(event: _NSEvent): void;
  setKnobProportion$(proportion: number): void;
  setFloatValue$knobProportion$(value: number, proportion: number): void;
  highlight$(flag: boolean): void;
  trackScrollButtons$(event: _NSEvent): void;
  drawParts(): void;
  drawArrow$highlight$(whichArrow: number, flag: boolean): void;

  // Properties
  scrollerStyle(): number;
  setScrollerStyle$(value: number): void;
  knobStyle(): number;
  setKnobStyle$(value: number): void;
  usableParts(): number;
  controlSize(): number;
  setControlSize$(value: number): void;
  hitPart(): number;
  knobProportion(): number;
  setKnobProportion$(value: number): void;
  arrowsPosition(): number;
  setArrowsPosition$(value: number): void;
  controlTint(): number;
  setControlTint$(value: number): void;
}
