// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSScrubberItemView } from "./NSScrubberItemView.js";
import type { _NSTextField } from "./NSTextField.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSScrubberTextItemView extends _NSScrubberItemView {
  static alloc(): _NSScrubberTextItemView;
  static new(): _NSScrubberTextItemView;
  init(): _NSScrubberTextItemView;
  // Properties
  textField(): _NSTextField;
  title(): _NSString;
  setTitle$(value: _NSString): void;
}
