// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSSet } from "../Foundation/NSSet.js";
import type { _NSScrubber } from "./NSScrubber.js";
import type { _NSScrubberLayoutAttributes } from "./NSScrubberLayoutAttributes.js";
import type { CGRect, CGSize } from "../structs.js";

export declare class _NSScrubberLayout extends _NSObject {
  static alloc(): _NSScrubberLayout;
  static new(): _NSScrubberLayout;
  // Class methods
  static layoutAttributesClass(): NobjcObject;

  // Instance methods
  init(): _NSScrubberLayout;
  initWithCoder$(coder: _NSCoder): _NSScrubberLayout;
  invalidateLayout(): void;
  prepareLayout(): void;
  layoutAttributesForItemAtIndex$(index: number): _NSScrubberLayoutAttributes | null;
  layoutAttributesForItemsInRect$(rect: CGRect): _NSSet;
  shouldInvalidateLayoutForChangeFromVisibleRect$toVisibleRect$(fromVisibleRect: CGRect, toVisibleRect: CGRect): boolean;

  // Properties
  scrubber(): _NSScrubber | null;
  visibleRect(): CGRect;
  scrubberContentSize(): CGSize;
  shouldInvalidateLayoutForSelectionChange(): boolean;
  shouldInvalidateLayoutForHighlightChange(): boolean;
  automaticallyMirrorsInRightToLeftLayout(): boolean;
}
