// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSScrubber } from "./NSScrubber.js";
import type { _NSScrubberItemView } from "./NSScrubberItemView.js";

export interface _NSScrubberDataSource {
  // Instance methods
  numberOfItemsForScrubber$?(scrubber: _NSScrubber): number;
  scrubber$viewForItemAtIndex$?(scrubber: _NSScrubber, index: number): _NSScrubberItemView;
}
