// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSImage } from "./NSImage.js";
import type { _NSImageView } from "./NSImageView.js";
import type { _NSScrubberItemView } from "./NSScrubberItemView.js";

export declare class _NSScrubberImageItemView extends _NSScrubberItemView {
  static alloc(): _NSScrubberImageItemView;
  static new(): _NSScrubberImageItemView;
  init(): _NSScrubberImageItemView;
  // Properties
  imageView(): _NSImageView;
  image(): _NSImage;
  setImage$(value: _NSImage): void;
  imageAlignment(): number;
  setImageAlignment$(value: number): void;
}
