// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTextFieldCell } from "./NSTextFieldCell.js";

export declare class _NSSecureTextFieldCell extends _NSTextFieldCell {
  static alloc(): _NSSecureTextFieldCell;
  static new(): _NSSecureTextFieldCell;
  init(): _NSSecureTextFieldCell;
  // Properties
  echosBullets(): boolean;
  setEchosBullets$(value: boolean): void;
}
