// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSButtonCell } from "./NSButtonCell.js";
import type { _NSMenu } from "./NSMenu.js";
import type { _NSTextFieldCell } from "./NSTextFieldCell.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGRect } from "../structs.js";

export declare class _NSSearchFieldCell extends _NSTextFieldCell {
  static alloc(): _NSSearchFieldCell;
  static new(): _NSSearchFieldCell;
  init(): _NSSearchFieldCell;
  // Instance methods
  initTextCell$(string_: _NSString): _NSSearchFieldCell;
  initWithCoder$(coder: _NSCoder): _NSSearchFieldCell;
  resetSearchButtonCell(): void;
  resetCancelButtonCell(): void;
  searchTextRectForBounds$(rect: CGRect): CGRect;
  searchButtonRectForBounds$(rect: CGRect): CGRect;
  cancelButtonRectForBounds$(rect: CGRect): CGRect;

  // Properties
  searchButtonCell(): _NSButtonCell | null;
  setSearchButtonCell$(value: _NSButtonCell | null): void;
  cancelButtonCell(): _NSButtonCell | null;
  setCancelButtonCell$(value: _NSButtonCell | null): void;
  searchMenuTemplate(): _NSMenu | null;
  setSearchMenuTemplate$(value: _NSMenu | null): void;
  sendsWholeSearchString(): boolean;
  setSendsWholeSearchString$(value: boolean): void;
  maximumRecents(): number;
  setMaximumRecents$(value: number): void;
  recentSearches(): _NSArray;
  setRecentSearches$(value: _NSArray): void;
  recentsAutosaveName(): number | null;
  setRecentsAutosaveName$(value: number | null): void;
  sendsSearchStringImmediately(): boolean;
  setSendsSearchStringImmediately$(value: boolean): void;
}
