// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSActionCell } from "./NSActionCell.js";
import type { _NSImage } from "./NSImage.js";
import type { _NSMenu } from "./NSMenu.js";
import type { _NSView } from "./NSView.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGRect } from "../structs.js";

export declare class _NSSegmentedCell extends _NSActionCell {
  static alloc(): _NSSegmentedCell;
  static new(): _NSSegmentedCell;
  init(): _NSSegmentedCell;
  // Instance methods
  selectSegmentWithTag$(tag: number): boolean;
  makeNextSegmentKey(): void;
  makePreviousSegmentKey(): void;
  setWidth$forSegment$(width: number, segment: number): void;
  widthForSegment$(segment: number): number;
  setImage$forSegment$(image: _NSImage | null, segment: number): void;
  imageForSegment$(segment: number): _NSImage | null;
  setImageScaling$forSegment$(scaling: number, segment: number): void;
  imageScalingForSegment$(segment: number): number;
  setLabel$forSegment$(label: _NSString, segment: number): void;
  labelForSegment$(segment: number): _NSString | null;
  setSelected$forSegment$(selected: boolean, segment: number): void;
  isSelectedForSegment$(segment: number): boolean;
  setEnabled$forSegment$(enabled: boolean, segment: number): void;
  isEnabledForSegment$(segment: number): boolean;
  setMenu$forSegment$(menu: _NSMenu | null, segment: number): void;
  menuForSegment$(segment: number): _NSMenu | null;
  setToolTip$forSegment$(toolTip: _NSString | null, segment: number): void;
  toolTipForSegment$(segment: number): _NSString | null;
  setTag$forSegment$(tag: number, segment: number): void;
  tagForSegment$(segment: number): number;
  drawSegment$inFrame$withView$(segment: number, frame: CGRect, controlView: _NSView): void;
  interiorBackgroundStyleForSegment$(segment: number): number;

  // Properties
  segmentCount(): number;
  setSegmentCount$(value: number): void;
  selectedSegment(): number;
  setSelectedSegment$(value: number): void;
  trackingMode(): number;
  setTrackingMode$(value: number): void;
  segmentStyle(): number;
  setSegmentStyle$(value: number): void;
}
