// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSControl } from "./NSControl.js";
import type { _NSImage } from "./NSImage.js";
import type { _NSMenu } from "./NSMenu.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGSize } from "../structs.js";

export declare class _NSSegmentedControl extends _NSControl {
  static alloc(): _NSSegmentedControl;
  static new(): _NSSegmentedControl;
  init(): _NSSegmentedControl;
  // Class methods
  static segmentedControlWithLabels$trackingMode$target$action$(labels: _NSArray, trackingMode: number, target: NobjcObject, action: string | null): _NSSegmentedControl;
  static segmentedControlWithImages$trackingMode$target$action$(images: _NSArray, trackingMode: number, target: NobjcObject, action: string | null): _NSSegmentedControl;

  // Instance methods
  selectSegmentWithTag$(tag: number): boolean;
  setWidth$forSegment$(width: number, segment: number): void;
  widthForSegment$(segment: number): number;
  setImage$forSegment$(image: _NSImage | null, segment: number): void;
  imageForSegment$(segment: number): _NSImage | null;
  setImageScaling$forSegment$(scaling: number, segment: number): void;
  imageScalingForSegment$(segment: number): number;
  setLabel$forSegment$(label: _NSString, segment: number): void;
  labelForSegment$(segment: number): _NSString | null;
  setMenu$forSegment$(menu: _NSMenu | null, segment: number): void;
  menuForSegment$(segment: number): _NSMenu | null;
  setSelected$forSegment$(selected: boolean, segment: number): void;
  isSelectedForSegment$(segment: number): boolean;
  setEnabled$forSegment$(enabled: boolean, segment: number): void;
  isEnabledForSegment$(segment: number): boolean;
  setToolTip$forSegment$(toolTip: _NSString | null, segment: number): void;
  toolTipForSegment$(segment: number): _NSString | null;
  setTag$forSegment$(tag: number, segment: number): void;
  tagForSegment$(segment: number): number;
  setShowsMenuIndicator$forSegment$(showsMenuIndicator: boolean, segment: number): void;
  showsMenuIndicatorForSegment$(segment: number): boolean;
  setAlignment$forSegment$(alignment: number, segment: number): void;
  alignmentForSegment$(segment: number): number;
  compressWithPrioritizedCompressionOptions$(prioritizedOptions: _NSArray): void;
  minimumSizeWithPrioritizedCompressionOptions$(prioritizedOptions: _NSArray): CGSize;

  // Properties
  segmentCount(): number;
  setSegmentCount$(value: number): void;
  selectedSegment(): number;
  setSelectedSegment$(value: number): void;
  segmentStyle(): number;
  setSegmentStyle$(value: number): void;
  springLoaded(): boolean;
  setSpringLoaded$(value: boolean): void;
  trackingMode(): number;
  setTrackingMode$(value: number): void;
  doubleValueForSelectedSegment(): number;
  selectedSegmentBezelColor(): NobjcObject;
  setSelectedSegmentBezelColor$(value: NobjcObject): void;
  indexOfSelectedItem(): number;
  segmentDistribution(): number;
  setSegmentDistribution$(value: number): void;
  activeCompressionOptions(): NobjcObject;
  borderShape(): number;
  setBorderShape$(value: number): void;
}
