// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTextField } from "./NSTextField.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { CGRect } from "../structs.js";

export declare class _NSSearchField extends _NSTextField {
  static alloc(): _NSSearchField;
  static new(): _NSSearchField;
  init(): _NSSearchField;
  // Instance methods
  rectForSearchTextWhenCentered$(isCentered: boolean): CGRect;
  rectForSearchButtonWhenCentered$(isCentered: boolean): CGRect;
  rectForCancelButtonWhenCentered$(isCentered: boolean): CGRect;

  // Properties
  searchTextBounds(): CGRect;
  searchButtonBounds(): CGRect;
  cancelButtonBounds(): CGRect;
  recentSearches(): _NSArray;
  setRecentSearches$(value: _NSArray): void;
  recentsAutosaveName(): number | null;
  setRecentsAutosaveName$(value: number | null): void;
  searchMenuTemplate(): NobjcObject;
  setSearchMenuTemplate$(value: NobjcObject): void;
  sendsWholeSearchString(): boolean;
  setSendsWholeSearchString$(value: boolean): void;
  maximumRecents(): number;
  setMaximumRecents$(value: number): void;
  sendsSearchStringImmediately(): boolean;
  setSendsSearchStringImmediately$(value: boolean): void;
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  centersPlaceholder(): boolean;
  setCentersPlaceholder$(value: boolean): void;
}
