// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSToolbarItem } from "./NSToolbarItem.js";

export declare class _NSSharingServicePickerToolbarItem extends _NSToolbarItem {
  static alloc(): _NSSharingServicePickerToolbarItem;
  static new(): _NSSharingServicePickerToolbarItem;
  init(): _NSSharingServicePickerToolbarItem;
  // Properties
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
}
