// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSSplitViewItemAccessoryViewController } from "./NSSplitViewItemAccessoryViewController.js";
import type { _NSViewController } from "./NSViewController.js";

export declare class _NSSplitViewItem extends _NSObject {
  static alloc(): _NSSplitViewItem;
  static new(): _NSSplitViewItem;
  init(): _NSSplitViewItem;
  // Class methods
  static splitViewItemWithViewController$(viewController: _NSViewController): _NSSplitViewItem;
  static sidebarWithViewController$(viewController: _NSViewController): _NSSplitViewItem;
  static contentListWithViewController$(viewController: _NSViewController): _NSSplitViewItem;
  static inspectorWithViewController$(viewController: _NSViewController): _NSSplitViewItem;

  // Instance methods
  addTopAlignedAccessoryViewController$(childViewController: _NSSplitViewItemAccessoryViewController): void;
  insertTopAlignedAccessoryViewController$atIndex$(childViewController: _NSSplitViewItemAccessoryViewController, index: number): void;
  removeTopAlignedAccessoryViewControllerAtIndex$(index: number): void;
  addBottomAlignedAccessoryViewController$(childViewController: _NSSplitViewItemAccessoryViewController): void;
  insertBottomAlignedAccessoryViewController$atIndex$(childViewController: _NSSplitViewItemAccessoryViewController, index: number): void;
  removeBottomAlignedAccessoryViewControllerAtIndex$(index: number): void;

  // Properties
  behavior(): number;
  viewController(): _NSViewController;
  setViewController$(value: _NSViewController): void;
  collapsed(): boolean;
  setCollapsed$(value: boolean): void;
  canCollapse(): boolean;
  setCanCollapse$(value: boolean): void;
  collapseBehavior(): number;
  setCollapseBehavior$(value: number): void;
  minimumThickness(): number;
  setMinimumThickness$(value: number): void;
  maximumThickness(): number;
  setMaximumThickness$(value: number): void;
  preferredThicknessFraction(): number;
  setPreferredThicknessFraction$(value: number): void;
  holdingPriority(): number;
  setHoldingPriority$(value: number): void;
  automaticMaximumThickness(): number;
  setAutomaticMaximumThickness$(value: number): void;
  springLoaded(): boolean;
  setSpringLoaded$(value: boolean): void;
  canCollapseFromWindowResize(): boolean;
  setCanCollapseFromWindowResize$(value: boolean): void;
  allowsFullHeightLayout(): boolean;
  setAllowsFullHeightLayout$(value: boolean): void;
  titlebarSeparatorStyle(): number;
  setTitlebarSeparatorStyle$(value: number): void;
  automaticallyAdjustsSafeAreaInsets(): boolean;
  setAutomaticallyAdjustsSafeAreaInsets$(value: boolean): void;
  topAlignedAccessoryViewControllers(): NobjcObject;
  setTopAlignedAccessoryViewControllers$(value: NobjcObject): void;
  bottomAlignedAccessoryViewControllers(): NobjcObject;
  setBottomAlignedAccessoryViewControllers$(value: NobjcObject): void;
}
