// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSView } from "./NSView.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { NSEdgeInsets } from "../structs.js";

export declare class _NSStackView extends _NSView {
  static alloc(): _NSStackView;
  static new(): _NSStackView;
  init(): _NSStackView;
  // Class methods
  static stackViewWithViews$(views: _NSArray): _NSStackView;

  // Instance methods
  setCustomSpacing$afterView$(spacing: number, view: _NSView): void;
  customSpacingAfterView$(view: _NSView): number;
  addArrangedSubview$(view: _NSView): void;
  insertArrangedSubview$atIndex$(view: _NSView, index: number): void;
  removeArrangedSubview$(view: _NSView): void;
  setVisibilityPriority$forView$(priority: number, view: _NSView): void;
  visibilityPriorityForView$(view: _NSView): number;
  clippingResistancePriorityForOrientation$(orientation: number): number;
  setClippingResistancePriority$forOrientation$(clippingResistancePriority: number, orientation: number): void;
  huggingPriorityForOrientation$(orientation: number): number;
  setHuggingPriority$forOrientation$(huggingPriority: number, orientation: number): void;
  addView$inGravity$(view: _NSView, gravity: number): void;
  insertView$atIndex$inGravity$(view: _NSView, index: number, gravity: number): void;
  removeView$(view: _NSView): void;
  viewsInGravity$(gravity: number): _NSArray;
  setViews$inGravity$(views: _NSArray, gravity: number): void;

  // Properties
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  orientation(): number;
  setOrientation$(value: number): void;
  alignment(): number;
  setAlignment$(value: number): void;
  edgeInsets(): NSEdgeInsets;
  setEdgeInsets$(value: NSEdgeInsets): void;
  distribution(): number;
  setDistribution$(value: number): void;
  spacing(): number;
  setSpacing$(value: number): void;
  detachesHiddenViews(): boolean;
  setDetachesHiddenViews$(value: boolean): void;
  arrangedSubviews(): NobjcObject;
  detachedViews(): _NSArray;
  views(): _NSArray;
  hasEqualSpacing(): boolean;
  setHasEqualSpacing$(value: boolean): void;
}
