// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSStackView } from "./NSStackView.js";
import type { _NSArray } from "../Foundation/NSArray.js";

export interface _NSStackViewDelegate {
  // Instance methods
  stackView$willDetachViews$?(stackView: _NSStackView, views: _NSArray): void;
  stackView$didReattachViews$?(stackView: _NSStackView, views: _NSArray): void;
}
