// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSColor } from "./NSColor.js";
import type { _NSTabView } from "./NSTabView.js";
import type { _NSView } from "./NSView.js";
import type { _NSViewController } from "./NSViewController.js";
import type { CGRect, CGSize } from "../structs.js";

export declare class _NSTabViewItem extends _NSObject {
  static alloc(): _NSTabViewItem;
  static new(): _NSTabViewItem;
  init(): _NSTabViewItem;
  // Class methods
  static tabViewItemWithViewController$(viewController: _NSViewController): _NSTabViewItem;

  // Instance methods
  initWithIdentifier$(identifier: NobjcObject): _NSTabViewItem;
  drawLabel$inRect$(shouldTruncateLabel: boolean, labelRect: CGRect): void;
  sizeOfLabel$(computeMin: boolean): CGSize;

  // Properties
  identifier(): NobjcObject;
  setIdentifier$(value: NobjcObject): void;
  color(): _NSColor;
  setColor$(value: _NSColor): void;
  label(): _NSString;
  setLabel$(value: _NSString): void;
  image(): NobjcObject;
  setImage$(value: NobjcObject): void;
  view(): _NSView | null;
  setView$(value: _NSView | null): void;
  viewController(): NobjcObject;
  setViewController$(value: NobjcObject): void;
  tabState(): number;
  tabView(): _NSTabView | null;
  initialFirstResponder(): _NSView | null;
  setInitialFirstResponder$(value: _NSView | null): void;
  toolTip(): NobjcObject;
  setToolTip$(value: NobjcObject): void;
}
