// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSImageView } from "./NSImageView.js";
import type { _NSTextField } from "./NSTextField.js";
import type { _NSView } from "./NSView.js";
import type { _NSArray } from "../Foundation/NSArray.js";

export declare class _NSTableCellView extends _NSView {
  static alloc(): _NSTableCellView;
  static new(): _NSTableCellView;
  init(): _NSTableCellView;
  // Properties
  objectValue(): NobjcObject;
  setObjectValue$(value: NobjcObject): void;
  textField(): _NSTextField | null;
  setTextField$(value: _NSTextField | null): void;
  imageView(): _NSImageView | null;
  setImageView$(value: _NSImageView | null): void;
  backgroundStyle(): number;
  setBackgroundStyle$(value: number): void;
  rowSizeStyle(): number;
  setRowSizeStyle$(value: number): void;
  draggingImageComponents(): _NSArray;
}
