// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSFont } from "./NSFont.js";
import type { _NSTabViewItem } from "./NSTabViewItem.js";
import type { _NSView } from "./NSView.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { CGPoint, CGRect, CGSize } from "../structs.js";

export declare class _NSTabView extends _NSView {
  static alloc(): _NSTabView;
  static new(): _NSTabView;
  init(): _NSTabView;
  // Instance methods
  selectTabViewItem$(tabViewItem: _NSTabViewItem | null): void;
  selectTabViewItemAtIndex$(index: number): void;
  selectTabViewItemWithIdentifier$(identifier: NobjcObject): void;
  takeSelectedTabViewItemFromSender$(sender: NobjcObject): void;
  selectFirstTabViewItem$(sender: NobjcObject): void;
  selectLastTabViewItem$(sender: NobjcObject): void;
  selectNextTabViewItem$(sender: NobjcObject): void;
  selectPreviousTabViewItem$(sender: NobjcObject): void;
  addTabViewItem$(tabViewItem: _NSTabViewItem): void;
  insertTabViewItem$atIndex$(tabViewItem: _NSTabViewItem, index: number): void;
  removeTabViewItem$(tabViewItem: _NSTabViewItem): void;
  tabViewItemAtPoint$(point: CGPoint): _NSTabViewItem | null;
  indexOfTabViewItem$(tabViewItem: _NSTabViewItem): number;
  tabViewItemAtIndex$(index: number): _NSTabViewItem;
  indexOfTabViewItemWithIdentifier$(identifier: NobjcObject): number;

  // Properties
  selectedTabViewItem(): _NSTabViewItem | null;
  font(): _NSFont;
  setFont$(value: _NSFont): void;
  tabViewType(): number;
  setTabViewType$(value: number): void;
  tabPosition(): number;
  setTabPosition$(value: number): void;
  tabViewBorderType(): number;
  setTabViewBorderType$(value: number): void;
  tabViewItems(): _NSArray;
  setTabViewItems$(value: _NSArray): void;
  allowsTruncatedLabels(): boolean;
  setAllowsTruncatedLabels$(value: boolean): void;
  minimumSize(): CGSize;
  drawsBackground(): boolean;
  setDrawsBackground$(value: boolean): void;
  controlSize(): number;
  setControlSize$(value: number): void;
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  contentRect(): CGRect;
  numberOfTabViewItems(): number;
  controlTint(): number;
  setControlTint$(value: number): void;
}
