// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSColor } from "./NSColor.js";

export declare class _NSTableViewRowAction extends _NSObject {
  static alloc(): _NSTableViewRowAction;
  static new(): _NSTableViewRowAction;
  init(): _NSTableViewRowAction;
  // Class methods
  static rowActionWithStyle$title$handler$(style: number, title: _NSString, handler: (...args: any[]) => any): _NSTableViewRowAction;

  // Properties
  style(): number;
  title(): _NSString;
  setTitle$(value: _NSString): void;
  backgroundColor(): _NSColor;
  setBackgroundColor$(value: _NSColor): void;
  image(): NobjcObject;
  setImage$(value: NobjcObject): void;
}
