// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSDraggingSession } from "./NSDraggingSession.js";
import type { _NSPasteboard } from "./NSPasteboard.js";
import type { _NSTableColumn } from "./NSTableColumn.js";
import type { _NSTableView } from "./NSTableView.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSIndexSet } from "../Foundation/NSIndexSet.js";
import type { _NSURL } from "../Foundation/NSURL.js";
import type { CGPoint } from "../structs.js";

export interface _NSTableViewDataSource {
  // Instance methods
  numberOfRowsInTableView$?(tableView: _NSTableView): number;
  tableView$objectValueForTableColumn$row$?(tableView: _NSTableView, tableColumn: _NSTableColumn | null, row: number): NobjcObject;
  tableView$setObjectValue$forTableColumn$row$?(tableView: _NSTableView, object_: NobjcObject, tableColumn: _NSTableColumn | null, row: number): void;
  tableView$sortDescriptorsDidChange$?(tableView: _NSTableView, oldDescriptors: _NSArray): void;
  tableView$pasteboardWriterForRow$?(tableView: _NSTableView, row: number): NobjcObject;
  tableView$draggingSession$willBeginAtPoint$forRowIndexes$?(tableView: _NSTableView, session: _NSDraggingSession, screenPoint: CGPoint, rowIndexes: _NSIndexSet): void;
  tableView$draggingSession$endedAtPoint$operation$?(tableView: _NSTableView, session: _NSDraggingSession, screenPoint: CGPoint, operation: number): void;
  tableView$updateDraggingItemsForDrag$?(tableView: _NSTableView, draggingInfo: NobjcObject): void;
  tableView$writeRowsWithIndexes$toPasteboard$?(tableView: _NSTableView, rowIndexes: _NSIndexSet, pboard: _NSPasteboard): boolean;
  tableView$validateDrop$proposedRow$proposedDropOperation$?(tableView: _NSTableView, info: NobjcObject, row: number, dropOperation: number): number;
  tableView$acceptDrop$row$dropOperation$?(tableView: _NSTableView, info: NobjcObject, row: number, dropOperation: number): boolean;
  tableView$namesOfPromisedFilesDroppedAtDestination$forDraggedRowsWithIndexes$?(tableView: _NSTableView, dropDestination: _NSURL, indexSet: _NSIndexSet): _NSArray;
}
