// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSAttributedString } from "../Foundation/NSAttributedString.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSOperationQueue } from "../Foundation/NSOperationQueue.js";
import type { _NSTextContainer } from "./NSTextContainer.js";
import type { _NSTextContentManager } from "./NSTextContentManager.js";
import type { _NSTextLayoutFragment } from "./NSTextLayoutFragment.js";
import type { _NSTextRange } from "./NSTextRange.js";
import type { _NSTextSelectionNavigation } from "./NSTextSelectionNavigation.js";
import type { _NSTextViewportLayoutController } from "./NSTextViewportLayoutController.js";
import type { CGPoint, CGRect } from "../structs.js";

export declare class _NSTextLayoutManager extends _NSObject {
  static alloc(): _NSTextLayoutManager;
  static new(): _NSTextLayoutManager;
  // Class methods
  static linkRenderingAttributes(): _NSDictionary;

  // Instance methods
  init(): _NSTextLayoutManager;
  initWithCoder$(coder: _NSCoder): _NSTextLayoutManager | null;
  replaceTextContentManager$(textContentManager: _NSTextContentManager): void;
  ensureLayoutForRange$(range: _NSTextRange): void;
  ensureLayoutForBounds$(bounds: CGRect): void;
  invalidateLayoutForRange$(range: _NSTextRange): void;
  textLayoutFragmentForPosition$(position: CGPoint): _NSTextLayoutFragment | null;
  textLayoutFragmentForLocation$(location: NobjcObject): _NSTextLayoutFragment | null;
  enumerateTextLayoutFragmentsFromLocation$options$usingBlock$(location: NobjcObject, options: number, block: (...args: any[]) => any): NobjcObject;
  enumerateRenderingAttributesFromLocation$reverse$usingBlock$(location: NobjcObject, reverse: boolean, block: (...args: any[]) => any): void;
  setRenderingAttributes$forTextRange$(renderingAttributes: _NSDictionary, textRange: _NSTextRange): void;
  addRenderingAttribute$value$forTextRange$(renderingAttribute: number, value: NobjcObject, textRange: _NSTextRange): void;
  removeRenderingAttribute$forTextRange$(renderingAttribute: number, textRange: _NSTextRange): void;
  invalidateRenderingAttributesForTextRange$(textRange: _NSTextRange): void;
  renderingAttributesForLink$atLocation$(link: NobjcObject, location: NobjcObject): _NSDictionary;
  enumerateTextSegmentsInRange$type$options$usingBlock$(textRange: _NSTextRange, type: number, options: number, block: (...args: any[]) => any | null): void;
  replaceContentsInRange$withTextElements$(range: _NSTextRange, textElements: _NSArray): void;
  replaceContentsInRange$withAttributedString$(range: _NSTextRange, attributedString: _NSAttributedString): void;

  // Properties
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  usesFontLeading(): boolean;
  setUsesFontLeading$(value: boolean): void;
  limitsLayoutForSuspiciousContents(): boolean;
  setLimitsLayoutForSuspiciousContents$(value: boolean): void;
  usesHyphenation(): boolean;
  setUsesHyphenation$(value: boolean): void;
  resolvesNaturalAlignmentWithBaseWritingDirection(): boolean;
  setResolvesNaturalAlignmentWithBaseWritingDirection$(value: boolean): void;
  textContentManager(): _NSTextContentManager | null;
  textContainer(): _NSTextContainer | null;
  setTextContainer$(value: _NSTextContainer | null): void;
  usageBoundsForTextContainer(): CGRect;
  textViewportLayoutController(): _NSTextViewportLayoutController;
  layoutQueue(): _NSOperationQueue | null;
  setLayoutQueue$(value: _NSOperationQueue | null): void;
  textSelections(): _NSArray;
  setTextSelections$(value: _NSArray): void;
  textSelectionNavigation(): _NSTextSelectionNavigation;
  setTextSelectionNavigation$(value: _NSTextSelectionNavigation): void;
  renderingAttributesValidator(): (...args: any[]) => any | null;
  setRenderingAttributesValidator$(value: (...args: any[]) => any | null): void;
}
