// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSMenu } from "./NSMenu.js";
import type { NSRange } from "../structs.js";

export declare class _NSTextCheckingController extends _NSObject {
  static alloc(): _NSTextCheckingController;
  static new(): _NSTextCheckingController;
  init(): _NSTextCheckingController;
  // Instance methods
  initWithClient$(client: NobjcObject): _NSTextCheckingController;
  invalidate(): void;
  didChangeTextInRange$(range: NSRange): void;
  insertedTextInRange$(range: NSRange): void;
  didChangeSelectedRange(): void;
  considerTextCheckingForRange$(range: NSRange): void;
  checkTextInRange$types$options$(range: NSRange, checkingTypes: number, options: _NSDictionary): void;
  checkTextInSelection$(sender: NobjcObject): void;
  checkTextInDocument$(sender: NobjcObject): void;
  orderFrontSubstitutionsPanel$(sender: NobjcObject): void;
  checkSpelling$(sender: NobjcObject): void;
  showGuessPanel$(sender: NobjcObject): void;
  changeSpelling$(sender: NobjcObject): void;
  ignoreSpelling$(sender: NobjcObject): void;
  updateCandidates(): void;
  validAnnotations(): _NSArray;
  menuAtIndex$clickedOnSelection$effectiveRange$(location: number, clickedOnSelection: boolean, effectiveRange: NobjcObject): _NSMenu | null;

  // Properties
  client(): NobjcObject;
  spellCheckerDocumentTag(): number;
  setSpellCheckerDocumentTag$(value: number): void;
}
