// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSTextSelection } from "./NSTextSelection.js";
import type { CGPoint, CGRect } from "../structs.js";

export declare class _NSTextSelectionNavigation extends _NSObject {
  static alloc(): _NSTextSelectionNavigation;
  static new(): _NSTextSelectionNavigation;
  init(): _NSTextSelectionNavigation;
  // Instance methods
  initWithDataSource$(dataSource: NobjcObject): _NSTextSelectionNavigation;
  flushLayoutCache(): void;
  destinationSelectionForTextSelection$direction$destination$extending$confined$(textSelection: _NSTextSelection, direction: number, destination: number, extending: boolean, confined: boolean): _NSTextSelection | null;
  textSelectionsInteractingAtPoint$inContainerAtLocation$anchors$modifiers$selecting$bounds$(point: CGPoint, containerLocation: NobjcObject, anchors: _NSArray, modifiers: number, selecting: boolean, bounds: CGRect): _NSArray;
  textSelectionForSelectionGranularity$enclosingTextSelection$(selectionGranularity: number, textSelection: _NSTextSelection): _NSTextSelection;
  textSelectionForSelectionGranularity$enclosingPoint$inContainerAtLocation$(selectionGranularity: number, point: CGPoint, location: NobjcObject): _NSTextSelection | null;
  resolvedInsertionLocationForTextSelection$writingDirection$(textSelection: _NSTextSelection, writingDirection: number): NobjcObject;
  deletionRangesForTextSelection$direction$destination$allowsDecomposition$(textSelection: _NSTextSelection, direction: number, destination: number, allowsDecomposition: boolean): _NSArray;

  // Properties
  textSelectionDataSource(): NobjcObject;
  allowsNonContiguousRanges(): boolean;
  setAllowsNonContiguousRanges$(value: boolean): void;
  rotatesCoordinateSystemForLayoutOrientation(): boolean;
  setRotatesCoordinateSystemForLayoutOrientation$(value: boolean): void;
}
