// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTextStorage } from "./NSTextStorage.js";
import type { NSRange } from "../structs.js";

export interface _NSTextStorageObserving {
  // Instance methods
  processEditingForTextStorage$edited$range$changeInLength$invalidatedRange$?(textStorage: _NSTextStorage, editMask: number, newCharRange: NSRange, delta: number, invalidatedCharRange: NSRange): void;
  performEditingTransactionForTextStorage$usingBlock$?(textStorage: _NSTextStorage, transaction: (...args: any[]) => any): void;

  // Properties
  textStorage?(): _NSTextStorage | null;
  setTextStorage$?(value: _NSTextStorage | null): void;
}
