// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAttributedString } from "../Foundation/NSAttributedString.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { CGPoint, CGRect, NSRange } from "../structs.js";

export declare class _NSTextLineFragment extends _NSObject {
  static alloc(): _NSTextLineFragment;
  static new(): _NSTextLineFragment;
  init(): _NSTextLineFragment;
  // Instance methods
  initWithAttributedString$range$(attributedString: _NSAttributedString, range: NSRange): _NSTextLineFragment;
  initWithCoder$(aDecoder: _NSCoder): _NSTextLineFragment | null;
  initWithString$attributes$range$(string_: _NSString, attributes: _NSDictionary, range: NSRange): _NSTextLineFragment;
  drawAtPoint$inContext$(point: CGPoint, context: number): void;
  locationForCharacterAtIndex$(index: number): CGPoint;
  characterIndexForPoint$(point: CGPoint): number;
  fractionOfDistanceThroughGlyphForPoint$(point: CGPoint): number;

  // Properties
  attributedString(): _NSAttributedString;
  characterRange(): NSRange;
  typographicBounds(): CGRect;
  glyphOrigin(): CGPoint;
}
