// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTextElement } from "./NSTextElement.js";
import type { _NSTextRange } from "./NSTextRange.js";
import type { _NSAttributedString } from "../Foundation/NSAttributedString.js";

export declare class _NSTextParagraph extends _NSTextElement {
  static alloc(): _NSTextParagraph;
  static new(): _NSTextParagraph;
  init(): _NSTextParagraph;
  // Instance methods
  initWithAttributedString$(attributedString: _NSAttributedString | null): _NSTextParagraph;

  // Properties
  attributedString(): _NSAttributedString;
  paragraphContentRange(): _NSTextRange | null;
  paragraphSeparatorRange(): _NSTextRange | null;
}
