// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSNotification } from "../Foundation/NSNotification.js";

export interface _NSTextDelegate {
  // Instance methods
  textShouldBeginEditing$?(textObject: NobjcObject): boolean;
  textShouldEndEditing$?(textObject: NobjcObject): boolean;
  textDidBeginEditing$?(notification: _NSNotification): void;
  textDidEndEditing$?(notification: _NSNotification): void;
  textDidChange$?(notification: _NSNotification): void;
}
