// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSTextAlternatives extends _NSObject {
  static alloc(): _NSTextAlternatives;
  static new(): _NSTextAlternatives;
  init(): _NSTextAlternatives;
  // Instance methods
  initWithPrimaryString$alternativeStrings$(primaryString: _NSString, alternativeStrings: _NSArray): _NSTextAlternatives;
  noteSelectedAlternativeString$(alternativeString: _NSString): void;

  // Properties
  primaryString(): _NSString;
  alternativeStrings(): _NSArray;
}
