// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";

export interface _NSTextLocation {
  // Instance methods
  compare$?(location: NobjcObject): number;
}
