// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSTextContentManager } from "./NSTextContentManager.js";
import type { _NSTextRange } from "./NSTextRange.js";

export declare class _NSTextElement extends _NSObject {
  static alloc(): _NSTextElement;
  static new(): _NSTextElement;
  init(): _NSTextElement;
  // Instance methods
  initWithTextContentManager$(textContentManager: _NSTextContentManager | null): _NSTextElement;

  // Properties
  textContentManager(): _NSTextContentManager | null;
  setTextContentManager$(value: _NSTextContentManager | null): void;
  elementRange(): _NSTextRange | null;
  setElementRange$(value: _NSTextRange | null): void;
  childElements(): NobjcObject;
  parentElement(): NobjcObject;
  isRepresentedElement(): boolean;
}
