// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTextContentStorage } from "./NSTextContentStorage.js";
import type { _NSTextParagraph } from "./NSTextParagraph.js";
import type { _NSTextContentManagerDelegate } from "./NSTextContentManagerDelegate.js";
import type { NSRange } from "../structs.js";

export interface _NSTextContentStorageDelegate extends _NSTextContentManagerDelegate {
  // Instance methods
  textContentStorage$textParagraphWithRange$?(textContentStorage: _NSTextContentStorage, range: NSRange): _NSTextParagraph | null;
}
