// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";

export interface _NSTextInputTraits {
  // Properties
  autocorrectionType?(): number;
  setAutocorrectionType$?(value: number): void;
  spellCheckingType?(): number;
  setSpellCheckingType$?(value: number): void;
  grammarCheckingType?(): number;
  setGrammarCheckingType$?(value: number): void;
  smartQuotesType?(): number;
  setSmartQuotesType$?(value: number): void;
  smartDashesType?(): number;
  setSmartDashesType$?(value: number): void;
  smartInsertDeleteType?(): number;
  setSmartInsertDeleteType$?(value: number): void;
  textReplacementType?(): number;
  setTextReplacementType$?(value: number): void;
  dataDetectionType?(): number;
  setDataDetectionType$?(value: number): void;
  linkDetectionType?(): number;
  setLinkDetectionType$?(value: number): void;
  textCompletionType?(): number;
  setTextCompletionType$?(value: number): void;
  inlinePredictionType?(): number;
  setInlinePredictionType$?(value: number): void;
  mathExpressionCompletionType?(): number;
  setMathExpressionCompletionType$?(value: number): void;
  writingToolsBehavior?(): number;
  setWritingToolsBehavior$?(value: number): void;
  allowedWritingToolsResultOptions?(): number;
  setAllowedWritingToolsResultOptions$?(value: number): void;
}
