// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSData } from "../Foundation/NSData.js";
import type { _NSFileWrapper } from "../Foundation/NSFileWrapper.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSImage } from "./NSImage.js";
import type { CGRect } from "../structs.js";

export declare class _NSTextAttachment extends _NSObject {
  static alloc(): _NSTextAttachment;
  static new(): _NSTextAttachment;
  init(): _NSTextAttachment;
  // Class methods
  static textAttachmentViewProviderClassForFileType$(fileType: _NSString): NobjcObject;
  static registerTextAttachmentViewProviderClass$forFileType$(textAttachmentViewProviderClass: NobjcObject, fileType: _NSString): void;

  // Instance methods
  initWithData$ofType$(contentData: _NSData | null, uti: _NSString | null): _NSTextAttachment;
  initWithFileWrapper$(fileWrapper: _NSFileWrapper | null): _NSTextAttachment;

  // Properties
  contents(): _NSData | null;
  setContents$(value: _NSData | null): void;
  fileType(): _NSString | null;
  setFileType$(value: _NSString | null): void;
  image(): _NSImage | null;
  setImage$(value: _NSImage | null): void;
  bounds(): CGRect;
  setBounds$(value: CGRect): void;
  fileWrapper(): _NSFileWrapper | null;
  setFileWrapper$(value: _NSFileWrapper | null): void;
  attachmentCell(): NobjcObject;
  setAttachmentCell$(value: NobjcObject): void;
  lineLayoutPadding(): number;
  setLineLayoutPadding$(value: number): void;
  allowsTextAttachmentView(): boolean;
  setAllowsTextAttachmentView$(value: boolean): void;
  usesTextAttachmentView(): boolean;
}
