// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTextElement } from "./NSTextElement.js";
import type { _NSTextLayoutFragment } from "./NSTextLayoutFragment.js";
import type { _NSTextLayoutManager } from "./NSTextLayoutManager.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";

export interface _NSTextLayoutManagerDelegate {
  // Instance methods
  textLayoutManager$textLayoutFragmentForLocation$inTextElement$?(textLayoutManager: _NSTextLayoutManager, location: NobjcObject, textElement: _NSTextElement): _NSTextLayoutFragment;
  textLayoutManager$shouldBreakLineBeforeLocation$hyphenating$?(textLayoutManager: _NSTextLayoutManager, location: NobjcObject, hyphenating: boolean): boolean;
  textLayoutManager$renderingAttributesForLink$atLocation$defaultAttributes$?(textLayoutManager: _NSTextLayoutManager, link: NobjcObject, location: NobjcObject, renderingAttributes: _NSDictionary): _NSDictionary | null;
}
