// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { _NSTextLayoutManager } from "./NSTextLayoutManager.js";
import type { _NSTextRange } from "./NSTextRange.js";

export declare class _NSTextContentManager extends _NSObject {
  static alloc(): _NSTextContentManager;
  static new(): _NSTextContentManager;
  // Instance methods
  init(): _NSTextContentManager;
  initWithCoder$(coder: _NSCoder): _NSTextContentManager | null;
  addTextLayoutManager$(textLayoutManager: _NSTextLayoutManager): void;
  removeTextLayoutManager$(textLayoutManager: _NSTextLayoutManager): void;
  synchronizeTextLayoutManagers$(completionHandler: (...args: any[]) => any | null): void;
  textElementsForRange$(range: _NSTextRange): _NSArray;
  performEditingTransactionUsingBlock$(transaction: (...args: any[]) => any): void;
  recordEditActionInRange$newTextRange$(originalTextRange: _NSTextRange, newTextRange: _NSTextRange): void;

  // Properties
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
  textLayoutManagers(): _NSArray;
  primaryTextLayoutManager(): _NSTextLayoutManager | null;
  setPrimaryTextLayoutManager$(value: _NSTextLayoutManager | null): void;
  hasEditingTransaction(): boolean;
  automaticallySynchronizesTextLayoutManagers(): boolean;
  setAutomaticallySynchronizesTextLayoutManagers$(value: boolean): void;
  automaticallySynchronizesToBackingStore(): boolean;
  setAutomaticallySynchronizesToBackingStore$(value: boolean): void;
}
