// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSObject } from "../Foundation/NSObject.js";
import type { CGRect } from "../structs.js";

export declare class _NSTextFinder extends _NSObject {
  static alloc(): _NSTextFinder;
  static new(): _NSTextFinder;
  // Class methods
  static drawIncrementalMatchHighlightInRect$(rect: CGRect): void;

  // Instance methods
  init(): _NSTextFinder;
  initWithCoder$(coder: _NSCoder): _NSTextFinder;
  performAction$(op: number): void;
  validateAction$(op: number): boolean;
  cancelFindIndicator(): void;
  noteClientStringWillChange(): void;

  // Properties
  client(): NobjcObject;
  setClient$(value: NobjcObject): void;
  findBarContainer(): NobjcObject;
  setFindBarContainer$(value: NobjcObject): void;
  findIndicatorNeedsUpdate(): boolean;
  setFindIndicatorNeedsUpdate$(value: boolean): void;
  incrementalSearchingEnabled(): boolean;
  setIncrementalSearchingEnabled$(value: boolean): void;
  incrementalSearchingShouldDimContentView(): boolean;
  setIncrementalSearchingShouldDimContentView$(value: boolean): void;
  incrementalMatchRanges(): _NSArray;
}
