// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTextLayoutFragment } from "./NSTextLayoutFragment.js";
import type { _NSTextViewportLayoutController } from "./NSTextViewportLayoutController.js";
import type { CGRect } from "../structs.js";

export interface _NSTextViewportLayoutControllerDelegate {
  // Instance methods
  viewportBoundsForTextViewportLayoutController$?(textViewportLayoutController: _NSTextViewportLayoutController): CGRect;
  textViewportLayoutController$configureRenderingSurfaceForTextLayoutFragment$?(textViewportLayoutController: _NSTextViewportLayoutController, textLayoutFragment: _NSTextLayoutFragment): void;
  textViewportLayoutControllerWillLayout$?(textViewportLayoutController: _NSTextViewportLayoutController): void;
  textViewportLayoutControllerDidLayout$?(textViewportLayoutController: _NSTextViewportLayoutController): void;
}
