// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSString } from "../Foundation/NSString.js";
import type { _NSMenu } from "./NSMenu.js";
import type { _NSPasteboard } from "./NSPasteboard.js";
import type { _NSTokenFieldCell } from "./NSTokenFieldCell.js";

export interface _NSTokenFieldCellDelegate {
  // Instance methods
  tokenFieldCell$completionsForSubstring$indexOfToken$indexOfSelectedItem$?(tokenFieldCell: _NSTokenFieldCell, substring: _NSString, tokenIndex: number, selectedIndex: NobjcObject): _NSArray;
  tokenFieldCell$shouldAddObjects$atIndex$?(tokenFieldCell: _NSTokenFieldCell, tokens: _NSArray, index: number): _NSArray;
  tokenFieldCell$displayStringForRepresentedObject$?(tokenFieldCell: _NSTokenFieldCell, representedObject: NobjcObject): _NSString | null;
  tokenFieldCell$editingStringForRepresentedObject$?(tokenFieldCell: _NSTokenFieldCell, representedObject: NobjcObject): _NSString | null;
  tokenFieldCell$representedObjectForEditingString$?(tokenFieldCell: _NSTokenFieldCell, editingString: _NSString): NobjcObject;
  tokenFieldCell$writeRepresentedObjects$toPasteboard$?(tokenFieldCell: _NSTokenFieldCell, objects: _NSArray, pboard: _NSPasteboard): boolean;
  tokenFieldCell$readFromPasteboard$?(tokenFieldCell: _NSTokenFieldCell, pboard: _NSPasteboard): _NSArray | null;
  tokenFieldCell$menuForRepresentedObject$?(tokenFieldCell: _NSTokenFieldCell, representedObject: NobjcObject): _NSMenu | null;
  tokenFieldCell$hasMenuForRepresentedObject$?(tokenFieldCell: _NSTokenFieldCell, representedObject: NobjcObject): boolean;
  tokenFieldCell$styleForRepresentedObject$?(tokenFieldCell: _NSTokenFieldCell, representedObject: NobjcObject): number;
}
