// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTextFieldCell } from "./NSTextFieldCell.js";
import type { _NSCharacterSet } from "../Foundation/NSCharacterSet.js";

export declare class _NSTokenFieldCell extends _NSTextFieldCell {
  static alloc(): _NSTokenFieldCell;
  static new(): _NSTokenFieldCell;
  init(): _NSTokenFieldCell;
  // Class methods
  static defaultCompletionDelay(): number;
  static defaultTokenizingCharacterSet(): _NSCharacterSet;

  // Properties
  tokenStyle(): number;
  setTokenStyle$(value: number): void;
  completionDelay(): number;
  setCompletionDelay$(value: number): void;
  tokenizingCharacterSet(): _NSCharacterSet;
  setTokenizingCharacterSet$(value: _NSCharacterSet): void;
  delegate(): NobjcObject;
  setDelegate$(value: NobjcObject): void;
}
