// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSToolbarItem } from "./NSToolbarItem.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSToolbarItemGroup extends _NSToolbarItem {
  static alloc(): _NSToolbarItemGroup;
  static new(): _NSToolbarItemGroup;
  init(): _NSToolbarItemGroup;
  // Class methods
  static groupWithItemIdentifier$titles$selectionMode$labels$target$action$(itemIdentifier: _NSString, titles: _NSArray, selectionMode: number, labels: _NSArray | null, target: NobjcObject, action: string | null): _NSToolbarItemGroup;
  static groupWithItemIdentifier$images$selectionMode$labels$target$action$(itemIdentifier: _NSString, images: _NSArray, selectionMode: number, labels: _NSArray | null, target: NobjcObject, action: string | null): _NSToolbarItemGroup;

  // Instance methods
  setSelected$atIndex$(selected: boolean, index: number): void;
  isSelectedAtIndex$(index: number): boolean;

  // Properties
  subitems(): _NSArray;
  setSubitems$(value: _NSArray): void;
  controlRepresentation(): number;
  setControlRepresentation$(value: number): void;
  selectionMode(): number;
  setSelectionMode$(value: number): void;
  selectedIndex(): number;
  setSelectedIndex$(value: number): void;
}
