// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSTouchBar } from "./NSTouchBar.js";
import type { _NSTouchBarItem } from "./NSTouchBarItem.js";

export interface _NSTouchBarDelegate {
  // Instance methods
  touchBar$makeItemForIdentifier$?(touchBar: _NSTouchBar, identifier: number): _NSTouchBarItem | null;
}
