// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObjectController } from "./NSObjectController.js";
import type { _NSTreeNode } from "./NSTreeNode.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSIndexPath } from "../Foundation/NSIndexPath.js";
import type { _NSString } from "../Foundation/NSString.js";

export declare class _NSTreeController extends _NSObjectController {
  static alloc(): _NSTreeController;
  static new(): _NSTreeController;
  init(): _NSTreeController;
  // Instance methods
  rearrangeObjects(): void;
  add$(sender: NobjcObject): void;
  remove$(sender: NobjcObject): void;
  addChild$(sender: NobjcObject): void;
  insert$(sender: NobjcObject): void;
  insertChild$(sender: NobjcObject): void;
  insertObject$atArrangedObjectIndexPath$(object_: NobjcObject, indexPath: _NSIndexPath): void;
  insertObjects$atArrangedObjectIndexPaths$(objects: _NSArray, indexPaths: _NSArray): void;
  removeObjectAtArrangedObjectIndexPath$(indexPath: _NSIndexPath): void;
  removeObjectsAtArrangedObjectIndexPaths$(indexPaths: _NSArray): void;
  setSelectionIndexPaths$(indexPaths: _NSArray): boolean;
  setSelectionIndexPath$(indexPath: _NSIndexPath | null): boolean;
  addSelectionIndexPaths$(indexPaths: _NSArray): boolean;
  removeSelectionIndexPaths$(indexPaths: _NSArray): boolean;
  moveNode$toIndexPath$(node: _NSTreeNode, indexPath: _NSIndexPath): void;
  moveNodes$toIndexPath$(nodes: _NSArray, startingIndexPath: _NSIndexPath): void;
  childrenKeyPathForNode$(node: _NSTreeNode): _NSString | null;
  countKeyPathForNode$(node: _NSTreeNode): _NSString | null;
  leafKeyPathForNode$(node: _NSTreeNode): _NSString | null;

  // Properties
  arrangedObjects(): _NSTreeNode;
  childrenKeyPath(): _NSString | null;
  setChildrenKeyPath$(value: _NSString | null): void;
  countKeyPath(): _NSString | null;
  setCountKeyPath$(value: _NSString | null): void;
  leafKeyPath(): _NSString | null;
  setLeafKeyPath$(value: _NSString | null): void;
  sortDescriptors(): _NSArray;
  setSortDescriptors$(value: _NSArray): void;
  content(): NobjcObject;
  setContent$(value: NobjcObject): void;
  canInsert(): boolean;
  canInsertChild(): boolean;
  canAddChild(): boolean;
  avoidsEmptySelection(): boolean;
  setAvoidsEmptySelection$(value: boolean): void;
  preservesSelection(): boolean;
  setPreservesSelection$(value: boolean): void;
  selectsInsertedObjects(): boolean;
  setSelectsInsertedObjects$(value: boolean): void;
  alwaysUsesMultipleValuesMarker(): boolean;
  setAlwaysUsesMultipleValuesMarker$(value: boolean): void;
  selectedObjects(): _NSArray;
  selectionIndexPaths(): _NSArray;
  selectionIndexPath(): _NSIndexPath | null;
  selectedNodes(): NobjcObject;
}
