// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSString } from "../Foundation/NSString.js";

export interface _NSUserInterfaceItemIdentification {
  // Properties
  identifier?(): _NSString | null;
  setIdentifier$?(value: _NSString | null): void;
}
