// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";

export interface _NSUserInterfaceItemIdentification {
  // Properties
  identifier?(): number | null;
  setIdentifier$?(value: number | null): void;
}
