// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSController } from "./NSController.js";
import type { _NSCoder } from "../Foundation/NSCoder.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSUserDefaults } from "../Foundation/NSUserDefaults.js";

export declare class _NSUserDefaultsController extends _NSController {
  static alloc(): _NSUserDefaultsController;
  static new(): _NSUserDefaultsController;
  init(): _NSUserDefaultsController;
  // Class methods
  static sharedUserDefaultsController(): _NSUserDefaultsController;

  // Instance methods
  initWithDefaults$initialValues$(defaults: _NSUserDefaults | null, initialValues: _NSDictionary | null): _NSUserDefaultsController;
  initWithCoder$(coder: _NSCoder): _NSUserDefaultsController | null;
  revert$(sender: NobjcObject): void;
  save$(sender: NobjcObject): void;
  revertToInitialValues$(sender: NobjcObject): void;

  // Properties
  defaults(): _NSUserDefaults;
  initialValues(): _NSDictionary | null;
  setInitialValues$(value: _NSDictionary | null): void;
  appliesImmediately(): boolean;
  setAppliesImmediately$(value: boolean): void;
  hasUnappliedChanges(): boolean;
  values(): NobjcObject;
}
