// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { CGRect } from "../structs.js";

export interface _NSViewContentSelectionInfo {
  // Properties
  selectionAnchorRect?(): CGRect;
}
