// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSObject } from "../Foundation/NSObject.js";

export declare class _NSViewLayoutRegion extends _NSObject {
  static alloc(): _NSViewLayoutRegion;
  static new(): _NSViewLayoutRegion;
  init(): _NSViewLayoutRegion;
  // Class methods
  static safeAreaLayoutRegionWithCornerAdaptation$(adaptivityAxis: number): _NSViewLayoutRegion;
  static marginsLayoutRegionWithCornerAdaptation$(adaptivityAxis: number): _NSViewLayoutRegion;
}
