// AUTO-GENERATED by objcjs-types generator — DO NOT EDIT
import type { NobjcObject } from "objc-js";
import type { _NSAppleEventDescriptor } from "../Foundation/NSAppleEventDescriptor.js";
import type { _NSArray } from "../Foundation/NSArray.js";
import type { _NSDictionary } from "../Foundation/NSDictionary.js";
import type { _NSObject } from "../Foundation/NSObject.js";

export declare class _NSWorkspaceOpenConfiguration extends _NSObject {
  static alloc(): _NSWorkspaceOpenConfiguration;
  static new(): _NSWorkspaceOpenConfiguration;
  init(): _NSWorkspaceOpenConfiguration;
  // Class methods
  static configuration(): _NSWorkspaceOpenConfiguration;

  // Properties
  promptsUserIfNeeded(): boolean;
  setPromptsUserIfNeeded$(value: boolean): void;
  addsToRecentItems(): boolean;
  setAddsToRecentItems$(value: boolean): void;
  activates(): boolean;
  setActivates$(value: boolean): void;
  hides(): boolean;
  setHides$(value: boolean): void;
  hidesOthers(): boolean;
  setHidesOthers$(value: boolean): void;
  forPrinting(): boolean;
  setForPrinting$(value: boolean): void;
  createsNewApplicationInstance(): boolean;
  setCreatesNewApplicationInstance$(value: boolean): void;
  allowsRunningApplicationSubstitution(): boolean;
  setAllowsRunningApplicationSubstitution$(value: boolean): void;
  arguments(): _NSArray;
  setArguments$(value: _NSArray): void;
  environment(): _NSDictionary;
  setEnvironment$(value: _NSDictionary): void;
  appleEvent(): _NSAppleEventDescriptor | null;
  setAppleEvent$(value: _NSAppleEventDescriptor | null): void;
  architecture(): NobjcObject;
  setArchitecture$(value: NobjcObject): void;
  requiresUniversalLinks(): boolean;
  setRequiresUniversalLinks$(value: boolean): void;
}
